### ISSUE TITLE
Windows path issue: gulp exec fails on windows with local jigsaw

### ISSUE THREAD

**Issue by kunstwort** [tightenco/jigsaw#100]
When running "gulp watch" on a windows machine having jigsaw installed locally, the .exec of "./vendor/bin/jigsaw" in the gulpfile fails because of a path issue. Windows interprets the leading "." as a command and results in "command not found".

working versions: 

return '"./vendor/bin/jigsaw"'
and
return 'vendor\\bin\\jigsaw' (note: double backslashes)

**Comment by damiani** [comment]
Thanks for pointing this out, added your fix in https://github.com/tightenco/jigsaw/commit/7174a8260495d15c9e9de63613334e3396541697
