### ISSUE TITLE
Error on instalation

### ISSUE THREAD

**Issue by wilburpowery** [tightenco/jigsaw#102]
Hey. 
I get the following error when I try to install with composer. 
![image](https://cloud.githubusercontent.com/assets/15817188/25559572/a2d6e52c-2cfa-11e7-9234-f7bc2b634152.png)

**Comment by wilburpowery** [comment]
I can't install it globally on Linux or Windows. Seems they're some problems when you have Laravel installed also or something. Not really sure.

**Comment by damiani** [comment]
This is covered in https://github.com/tightenco/jigsaw/issues/94, which seems to be the same conflict (probably with `laravel/valet`?) that you're experiencing, when trying to install Jigsaw globally. Try the method described [there](https://github.com/tightenco/jigsaw/issues/94#issuecomment-298230220), or install it locally to your project directory as described in the ["Installing locally" section of the docs](http://jigsaw.tighten.co/docs/installation/).

**Comment by wilburpowery** [comment]
Did a pull request to add a little description in the readme.md file. It's a good idea so no more similar issues are created. Also linked to the possible solution.
