### ISSUE TITLE
jigsaw serve error with path that includes spaces

### ISSUE THREAD

**Issue by roberttolton** [tightenco/jigsaw#105]
Hi Matt, posting this issue here as per our Slack DM.

Project path:
`/Volumes/Work Drive/vagrant-dev/client/client-microsite`

`jigsaw serve` Throws this error:
```
Server started on http://localhost:8000
Directory /Volumes/Work does not exist.
```

`gulp watch` is happy though.

**Comment by quickliketurtle** [comment]
Looks like this was fixed in master (https://github.com/tightenco/jigsaw/commit/023a751c347d23cfd70f4225439513fc14a2a24f) But not the latest tagged version.

**Comment by damiani** [comment]
This is tagged now as v1.0.5. :)
