### ISSUE TITLE
Jigsaw Build and Watch / Forms

### ISSUE THREAD

**Issue by aaesis** [tightenco/jigsaw#106]
Hi! Do we always use "jigsaw build" every time we change something in blade files? Do we have option like watching the changes and build it automatically? ex: jigsaw watch

Do we have sample contact form build through jigsaw?

**Comment by quickliketurtle** [comment]
@aaesis Jigsaw works with Laravel Elixir so all you have to do is pull that in with `npm install` then run `gulp watch` and you are set. Even though the docs don't list is specifically it does watch for changes to your blade files also.

Docs: http://jigsaw.tighten.co/docs/compiling-assets/

**Comment by quickliketurtle** [comment]
@aaesis For the contact form you would just write the markup for it and it would build as expected.  However, since you are generating a static site you would need to post to some form endpoint outside the project.

**Comment by aaesis** [comment]
@quickliketurtle Thanks dude, This is helpful on my side.

@quickliketurtle Do you have any idea also how to integrate multi language in Jigsaw?

**Comment by quickliketurtle** [comment]
@aaesis Check out issue #25, specifically @damiani's commented on May 4, That may help you out.

**Comment by aaesis** [comment]
@quickliketurtle GREAT! thanks a lot dude! save my day!
