### ISSUE TITLE
Composer conflict with laravel/valet

### ISSUE THREAD

**Issue by Strernd** [tightenco/jigsaw#108]
I only installed laravel/valet globally. This results in the following conflict:

 Problem 1
    - Conclusion: don't install tightenco/jigsaw 1.0.2
    - Conclusion: don't install tightenco/jigsaw v1.0.1
    - Conclusion: don't install illuminate/support v5.4.19
    - Conclusion: remove tightenco/collect v5.4.20
    - Conclusion: don't install illuminate/support v5.4.13|keep tightenco/collect v5.4.20
    - Conclusion: don't install illuminate/support v5.4.17|keep tightenco/collect v5.4.20
    - Installation request for tightenco/jigsaw ^1.0 -> satisfiable by tightenco/jigsaw[1.0.2, v1.0.0, v1.0.1].
    - Conclusion: don't install tightenco/collect v5.4.20|install illuminate/support v5.4.13|install illuminate/support v5.4.17
    - tightenco/jigsaw v1.0.0 requires illuminate/support ^5.4 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - don't install illuminate/support v5.4.0|don't install tightenco/collect v5.4.20
    - don't install illuminate/support v5.4.9|don't install tightenco/collect v5.4.20
    - Installation request for tightenco/collect (locked at v5.4.20) -> satisfiable by tightenco/collect[v5.4.20].

Installation failed, reverting ./composer.json to its original content.`

Is there a way to fix this?

**Comment by santigarcor** [comment]
I'm having the same issue when trying to install it. I also use laravel/valet.

**Comment by damiani** [comment]
The solution to this is covered in https://github.com/tightenco/jigsaw/issues/94 (check [this comment](https://github.com/tightenco/jigsaw/issues/94#issuecomment-298230220), specifically), or install Jigsaw locally to your project by following the directions [here](http://jigsaw.tighten.co/docs/installation/).

**Comment by santigarcor** [comment]
Ok, thanks.
