### ISSUE TITLE
File copying

### ISSUE THREAD

**Issue by Oreolek** [tightenco/jigsaw#110]
I have an `images` folder with subfolders in it. Jigsaw copies the `images` folder with files but not subfolders. What's worse, it cleans the build directory on every build, so I have to issue `cp -r` afterwards.

Can I configure or alter this behaviour?

**Comment by damiani** [comment]
Subfolders and their contents should all be copied to your build directory by default. Can you post a repo of the code that's not working so I can take a look and see what might be going on?

**Comment by Oreolek** [comment]
Can't post the repo (closed source) but found more details.

The subfolders are named:`images/_small`, `images/_large` etc. When I renamed one of them to `images/small`, Jigsaw recognized it and copied as is.

**Comment by damiani** [comment]
This is by design; Jigsaw does not directly render folders and files that are prefixed with `_`, since the underscore is used to designate layout partials or collection items (see "Preventing Layouts & Partials from Rendering" under http://jigsaw.tighten.co/docs/blade-templates-and-partials/).

**Comment by quickliketurtle** [comment]
@Oreolek As a workaround, you could use Elixir to do this. 
By default, it is running `.exec('jigsaw build', ['./source/**/*', '!./source/_assets/**/*'])`
You would just chain on to that with
`mix.copy('./source/images', 'build_' + env + '/images')`
Then when you run `gulp` it will run the build command, then copy the images directory.  You may need to update to match your source and destination folders.
