### ISSUE TITLE
Build a tool to facilitate migration from Jekyll

### ISSUE THREAD

**Issue by damiani** [tightenco/jigsaw#111]
Migrating from Jekyll is a common path for new Jigsaw users. It would be nice if we could automate this process (or, at least, most of the process).

- Talk to some of the users who have migrated sites from Jekyll to Jigsaw to uncover pain points
- Take a look at how some other SSG's handle it (Hugo, for example). There are some issues that will be challenging, like converting Jekyll's Liquid filters.

**Comment by dgursh** [comment]
@damiani What would be the primary reason behind migrating a project from Jekyll to Jigsaw? Why have people done this in the past from your XP? The outcome is the same as they are both static site generators.

**Comment by damiani** [comment]
Based on people who've blogged about it, seems to be primarily a preference for PHP over Ruby, desire to use Blade, and faster build time.
