### ISSUE TITLE
Filenames starting with a dot are ignored (again)

### ISSUE THREAD

**Issue by kostaspt** [tightenco/jigsaw#114]
I think #16 is not fixed anymore.

There is a `.htaccess` file inside my `source` folder, and it isn't copied in both local and production build.

Tried to change the `$hidden` variable to `false` [here](https://github.com/tightenco/jigsaw/blob/master/src/SiteBuilder.php#L58), to include hidden files,  but it's causing this error:

```
PHP Fatal error:  Uncaught Error: Call to a member function handleCollectionItem() on null in src/Handlers/CollectionItemHandler.php:45
```

Any ideas for a fix?

**Comment by jhoffmandev** [comment]
I get the same issue using Jigsaw 1.0.6

**Comment by mattstauffer** [comment]
I don't know if this is the same issue, but I can't build a markdown file with a dot in the name.

Example:

advanced-laravel-5.1.md

error: 
```
View [_blog.advanced-laravel-5.1] not found.
```

I can fix it by renaming it `advanced-laravel-5-1`.
