### ISSUE TITLE
"Cannot GET /" with "gulp watch"

### ISSUE THREAD

**Issue by goldfinger43** [tightenco/jigsaw#115]
Hey,

first of all, thank you for this awesome tool.
I am using "gulp watch" to compile my assets and refresh my browser. About 70% of all refreshs are working fine, but in the other 30% i get "Cannot GET /"; "localhost/ Failed to load resource: the server responded with a status of 404 (Not Found)".

It looks like browserrefresh ist faster than refreshing the build. After a manual refresh everything works again.
Is there a way to tell browserSync to wait until the build is ready?

I am on Windows 10, php 7.1.2

**Comment by adrianR84** [comment]
in gulfile.js, have you tried to add the option reloadDelay: 50 to browsersync config ? something like the below ..
        .browserSync({
            port: port,
            server: { baseDir: 'build_' + env },
            proxy: null,
            files: [ 'build_' + env + '/**/*' ],
            reloadDelay: 50
        });

**Comment by goldfinger43** [comment]
Thank you. Its working most of the time.

**Comment by adrianR84** [comment]
you can set an even higher reloadDelay like 100 or 200 and the chances of working are increasing....
