### ISSUE TITLE
[Question] Generate collection content with REST API

### ISSUE THREAD

**Issue by RogueRonin** [tightenco/jigsaw#117]
Can I populate a collection with decoded JSON objects I get from a JSON REST API?

Each object should also generate a page, because they will be the most recent blog posts.
But not always, since there's another endpoint that just carries some links and their descriptions, so no single templates needed there.

So something like

```
<?php

return [
    'collections' => [
        'posts' => [
            'remote' => someFunctionReturningAPageOrFileObjectThatIsTreatedLikeAnActualFileAndGeneratesThatFile(),
            'path' => 'blog/{date|Y-m-d}/{filename}',
            'author' => 'Tighten Co.',
        ],
    ],
];
```

**Comment by DRogue1337** [comment]
Collections with just meta data that shouldn't be actual pages but maybe just be used to generate a list of things on a single page can be prefixed with an "_" and have just the frontmatter for the meta data.

For example when getting an array of links via an api you can just iterate over the .md or .txt or whatever files and extract what you need from the frontmatter. So `url`, `alt`, `title`, `thumbnail` and display that in your link.blade.php file.

**Comment by DRogue1337** [comment]
As I didn't thought of this before I will now try to implement this using gulp like suggested here https://github.com/tightenco/jigsaw/pull/89#issuecomment-314319469

**Comment by DRogue1337** [comment]
@damiani @AyubM
Could any of you provide an example as to how to accomplish this using gulp?
I don't see how I can get the API data and create the collection files in conjunction with the jigsaw functions. Or are there none and this has to be made without the use of any possible supporting functions?

**Comment by damiani** [comment]
There's no way that I'm aware of to do this at the moment, using Jigsaw's built-in functionality. Presumably, you'd need to save the API data to a file (or files) and have Jigsaw parse those JSON files to find page content, variables, what template to use, etc. Right now, Jigsaw can't do that out of the box.

**Comment by DRogue1337** [comment]
Alright, thanks. Got another impression from the last two comments in the previously linked PR. Then I'll keep going coming up with something that can enhance jigsaw this way.

Maybe a" jigsaw javascript lib" to integrate with gulp? Don't know if that makes sense or to just alter the php build function.

**Comment by AyubM** [comment]
@DRogue1337 My thinking was to just use gulp / node to get the data from your API, then using that data format it into a blade file for your layout to use.

E.g. just generate
@section('somefield', 'somevalue')

for each of your JSON properties.

**Comment by damiani** [comment]
Consolidating discussion of this proposal to https://github.com/tightenco/jigsaw/issues/113

**Comment by damiani** [comment]
This feature has been implemented on https://github.com/tightenco/jigsaw/pull/187. Any further discussion can take place on that PR.
