### ISSUE TITLE
is there a way to use title on layout from front matter section?

### ISSUE THREAD

**Issue by w1n78** [tightenco/jigsaw#119]
let's say i have index.blade.php and have the following on top of the page

```
---
extends: _layouts.master
title: Hello World Page Title
---
```

my _layouts.master file looks like this
```
<html>
<head>
<title>{{ $page->title or '' }}</title>
</head>
<body>
@yield('body')
</body>
</html>
```

does it function/work this way because i can't get it to work or is it the wrong approach? how do i do something like that where i define the page's title on the page itself then apply it to the layout. if no value is given, empty string is displayed. thanks.

**Comment by damiani** [comment]
If you leave off the `or ''` part, it should work as expected. 

`$page` is an object with dynamic properties, so using `or` (or `isset`) will always return `true`.  If `$page->title` is empty, it will automatically return `null` and won't error.

If you do want to specify a default for cases when `title` is empty, either do that in `config.php`, or echo `{{ $page->title ?: 'The default title' }}` in your template.

**Comment by w1n78** [comment]
haha i guess i over engineered that one. thanks, that worked.
