### ISSUE TITLE
[Proposal] Plugins/Extensions for Jigsaw

### ISSUE THREAD

**Issue by DRogueRonin** [tightenco/jigsaw#120]
A way to to `composer require` a plugin would be nice, that for example introduces helper functions and partials I use for every project. So when updating a helper function or a general partial I don't have to go through every project and replace that, but just install the most recent version of my plugin and be done.

More detailed example: A Google Analytics extension you can require and just put your tracking code into `config.php` and place the function that outputs the code in the layout.

And/or maybe `npm install` a plugin to hook into the gulp build process.

**Comment by cmosguy** [comment]
I would like to upvote this idea, does anyone have a recommended way of implementing this idea?  I want to build an Algolia indexer during the build process to hook into.

**Comment by damiani** [comment]
Definitely open to this. Some things like the Google Analytics code can already be accomplished without any plugin need (just put your tracking code in `config.php` and include Google's snippet in your master template, echoing your code where appropriate), but a plugin/extension architecture would be useful, in addition to before/after middleware functionality for any custom pre-/post-processing that people might want to do.

**Comment by damiani** [comment]
We should be able to piggy-back off of [this PR](https://github.com/tightenco/jigsaw/pull/189) to support this.

**Comment by atymic** [comment]
@damiani @mattstauffer 

I would be keen to have a go at working on this. Would you be open to a PR with a WIP implementation?

**Comment by damiani** [comment]
@atymic Yes, absolutely!

**Comment by molerat619** [comment]
Any news on this? I want to import some plugins into my project like jQuery etc. 

Of course I can download the file manually and add it to the right folder, but I was wondering if you could `npm install jquery` and have Webpack actually using it in the build.

**Comment by atymic** [comment]
@molerat619 this is completely different (this is back end/php plugins).

You should already be able to do that with laravel mix?

**Comment by damiani** [comment]
@molerat619 Yes, that's already possible; install it via `npm` and adjust your `webpack.mix.js` file accordingly.
