### ISSUE TITLE
.env file for config settings

### ISSUE THREAD

**Issue by AyubM** [tightenco/jigsaw#122]
Maybe I'm misunderstanding things, but doesn't the 'baseUrl' property in config.php require different values for development and production?

Would you accept a pull request so that we could use .env files like in laravel to import configuration into config.php?

**Comment by kostaspt** [comment]
You can already do this by adding a `config.production.php` file to override values for the production environment.

Docs link: http://jigsaw.tighten.co/docs/environments/
