### ISSUE TITLE
Any Idea how to fix Critical Css using Jigsaw and Elixir ?

### ISSUE THREAD

**Issue by mrgodhani** [tightenco/jigsaw#123]
Hi
I was wondering if it is possible or is there any best work flow to solve critical CSS either using Laravel elixir or something else. I know that laravel has this package https://packagist.org/packages/krisawzm/critical-css. But How do we solve that if using Jigsaw as static site generator ?

**Comment by DRogue1337** [comment]
Maybe try https://github.com/addyosmani/critical

And apply it after the build process on the HTML files in the source folder

**Comment by mrgodhani** [comment]
@DRogue1337  Thanks. That's exactly what I did. Created elixir extension.
