### ISSUE TITLE
Nginx Config for Jigsaw + Wordpress as subfolder

### ISSUE THREAD

**Issue by mrgodhani** [tightenco/jigsaw#124]
Hi

Any idea how to have wordpress + jigsaw working together properly. So what I mean is having wordpress in subfolder under build_production. 

Problem I found is handling 404 error between two. How do we accomplish that?

**Comment by damiani** [comment]
Mixing Jigsaw with Wordpress is probably not going to be a happy combination. But, in order for it to work, you'd have to alter your `.htaccess` file to exclude certain URLs from being rewritten, so they can get passed down directly to your Jigsaw folder and aren't handled by Wordpress. In order for this to work, you'd have to be willing to have all your Jigsaw pages accessible under some common path like `/blog/...`.

If you want to go this route, this might be a good place to start: https://tanyanam.com/2012/12/09/wordpress-exclude-directory-from-url-rewrite-with-htaccess/

**Comment by mrgodhani** [comment]
So this is what I have in nginx. It works fine. But when it comes to 404 error jigsaw area would throw me error saying "No input file specified".

```
location /blog/ {
        try_files $uri $uri/ @wordpress;
    }

    location @wordpress {
        rewrite /blog/ /blog/index.php;
    }

    location ^/blog/index.php(/.*)?$ {
        fastcgi_split_path_info ^(/blog/index.php)(/.*)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    }


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/kobyinc.celertron.com-error.log error;


    location ~ \.php$ {
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
```

**Comment by DRogue1337** [comment]
You could try to set a custom error page like this

https://stackoverflow.com/q/1024199/6114451
