### ISSUE TITLE
date format in pluck() for collection

### ISSUE THREAD

**Issue by w1n78** [tightenco/jigsaw#127]
i checked out your demo on collections at https://github.com/tightenco/jigsaw-collections-demo/blob/master/source/_layouts/category.blade.php. here you demonstrate how to "group by" categories in a collection. i would like to do this with dates. my dates are YYYY-MM-DD formatted. i'd like to "group by" just the year. here is what i have.

```
// front matter on collection
---
title: blah blah
date: 2017-07-26
permalink: blah-blah
---

// i tried the following
@foreach ($events->pluck(date('Y', 'date'))->unique() as $event_date)
  {{ $event_date }}
@endforeach
```

it didn't work. i checked the laravel docs on pluck() and didn't find anything either. am i close? thanks.

**Comment by damiani** [comment]
`pluck` won't work in this case, because it doesn't receive any reference to the current `$event`. Instead, you could use `map`:

```php
@foreach ($events->map(function($event) { return date('Y', $event->date); })->unique() as $year)
    {{ $year })
@endforeach
```

You can clean this up a little more by moving that `date` function into `config.php`:

```php
return [
    'collections' => [
        'events' => [
            'year' => function($event) {
                return date('Y', $event->date);
            },
        ],
    ],
];
```

...and then using a higher-order version of `map`:

```php
@foreach ($events->map->year()->unique() as $year)
    {{ $year }}
@endforeach
```
