### ISSUE TITLE
[Proposal] Add ability to house multiple sites in one installation

### ISSUE THREAD

**Issue by adamkelso-rg** [tightenco/jigsaw#128]
Before going further, I'll specify that we're currently building out this functionality for a few things we need at work. This proposal is to see if Tighten would be interested in a pull request with the results when it's done. Thanks so much for releasing Jigsaw as open source.

## Overview
It would be nice to house multiple sites in one Jigsaw installation, with shared resources and views. This would allow several static sites to share resources, like templates or themes, and still have separate content and skins.

From the command line a user could then choose to build any specific site or all of them. This would be extremely helpful for occasions when a resource shared by multiple sites changes and everything needs to be updated.

## Our Current Plan
The idea so far has been to include a _config.php_ file in the root of the installation, specifying the source locations and build destination of each **domain**. During the build process, the build job iterates over each domain and simply loads it's specific config file and then builds like normal.

Also in the root config is a **namespaces** array that specifies source locations of views that can be turned into Laravel view modules. By doing so, any domain can use the namespaced resources with the syntax `@include('Module::folder.view')`.

Thanks again for the work on Jigsaw and the other Laravel community efforts.

**Comment by damiani** [comment]
Yes, this would be a great addition. My initial thoughts are to keep the definition in the root `config.php` as simple as possible, so perhaps just a `sites` array with keys for each site that point to the `source` locations, and then let each individual site specify their build locations in their own `config.php` files. something like:

```php
return [
    'sites' => [
        'site-1' => 'source_main',
        'site-2' => 'source_secondary'
    ],
    'namespaces' => [
        'Shared' => 'shared_resources',
    ],
];
```

...then, you would run `jigsaw build site-1` for a single site, or just `jigsaw build` to build all of them.

I look forward to your PR!

**Comment by adamkelso-rg** [comment]
Great!

That's pretty close to what I have so far, except I've been editing with the build destination in the root config.

```php
return [
    'domains' => [
        'directory-of-site-1' => 'build-destination-of-site-1',
        'directory-of-site-2' => 'build-destination-of-site-2'
    ],
    'namespaces' => [
        'parent' => 'parent-directory',
        'another' => 'somewhere-else'
    ]
];
```

However, I think you're right, it would make more sense to leave that in each site's configuration.

Also, I'm currently assuming the directories for each site have a **source** directory inside, and a **config.php** at the root of each site. This sound like a fair assumption to you, or do you think the exact source and exact config file should be specified in the sites array?

One issue though, with this is the flow of serving would be a problem. You would need to specify a site to **serve**. I guess we can do a check inside both **serve** and **build** to see if the sites array exists before modifying behavior.

**Comment by damiani** [comment]
>Also, I'm currently assuming the directories for each site have a source directory inside, and a config.php at the root of each site. This sound like a fair assumption to you, or do you think the exact source and exact config file should be specified in the sites array?

I think this is a fair assumption. Just specifying the path to the site's directory, which contains `config.php` and `source`, should be sufficient.

For `serve`, yeah, we would need to support specifying a specific site to serve. By default, it would presumably serve the first site in the `sites` array.

As for naming, I feel `sites` is better than `domains`; `domains` could be confusing, for instance, if multiple sites were being served as subdomains, for instance. I also wonder if `shared` is better than `namespaces`? Not sure about this, but `namespaces` sounds a little wrong in this context, even though it _does_ correspond to the package namespace syntax if you use `Namespace::folder.view`. Just something to ponder.

**Comment by adamkelso-rg** [comment]
Agree on all of those. I'll use "sites".

For namespaces, how about "Modules", since that's how they're referred in the Laravel documentation? Or... at least that's what they _were_ referred to as. Looks like they're no longer in the main documentation.

**Comment by adamkelso-rg** [comment]
PR submitted. #130

**Comment by damiani** [comment]
Let's move any future discussion of this to the PR https://github.com/tightenco/jigsaw/pull/130.
