### ISSUE TITLE
Collections getUrl incorrect when path in config has no prefix

### ISSUE THREAD

**Issue by garhbod** [tightenco/jigsaw#131]
Am wanting to make a dynamic menu and as there is no pages collection I've attempted to make an ad hoc solution by making a pages collection to iterate through

```
    'collections' => [
        'pages' => [
            'path' => '{permalink}',
            'sort' => 'order',
        ],
    ],
```

Everything works fine apart from the output or $page_item->getUrl() is prefixed with `//\/` so a page with pemalink set to `about` should output to `/about` but is actually output to `//\/about`

If I prefix the `path` in the config it works as expected `'path' => '!/{permalink}',` would produce `/!/about`

My suggestion would be to create a $pages collection by default but if that is not possible then can we find a solution to this issue?

**Comment by damiani** [comment]
There are several other instances of path trimming that would likely cause similar issues on Windows, so I've modified those as well, on the branch https://github.com/tightenco/jigsaw/tree/garhbod-patch-3 . Could you take a look and build with version `dev-garhbod-patch-3` to make sure it works correctly for you?

**Comment by garhbod** [comment]
Tried version `dev-garhbod-patch-3` @damiani but it doesn't have your changes or even my changes.

I downloaded a zip of https://github.com/tightenco/jigsaw/tree/garhbod-patch-3 and tested and everything works great
