### ISSUE TITLE
Some helper names are invalid; needs documentation

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/jigsaw#140]
There are a few helpers you can't set; we should document them and possibly find better errors.

So far I've run into it for `series` and `date`; if I try to put a helper on a collection, I get this error:

```
  [ErrorException]
  No function named "date" for the collection "posts" was found in the file "
  config.php". (View: /Users/mattstauffer/Sites/mattstauffer-co/source/blog.b
  lade.php)

  [Exception]
  No function named "date" for the collection "posts" was found in the file "
  config.php".
```

**Comment by damiani** [comment]
This is more likely a collision with an identically-named variable specified in a YAML header. Regardless, _that_ should be documented.
