### ISSUE TITLE
Registration and Trademark symbols in variables are rendered in final file name

### ISSUE THREAD

**Issue by standingdreams** [tightenco/jigsaw#145]
I recently upgraded Jigsaw to include the pull request #141. I needed a way to include an `.htaccess` for site redirects. I am using Blade/Markdown files to render pages from a parent template for products and accessories on a site. The name of the product is being used as the file name. 

Before upgrading trademark (™) and registration (®) symbols were being stripped out of the final file name. However, after upgrading it is now rendering ™ and ® as "tm" and "r", respectively. I was able to rectify the issue (of course after the client noticed the problem). I simply had to create another variable for the file name that did not include ™ or ® in it. 

I wanted to bring it up as an issue, just in case anyone else comes across this problem.

**Comment by dgursh** [comment]
Why are you using those symbols in the file name? If you're worried about copyright, there's really nothing you can do since it is a static website. You're best bet is to put copyright notice in the footer of your website and include a terms of service and privacy policy

**Comment by standingdreams** [comment]
@dgursh The goal was not to have those symbols as apart of the file name at all. I totally can see what I left off in this explaining this issue: the title variable was being used to define the path in the collection.

Example
`'path' => 'blog/{title}'   // 'blog/Title Of First Post'`

Previously the title could consist of trademark (™) and registration (®) symbols and they would be stripped from the path. However, after upgrading Jigsaw to include the pull request #141, the path began to render ™ and ® as "tm" and "r", respectively.

**Comment by dgursh** [comment]
Ok, so you are including trademark and registration symbols in the URL paths of your pages. Out of curiosity, why are you doing that? I don't think you can include html entities ™ and ® in a URL without first encoding it.

**Comment by standingdreams** [comment]
No, the trademark and registration symbols should not be apart of the URL paths at all. However, the `title` variable that was used in the templates had them in there. When creating a collection, you can use a variable from the a Markdown/Blade file as the path. I was using "Product 1®" to show as the title within the template but also using it for the path. 

Initially, this worked fine. It seems the master branch breaks that functionality.

**Comment by dgursh** [comment]
I understand what you are saying. But the path route defined in your config file is exactly that... the path (the URL). So, if you are using a title variable that includes those characters it will be included in the URL.

**Comment by standingdreams** [comment]
Previously, that wasn't the case. I had trademarks and registration symbols all in that title variable. It would only output the characters that were not symbols. However, after upgrading Jigsaw, that functionality was broken.

I simply want to bring attention to it just in case there was someone else utilizing it the same way i was. I had to create new variables that created slugs for the path.

**Comment by dgursh** [comment]
Ok, glad to hear you figured it out. I think this issue can be closed. As it is very specific use case. OK?

**Comment by damiani** [comment]
@standingdreams An easier way to restore the old slugs would be to use a function for your `path`; that way, you can strip out ™ and ®, or manipulate the title however you wish. For example:

```
'path' => function($page) {
    return 'blog/' . str_slug($page->title);
},
```

**Comment by damiani** [comment]
Thanks for pointing this out, and I'm going to take a closer look...it seems like the preferred behavior would be to strip out url-invalid characters like ™ and ® under all circumstances, even when not slugifying a title. I can't imagine a situation where we'd want to leave those in a path.

**Comment by standingdreams** [comment]
@damiani YES. That is exactly where I'm getting at. The solution you provided is a great fix. However, I can't imagine why any of those symbols should be rendered in the first place. On version 1.0, they were not rendered at ALL. I upgraded to 1.0.6 so that I can included .htaccess files in the build. After doing that upgrade, that's when this issue arose.

I just want to raise the concern for others.
