### ISSUE TITLE
New project errrors

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#146]
I'm getting some errors when trying to run my project using the following command

```
./vendor/bin/jigsaw build production
```

The first is a composer error it looks like
```
PHP Fatal error:  Interface 'Illuminate\View\Engines\EngineInterface' not found 
```

I was able to solve this my changing the path in MarkdownEnding.php to the following
```
use Illuminate\Contracts\Engines\EngineInterface;
```
I then had to run composer dump-autoload inside of Jigsaw src.

I then had another error...

```
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Container\Container' not found
```

I don't understand ... why are there so many issues with a fresh install?

**Comment by dgursh** [comment]
Ok, the change was as followed. I changed

```
use Illuminate\View\Engines\EngineInterface
```
to the following:
```
use Illuminate\Contracts\View\Engine as EngineInterface;
```

Now markdown files work. Should open a PR for this for the tightenco source.

**Comment by damiani** [comment]
This was caused by the recent update of some key Laravel dependencies to version 5.5. A new Jigsaw release has been tagged (v1.0.7) which fixed this issue, so if you run `composer update` from your project directory, you should be good to go.
