### ISSUE TITLE
Issues with Markdown and custom variables

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#147]
I've follow the docs exactly and reproduced the example in the docs here

```
http://jigsaw.tighten.co/docs/markdown/
```

It is saying for both variables that they are undefined

```
PHP Notice:  Undefined variable: title in test/_tmp/85f6768403c0a591c1cd70fbb697dfcb1d2eaf77.php on line 6
PHP Notice:  Undefined variable: author in test/_tmp/85f6768403c0a591c1cd70fbb697dfcb1d2eaf77.php on line 7
```

**Comment by dgursh** [comment]
Hey @adamwathan can you checkout this repo I just pushed up. I'm still getting errors saying that the variables are undefined. Not sure why. Thanks.

https://github.com/dgursh/test-jigsaw-app

**Comment by damiani** [comment]
There is an error on the `markdown` page of the documentation, which is a holdover from a previous version. `$title` and `$author` should now be referenced as `$page->title` and `$page->author`, as described here: http://jigsaw.tighten.co/docs/site-variables/

I'll update the docs on the markdown page to fix that.

**Comment by dgursh** [comment]
Thank you @damiani !!
