### ISSUE TITLE
Markdown files and sections broken

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#148]
Not sure who is maintaining this project, but it is riddled with bugs.

A markdown file that extends a layout and has a section is producing a bug where it is rendering off the page entirely. After closer examination the section is moved into the header tag of the page.

```
---
extends: _layouts.course
section: content
---

Here is some sample content...
```

This results in the section being placed above the head tag on the HTML. Bizarre.

**Comment by adamwathan** [comment]
Can you publish a repository that demonstrates this issue? I use this feature of Jigsaw on just about every static site I maintain and have never encountered this problem.

This page for example:

https://adamwathan.me/2014/04/12/theres-a-model-hiding-in-your-rest-api/

...is generated from this Markdown:

```
---
extends: _layouts.post
section: post
title: "There's a Model Hiding in Your REST API"
author: Adam Wathan
date: 2014-04-12
---

Last week I wrote a post for the Vehikl blog about using the constraints of REST to force you to think more critically about how you are modeling your system.

Check it out here:

[http://transmission.vehikl.com/theres-a-model-hiding-in-your-rest-api/](http://transmission.vehikl.com/theres-a-model-hiding-in-your-rest-api/)
```

...and everything renders in the right spot, not in the head like you are suggesting.

**Comment by adamwathan** [comment]
All of the markdown that powers the Jigsaw docs are also setup this way as you can see here:

https://github.com/tightenco/jigsaw-site/tree/master/source/docs

...and everything renders where it's supposed to, so there must be something else at play here.

If you can upload a project that reproduces this I'm happy to take a look.

**Comment by dgursh** [comment]
Thanks @adamwathan. Love the project. Will upload an example that duplicates the issue soon.

**Comment by dgursh** [comment]
@adamwathan the issue has been solved. It was an error on my end. Thanks.

**Comment by dgursh** [comment]
@adamwathan the issue has been solved. It was an error on my end. Thanks.

**Comment by dgursh** [comment]
Actually @adamwathan I thought I fixed it, but the error is still happening. Let me try and make another repo for you.

**Comment by damiani** [comment]
It's likely that your section name `content` doesn't match up with your parent template. Post a repo, and I'll be happy to take a look at your code and help you troubleshoot.
