### ISSUE TITLE
Advice on nested collection relationships?

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#149]
@damiani @adamwathan 

any advice on how to structure a config file for nested relationships on collections?

I'm trying to say a course "has-many" lessons, and a lesson "belongs to" a course.

```
return [
    'baseUrl' => '',
    'production' => false,
    'collections' => [ 
    	'courses' => [
    		'path' => '/coding/',
    		'lessons' => [
	    		'path' => '/coding/basics/',
	    	],
    	],

    	'lessons' => [
    		'path' => '/coding/basics',
    	],
    ],
];
```

**Comment by dgursh** [comment]
More specifically, how would you do nested URLS inside of collections?

/course/lesson

**Comment by sawirricardo** [comment]
Hi @dgursh how did you do it in the end?
