### ISSUE TITLE
Jigsaw 0.4.0 is not in Packagist 

### ISSUE THREAD

**Issue by lcdss** [tightenco/jigsaw#15]
[Jigsaw (Packagist)](https://packagist.org/packages/jigsaw/jigsaw)
To install it using composer I had to specify the commit:
`composer global require jigsaw/jigsaw:dev-master#7308f69c5d868911b111ccf1b1cfbc683d53af8b`

**Comment by adamwathan** [comment]
Fixed! Needed to update the repo on Packagist after moving it to the Tighten Co organization.

**Comment by lcdss** [comment]
Thanks!
