### ISSUE TITLE
How do you customize a collection's metadata?

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#150]
It says in the documentation that...

```
getPrevious() and getNext() give you the adjacent items in the collection, based on the collection's default sort order
```

How would I go about customizing these functions to work with my custom collection paths?

**Comment by damiani** [comment]
No customization is necessary; `getPrevious()` and `getNext()` will always return the previous and next collection items, and then `getPath()` will get the path to the adjacent item, formatted according to whatever you defined as the collection `path`. 

So, for example, `$page->getNext()->getPath()` will return the path to the next page. If you included a `baseUrl` in `config.php`, then `$page->getNext()->getUrl()` will return the fully qualified URL. Both will take your `path` setting into account automatically.

**Comment by dgursh** [comment]
Thank you @damiani. This project is really amazing. I want to help contribute in any way I can.

Out of curiosity, have you or @adamwathan used this Static Site Generator to create an enterprise-level application? I'm currently migrating over one of my big Laravel Spark applications to this for performance reasons.

**Comment by damiani** [comment]
I suppose it depends what you mean by "enterprise-level," but generally speaking, no; Jigsaw wouldn't be a good fit for an app that used to rely on Spark. You'd probably be better off sticking with Laravel, and focusing on optimizing performance...https://serversforhackers.com/laravel-perf is a great resource for that.
