### ISSUE TITLE
Help with rendering sidebar structure

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#151]
I'm having a tough time getting the correct variable to be displayed on the page on my sidebar navigation.

My sidebar navigation has the following structure:

```
Topic
   Course
   Lessons (for that course)
```

-a topic can have many courses
-a course can have many lessons

Here's an example
```
PHP <-- Topic
  The Basics <-- Course
  Home <-- Lesson
  Introduction <-- Lesson
  Install <-- Lesson
  Syntax <-- Lesson
  Adanced <-- Course
  Home <-- Lesson
  Introduction <-- Lesson
  lesson3 <-- Lesson
  lesson4 <-- Lesson
```
I'm rendering it on the screen using the following code that is a partial included on every page.

```
         <li><h1><a href="{{ '/'.$page->topic }}">{{ $page->topic }}</a></h1></li>
         @foreach ($courses->where('topic', $page->topic) as $course)
            <li><h2>{{ $course->title }}</h2></li>
            @foreach ($lessons->where('course', $page->course) as $lesson)
                <li><h3><a href="{{ $lesson->getUrl() }}"> {{ $lesson->title }}</a></h3></li>
            @endforeach
         @endforeach
```
The problems I'm running into are as follows
-Every course is displaying the same lessons, not specific to the course
-if I have duplicate course names, like The Basics for multiple topics it's rendering lessons for both.

I understand why it's doing this. The foreach loop is clearly incorrect in the logic, but if I remove it and just do something like this...
```
<li><h2><a href="what goes here???" class="{{ $page->active($course->getUrl()) }}"> {{ $course->title }}</a></h2></li>
```
I no longer have access the specific course variable anymore and I have to access it through the $page variable, which is no longer an object.

Any advice on how to structure this better? Also, should I be performing these where clauses in the views? Or is there a better place to put these?

Thanks so much.

**Comment by damiani** [comment]
The problem is likely in the second `@foreach` statement, `$page->course` is getting the reference to the current page that you are on, not the name of the course that you're looping over in `$course`; so that should probably be something like `$course->title` instead.

So assuming your `course` files are set up like:

```md
---
topic: PHP
title: The Basics
extends: _layouts.course
section: content
---

This is the "The Basics" course
(PHP > The Basics)
```

and your `lesson` files are set up like:

```md
---
topic: PHP
course: The Basics
title: Home
extends: _layouts.lesson
section: content
---

This is the "Home" lesson
(PHP > The Basics > Home)
```

...then this would give you what you're looking for, and will solve both issues you mention:

```blade
<li>
    <h1><a href="{{ '/' . $page->topic }}">{{ $page->topic }}</a></h1>
</li>

@foreach ($courses->where('topic', $page->topic) as $course)
    <li>
        <h2>{{ $course->title }}</h2>
    </li>

    @foreach ($lessons->where('course', $course->title) as $lesson)
        <li>
            <h3><a href="{{ $lesson->getUrl() }}"> {{ $lesson->title }}</a></h3>
        </li>
    @endforeach

@endforeach
```

For lessons like "Introduction" that have duplicate titles, you'll just need to give them unique filenames, so I'd just prepend the course title to the filename to prevent collisions:

```
_courses
    advanced.md
    the_basics.md
    ...

_lessons
    advanced_introduction.md
    advanced_lesson_1.md
    the_basics_home.md
    the_basics_introduction.md
    ...
```

**Comment by dgursh** [comment]
Ok @damiani this all makes sense. Let me make sure I understand this...

-a "course" markdown file needs to have the topic repeated
-a "lesson" markdown file needs to have the course and topic repeated

Maybe in a future release their can be a place to store repeated variables across relationships of markdown files. Thoughts?

And you are exactly correct. I realized that the file names all need to be unique. I can have two lessons named "intro" in two different courses, but need to be named differently. Maybe something to improve in future versions as well?

Thanks for your great explanation.
