### ISSUE TITLE
[Proposal] Factories for markdown files

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#153]
I see a need for creating factories for markdown files similar to how Laravel creates model factories for testing. Does this feature already exist? If not, what are everyone's thoughts around making it?

Thanks.

**Comment by damiani** [comment]
We've talked about this a little bit, something along the lines of a command like `jigsaw make post --title="My New Post"`, but we'd need a clean way to define a template for new files, accepting parameters (like `--title` from the command), etc. Definitely open to the idea, though.

**Comment by wilburpowery** [comment]
What parameters do you guys have in mind? I've been trying to work on something like this. I really hate to go and create the file manually and add all the template stuff. I really like the idea of just running a `make:post` command. @damiani 

<img width="1037" alt="screen shot 2017-10-06 at 5 56 32 pm" src="https://user-images.githubusercontent.com/15817188/31302544-c45f8594-aabf-11e7-8191-b43cb5d8208a.png">

**Comment by damiani** [comment]
This is being addressed in https://github.com/tightenco/jigsaw/pull/164, any further discussion can take place on that PR.
