### ISSUE TITLE
[Help] Trouble with multi-variable collection sorting

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#154]
I have the following variables in my YAML files for Lessons.

```
Lessons.md
---
subject: "php"
course: "basics"
courseName: "php-basics"
title: "PHP Intro"
description: "this is a description..."
orderNumber: 1
---
```
My goal is to sort the lessons first by "courseName" and then by the "orderNumber". That way I can progress through all of the lessons of the course in order.

In my config I have the following for the sorting of lessons collection
```
'lessons' => [
            'sort' => ['orderNumber',  'courseName']
]
```

The result is that it appears to be taking into account orderNumber and not the courseName. The following two lessons appear next to each other even though I'm also sorting based on courseName.

```
php-intro.md
---
subject: "php"
course: "basics"
courseName: "php-basics"
title: "PHP Intro"
description: "this is a description..."
orderNumber: 1
---

CSS-intro.md
---
subject: "css"
course: "basics"
courseName: "css-basics"
title: "CSS Intro"
description: "this is a description..."
orderNumber: 1
---
```

I even tried reversing the order, like so. But that gives an even crazier order that is not correct.
```
'lessons' => [
            'sort' => ['courseName',  'orderNumber']
]
```

Any advice on how to fix / debug?

**Comment by damiani** [comment]
It should work the first way you have it, with `'sort' => ['orderNumber',  'courseName']`, but it seems to be failing when there are multiple `orderNumbers`. I'll take a closer look and work on a fix.

**Comment by dgursh** [comment]
Thank you. I recreated all of the lesson markdown files and it was working great 
```
'sort' => ['courseName',  'orderNumber']
```
but only when I had duplicates of a single orderNumber (5 lessons with orderNumber of 1). But once, I started adding more lessons with duplicate orderNumber's of 2, the order fell apart.

**Comment by dgursh** [comment]
Ok, thank you. Let me know when you've figured out a fix. Would you like me to upload a sample repo project with the code for you to look at? @damiani

**Comment by dgursh** [comment]
Hi @damiani  I set up a sample repo that tests this layout

https://github.com/dgursh/bug

You'll notice when you navigate to the home page the the lesson links are out of order, despite the sorting variables that I use. Let me know your thoughts.

**Comment by dgursh** [comment]
@damiani where in the src code is the custom sorting functions? I can take a look at it as well.
