### ISSUE TITLE
[Question] intended behavior or bug of some sort? Not including section variable.

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#159]
Something that I noticed after playing around with jigsaw for a few weeks. Not sure if this is intended behavior/correct functionality, but I thought I would bring to everyone's attention.

I noticed that if my markdown files don't have the "section:" variable in the YAML section, they do not render at all on the screen. This is even the case if I have a markdown file has no content, just variables.

```
---
extends: _layouts.course
section: subcontent
topic: "coding"
title: "PHP Basics"
image: pic.png
description: "..."
---
```

If i remove "section: subcontent", the file does not render at all. Even though I'm rendering it in the view like this. 

```
@extends('_layouts.master')

@section('content')
  <h3>{{ $page->title }}</h3>
@endsection
```

I'm clearly not using the section called "subcontent". I'm using the section called "content". If I replace the variable with the following it works.

```
section: foo
```
It seems I need to have a section variable even if it doesn't match the section name. Weird, right?

**Comment by damiani** [comment]
If you don't specify a `section`, or that `section` doesn't have a corresponding `yield()` directive in the parent template that you're `extend`ing, then there's nowhere for the markdown file to render to. So it won't render anywhere, although variables from the markdown file (like `title`) will still be available in your parent template. This is standard Blade behavior.

Your second code snippet, assuming that's `_layouts/course.blade.php`, won't render anything from your markdown file unless it had a `@yield('subcontent')` inside the `content` section, and the template `_layouts.master` had a `@yield('content')` somewhere.

> If I replace the variable with the following it works.

What do you mean by "it works"? If your markdown file has `section: foo`, it's still not going to render anywhere unless your parent template has `@yield('foo')`.

**Comment by dgursh** [comment]
So, I actually can't access the $page variables at all unless I have a section specified, even if that section doesn't exist.

**Comment by damiani** [comment]
Can you show me some more complete code, please? In my testing, page variables are accessible, regardless of whether `section` is specified.

**Comment by dgursh** [comment]
Ok I will try and make a test repo for you when I can. @damiani
