### ISSUE TITLE
Filenames starting with a dot are ignored

### ISSUE THREAD

**Issue by wyandotte** [tightenco/jigsaw#16]
When running `jigsaw build`, files starting with a dot are ignored. Initially encountered this with a .htaccess file, but any file with a name starting with a dot is not copied to `build_local`. This doesn't seem to be intended behaviour, as only files starting with an underscore should be ignored.

**Comment by adamwathan** [comment]
Thanks, good catch! Fixed and tagged as v0.4.1 :)

**Comment by wyandotte** [comment]
Wow, that was fast. Recently discovered Jigsaw and already using it for a project, it's great!

**Comment by adamwathan** [comment]
Awesome, glad to hear it!
