### ISSUE TITLE
Is there a way to handle versioning/cache busting?

### ISSUE THREAD

**Issue by nathangross** [tightenco/jigsaw#166]
Is there any supported/preferred way to handle versioning of generated css and js files?

**Comment by damiani** [comment]
Jigsaw is set up to use Laravel Elixir to compile your assets; take a look at [the docs on **Compiling Assets**](http://jigsaw.tighten.co/docs/compiling-assets/) if you're not familiar with that.

To version CSS or JS files, you can add a `version` line to your `gulpfile.js`, after your assets are compiled. So, for instance, to version a CSS file that has been generated from SASS, your gulpfile would include:

```js
mix.sass('main.scss')
   .version('css/main.css')
   .exec(bin.path() + ' build ' + env, ['./source/*', './source/**/*', '!./source/_assets/**/*'])
});
```

This will create a `build/css` directory, which will contain a versioned copy of your compiled `main.css` file. Then, use the `elixir` Blade directive in your parent template to reference the versioned file:

```html
<link rel="stylesheet" href="{{ elixir('css/main.css', 'build') }}">
```

Note that you need to specify the `build` directory as the 2nd parameter in the `elixir` directive.

You can do the same with other CSS or JS files, by specifying an array for `.version` in your gulpfile:

```js
    .version(['css/main.css', 'js/main.js'])
```

**Comment by nathangross** [comment]
Awesome, thanks @damiani. I tried to get the version function to work (I use it in my laravel projects), but was missing the second param in the elixir directive master layout file. 

This works perfectly.
