### ISSUE TITLE
Trailing slash on URLs

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#170]
I just deployed a site to Amazon S3, however I noticed that all of the URLs end with a trailing slash like so:

```
example.com/dir/
```

On my local machine it does not have a trailing slash

```
example.com/dir
```

Why is it doing this? Is there anyway to fix this behavior? I believe Amazon S3 is treating the jigsaw folders like directories and then just assuming index.html is the file. Need to fix for SEO. Any suggestions? Thanks.

**Comment by dgursh** [comment]
I guess I can just turn --pretty=false

But then I'm stuck with .html

**Comment by damiani** [comment]
This is S3's behavior; it hits `example.com/dir` and if no object exists there (it doesn't), it tries `example.com/dir/index.html`. In a Jigsaw site, that object _does_ exist, and that's what it serves, using the URL `example.com/dir/`.

It should have no SEO effect, however. According to [Google](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html), at least:

> `http://example.com/foo/ (with trailing slash, conventionally a directory)`
`http://example.com/foo (without trailing slash, conventionally a file)`
Google treats each URL above separately (and equally) regardless of whether it’s a file or a directory, or it contains a trailing slash or it doesn’t contain a trailing slash.

**Comment by GitHub-Mike** [comment]
Here is a (late) solution to the problem for apache users. Add the following lines to the .htaccess:

```apache
DirectorySlash Off

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_URI} !/$
RewriteCond %{REQUEST_FILENAME}/index.html -f
RewriteRule (.*) $1/index.html [L]
```

**Comment by chrisvidal** [comment]
digging up this thread 

the following snipper is not working for my apache 2. 
Google search console is giving lots of `page with redirect` issue because of this trailing slash.

any idea how to fix this?

```
DirectorySlash Off

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_URI} !/$
RewriteCond %{REQUEST_FILENAME}/index.html -f
RewriteRule (.*) $1/index.html [L]
```

**Comment by GitHub-Mike** [comment]
> the following snipper is not working for my apache 2. Google search console is giving lots of `page with redirect` issue because of this trailing slash.

Does the snippet really not work?

The messages in the GSC can also have other reasons.

**Comment by GitHub-Mike** [comment]
> when I type in the url domain.com/page/subpage it returns back to domain.com/page/subpage/

I have just tested this, but cannot confirm the behaviour.

"DirectorySlash Off" also applies to subdirectories. Unless there are special instructions for this subdirectory from this or another .htaccess file.

What happens if you place an .htaccess file with the content:

```DirectorySlash Off```

in this subdirectory?

**Comment by chrisvidal** [comment]
Now it's working, I haven't change anything.

I think I found the reason because of the structured directories and files, I had this:

'/programs/martial-arts/index.blade.php`
'/programs/martial-arts/martial-arts-for-kids.blade.php`
'/programs/martial-arts/martial-arts-for-adults.blade.php`

then I changed to 

'/programs/martial-arts.blade.php` <=
'/programs/martial-arts/martial-arts-for-kids.blade.php`
'/programs/martial-arts/martial-arts-for-adults.blade.php`

and it works fine now for the intermediary folders

thanks
