### ISSUE TITLE
how do i update jigsaw?

### ISSUE THREAD

**Issue by w1n78** [tightenco/jigsaw#171]
i installed jigsaw using http://jigsaw.tighten.co/docs/installation/

my project is currently running 1.0.5. it looks like the latest version is 1.0.9. i tried jigsaw update but that command is not defined.

do i have to start a new project in order to use the latest version? thanks.

**Comment by mattstauffer** [comment]
@w1n78 Jigsaw is a Composer dependency, so you can update the copy of Jigsaw used in your project with Composer:

```bash
composer update tightenco/jigsaw
```

If you installed it globally, it's similar:

```bash
composer global update tightenco/jigsaw
```

**Comment by w1n78** [comment]
@mattstauffer thank you sir
