### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#173]
Forgive me if this is the wrong venue for this line of questioning....

What is the status of this project?  Activity seems to have dried up recently.  Was a decision made to focus elsewhere?  Is it "done" or are the primary devs simply taking a hiatus?  

Also, is there another jigsaw "community" somewhere for Q/A, discussion, etc?

I'm trying to set expectations going forward, so any insight would be welcome.

**Comment by damiani** [comment]
@cjf Development is still active, but has been held up recently by other work...yours is a good reminder, though, that we have open issues to deal with, which I aim to continue tackling this week.

As for discussion, GitHub issues are the best place at the moment for questions, feature requests, and discussion.

**Comment by mattstauffer** [comment]
@cjf Just a side note: Since this is an open source project, we welcome contributions from the community. If this is a project you're interested in connecting with, we'd love for you to consider contributing to help the project keep moving forward! Please feel free to let us know if you're interested in helping out.

**Comment by cjf** [comment]
@damiani To be clear, I'm grateful for the work and completely understand other things coming up.  I was really just worried that it has been moved on from, and that I missed the memo!

@mattstauffer I've tinkered with some of the open issues but haven't gotten far enough, yet, to take the next step.  It seems we all get held up by other work!

Thank you both for the updates, and the work on jigsaw!
