### ISSUE TITLE
I am thinking of adding functionality to add a sitemap.xml on production builds?

### ISSUE THREAD

**Issue by johnmackenzie91** [tightenco/jigsaw#175]
What do you think of that proposal?

If so, could someone be so kind as to point me in the right direction to where the page generation happens?

Regards.

**Comment by damiani** [comment]
Pages are generated in the `buildSite` method of `SiteBuilder`. The last step of the collection pipeline in that method, `buildFile`, is where the actual output files are generated.

This might actually be a good use case for the feature described in https://github.com/tightenco/jigsaw/pull/136#issuecomment-338524912, i.e. if we exposed the ability to run user-generated code after the build has been completed, then you could easily add a sitemap generation function that traverses `build_production` after Jigsaw is done processing.

**Comment by damiani** [comment]
Let's move any further discussion of this feature to the PR https://github.com/tightenco/jigsaw/pull/136. Building a `sitemap.xml` would be a great example for running user-defined code after a build is complete.
