### ISSUE TITLE
Copying to build folder not working via Gulp

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#176]
I try to copy Netlify redirects to my build via Gulp. I just added it to the `exec` command. When I change the destination of `copy`, it perfectly works. But not for my `build_local` folder. It shows up in the `gulp` log but never makes it to the folder. I tried it with relative and absolute paths, with no effect. It works on the build_production folder

What could I be doing wrong?

```
    mix.sass('main.scss')
        .exec(bin.path() + ' build ' + env, ['./source/*', './source/**/*', '!./source/_assets/**/*'])
        .copy('_redirects.txt', './build_local/_redirects.txt');
```

**Comment by damiani** [comment]
Assuming that `_redirects.txt` is at the top level of your directory (at the same level as your `gulpfile`), then this should work, and it works in my testing—`_redirects.txt` gets copied to `build_local` just fine. If you can post a repo of your project, I can take a look and see if there's something else going on.

**Comment by minthemiddle** [comment]
Thanks for the off, @damiani, will post the repo as soon as I published the website today (due to partnership agreements it is not yet).

**Comment by minthemiddle** [comment]
@damiani Here's the repo: https://github.com/CodeDesignInitiative/cdweb1801 - copying `_redirects.txt` to `build_local` or `build_production` does not work, unfortunately.

**Comment by damiani** [comment]
Very odd...I just pulled down your repo and tested it, and it copies `_redirects.txt` just fine, either to `build_local` or `build_production` (depending on what's set in the gulpfile):

![screen shot 2018-01-12 at 5 35 35 pm](https://user-images.githubusercontent.com/357312/34898056-12c38130-f7bf-11e7-8432-25b2b372c89d.png)

Just to confirm: you're running `gulp`, right, and not just `./vendor/bin/jigsaw build`?

**Comment by minthemiddle** [comment]
Oh, order matters when pushing to production, it seems. When I swap `gulp` and `jigsaw` it works, so `$  jigsaw build production && gulp --production`, the `redirect` gets pushed. I guess that `jigsaw` overwrites the folder somehow.

**Comment by damiani** [comment]
Yes, Jigsaw's `build` command rebuilds the `build_{env}` folder each time. And Jigsaw's stock configuration of `gulpfile.js` runs `jigsaw build`, so there's no need to run both—just run `gulp --production` and you should be all set.
