### ISSUE TITLE
Date renders as int instead of date

### ISSUE THREAD

**Issue by GeorgThomassen** [tightenco/jigsaw#178]
Hello,

I'm setting up a default jigsaw installation according to the docs however the date renders as an int.

With a collection of `posts` set up as the docs describes and the following post.blade.md in a _posts folder with a date variable in the front matter
```
---
extends: _layouts.master
title: My First Blog Post
author: John Doe
description: An awesome description of the post
date: 2017-03-23
section: body
---

Some awesome content
```

In the master layout:
```
<p>By {{ $post->author }} · {{ $post->date }}</p>
```

the date renders as `1490227200` even though the path setting in the config `'path' => 'blog/{date|Y}/{date|m}/{date|d}/{-title}',` works just fine.

If I surround the date variable in the front matter with single quotes it does renders correctly and the path still works fine. Is it just a typo in the docs or am I not supposed to use single quotes in the front matter?

**Comment by damiani** [comment]
If I remember correctly, the YAML processor turns dates that it finds in frontmatter into integer timestamps, so outputting a date in your template should use PHP's `date()` function and specify a format. For example:

```php
<p>{{ date('F j, Y', $post->date) }}</p>
```

I'll update the docs to reflect that, thanks for pointing it out!

**Comment by GeorgThomassen** [comment]
That makes sense! Thank you
