### ISSUE TITLE
$page->getPath() returns nothing

### ISSUE THREAD

**Issue by mariordev** [tightenco/jigsaw#181]
I'm using Jigsaw version 1.0.10. When I call $page->getPath() I get nothing in return. The other methods documented here http://jigsaw.tighten.co/docs/page-metadata/ are returning the correct value. Am I missing something?

Thanks!

**Comment by damiani** [comment]
Can you include a link to your repo, or at least, the code for the page where it's not working?

**Comment by damiani** [comment]
Closing for now, let me know if you're still experiencing this issue and I'll reopen it.
