### ISSUE TITLE
Why run 'jigsaw build' if running 'gulp'?

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#183]
I may just be having a brain cramp, but is there a reason the docs say to run both 'gulp' and 'jigsaw build' when it comes time to deploy?

My understanding is that the gulpfile calls 'jigsaw build' anyway.  What does the extra build accomplish?

http://jigsaw.tighten.co/docs/deploying-your-site/

**Comment by damiani** [comment]
Your brain's just fine, that line in the docs is outdated. Originally, the default `gulpfile` only ran `jigsaw build` and wasn't environment-aware. I've updated the docs...thanks for pointing this out!
