### ISSUE TITLE
Blogpost: Use continuous deployment with Jigsaw on Netlify

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#184]
I just published a blogpost about how to use continuous deployment with Jigsaw on Netlify:

https://medium.com/@martin_betz/just-commit-to-git-build-static-pages-continuously-using-php-generators-like-jigsaw-on-netlify-4a3a18327ffa

**Comment by minthemiddle** [comment]
Not an issue, just a note.

**Comment by damiani** [comment]
Thanks @minthemiddle !
