### ISSUE TITLE
How to output Markdown content as raw HTML?

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#185]
I have problems outputting the content of a collection's Markdown as pure HTML.
When I use `{{ $collection->getContent() }}` I get `"<p>My content</p>"` which literally outputs the HTML tags. When I use the `blade` `raw` directive: `{!! $collection->getContent() !!}`, I get the right result, but it this the best practice?

I use the content block in a partial and cannot use the `@yield()` command in that scenario I guess.

**Comment by damiani** [comment]
The typical setup would be to extend a parent template from each of your collection items, and render the content using `@yield()`; if you're doing something else that requires you to access `$collection` directly, then yes, `{!! $collection->getContent() !!}` would be the best way to output the processed Markdown content.

If you have a repo of your project I can take a look at, I can give you more specific advice...there may be a better way to structure your collection files.

**Comment by minthemiddle** [comment]
Thanks for the feedback. We are using markdowns in a collection to add updates to youth camps that we run. This is the repo: https://github.com/CodeDesignInitiative/cdweb1801

Each camp is an own [markdown](https://github.com/CodeDesignInitiative/cdweb1801/blob/master/source/_camps/1802-ber.md) from the `camp` collection which extends an [layout](https://github.com/CodeDesignInitiative/cdweb1801/blob/master/source/_layouts/camps.blade.php). In this layout, we include an [update](https://github.com/CodeDesignInitiative/cdweb1801/blob/master/source/_layouts/camps.blade.php#L82).

The `update` pulls an entry from the `update` collection and compares the camp ids (e.g. `ber1802`) and shows the corresponding `update`.

I guess that in this setting, I cannot extend on an layout and need to to refer to `{!! $collection->getContent() !!}`.

**Comment by damiani** [comment]
Yes, if you're referencing an item directly, like you are with each `update`, you need to access its content using `getContent`. 

But I've just added support for the ability to drop the `->getContent()` part in a Blade view, in [this PR](https://github.com/tightenco/jigsaw/pull/186). Once that's merged, you'll be able to simply call `{!! $update !!}` in your Blade template.
