### ISSUE TITLE
Is there any way to get current route / page name?

### ISSUE THREAD

**Issue by ashokvishwakarma** [tightenco/jigsaw#19]
I am building a static website with some layouts and elements (header / footer) which includes and navigation as well. I wanted to add a active class in my header.blade.php based on page name.

What I have got from searching over internet.
JavaScript solution, check the URL using `location.pathname` and add the class `active` to the navigation links.

But if there is anything in Jigsaw to add the same while its getting compiled would be great, please let me know if this can be possible.

**Comment by adamwathan** [comment]
Not at the moment but this is a good idea, I will try and get this in really soon.

**Comment by akvlko** [comment]
Thanks @adamwathan that would be a great help to use the Jigsaw as full fledged static site builder.
Looking forward to get this done soon.

**Comment by nerdmediallc** [comment]
Until this feature is added in a more graceful way you could use the hacky solution below.

Base Template Example
```
{{--*/ $activeNav = 'nav-2' /*--}}

@section('body')
	@include('_common.navigation')
	<h1>Hello World</h1>
@endsection
```

Included Navigation Template Example

```
<ul>
	<li{!! $activeNav == 'nav-1' ? ' class="active"' : '' !!}>Nav 1</li>
	<li{!! $activeNav == 'nav-2' ? ' class="active"' : '' !!}>Nav 2</li>
	<li{!! $activeNav == 'nav-3' ? ' class="active"' : '' !!}>Nav 3</li>
</ul>
```

**Comment by jevets** [comment]
[Harp](http://harpjs.com/) does a nice job of this, making a `current` [variable](http://harpjs.com/docs/development/current) available to all views.

For page `/about/team`, generated from file `about/team.md`, for example:

```js
current.source
// (string) 'team'

current.path
// (array) ['about', 'team']
```

This is usually enough to determine the current active page and even its active parent page/section.

I'm going to take a stab at a larger site with Jigsaw over the next couple weeks, so I'll post back if I find a nice way of adding this behavior, too.

Also for nav item classes, I usually clean up the ternary operator like so (think I saw Taylor Otwell do this somewhere). It's just cleaner to me:

```php
<li class="{{ $activeNav != 'nav-1' ?: 'active' }}">...</li>
```

**Comment by damiani** [comment]
As of v1.0.0, you can now access `$page->getFilename()` or `$page->getPath()`, which you could check via a [helper method](http://jigsaw.tighten.co/docs/helper-methods/) in `config.php`.  

You could also add a variable in the YAML front matter for a page, something like:

```
---
section: about
---
```

...and check the value of `$page->section` instead of using the filename or path.
