### ISSUE TITLE
path of images in markdown does not recognize pretty URLs

### ISSUE THREAD

**Issue by dirkolbrich** [tightenco/jigsaw#192]
The markdown parser does not parse the correct path for image files of linked images in .md files, if the same content is shown on a paginated index site (path is correct) and a single post site under a pretty URL path (path of image is incorrect) .

Here is the source structure, pretty basic:

```
source
- _posts
    - some-post.md
- img
    - image.jpg
- index.blade.php
```

The config.php file defines a collection of post and puts them into a pretty subfolder path. The main index file under `/` shows the paginated content. The single post is shown under a `/blog/2018/some-post` path.

```php
// config.php
return [
    'baseUrl' => '',
    'production' => false,
    'collections' => [
        'posts' => [
            'path' => '/blog/{date|Y}/{-title}',
            'sort' => '-date',
        ],
    ],
    // …
];

```

The output:
```
build
- index.html // paginated content page 1 - the start page - // link to image points to '/img/image.jpg', which is ok 
- 2
    - index.html // paginated content page 2
- blog
    - 2018
        - some-post
            - index.html // link to image points to '/blog/2018/img/image.jpg', which does not exist
- img
    - image.jpg
```

```md
section: content
title: some post
date: 2018-03-09
—
Some text in this post.

![this is an image]('../img/image.jpg‘)

```

Is there a way to make the link to the image always point to the image folder under root?

So if I link the image within the .md file with `![image]('/img/image.jpg‘)`, it always points to `{baseURL}/img/image.jpg`, if I define a base URL.

**Comment by damiani** [comment]
You can refer to the image in your Markdown file as `![image](/img/image.jpg)` and it should pull it from the root folder.

**Comment by dirkolbrich** [comment]
Ahhhh .... the obvious. Thank you.

**Comment by balintawak-eskrima** [comment]
In addition for said, you can change urls through extending of michelf/php-markdown
In file *jigsaw/src/Parsers/JigsawMarkdownParser.php*
```php
<?php

namespace TightenCo\Jigsaw\Parsers;

use Michelf\MarkdownExtra;

class JigsawMarkdownParser extends MarkdownExtra
{
    public function __construct()
    {
        parent::__construct();
        $this->code_class_prefix = 'language-';
        $this->url_filter_func = function ($url) {
            return str_replace("{{'@'}}", '@', $url);
        };
    }

    public function text($text)
    {
        return $this->transform($text);
    }

    public function parse($text)
    {
        return $this->text($text);
    }
}
```
you can put your custom logic in *url_filter_func* closure, problem consist in that will taking all urls, in this case you can use native php function getimagesize for filtering url-images.
