### ISSUE TITLE
[Question] How can you get the config.php array in JS

### ISSUE THREAD

**Issue by hellocosmin** [tightenco/jigsaw#193]
As the title says, is it possible to get the final config array (after Jigsaw merges env-specific configs) in JS, in order to use a key inside a script?

**Comment by damiani** [comment]
Yes, you can access it by echoing the `$page` variable in you master Blade template, something like this:

```php
<script type="text/javascript">
    var jigsaw = @json($page)
</script>
```

That'll populate the JS `jigsaw` variable with the parsed contents of `config.php`, including collection details and environment-specific config items.

**Comment by hellocosmin** [comment]
Thanks for answering my silly question, @damiani. Yes, of course we can do it like that in a Blade template - apologies for not being clear.

What I meant was how could one get the config in the Webpack/Gulp script.

So for example, say I needed to use a config key in `webpack.mix.js`, presumably in the `AfterBuild` plugin after Jigsaw compiles Blade and outputs them. 

I've tried something and it does work, but I feel it's a bit hacky and I would appreciate any input here. 

In my use case, I want to be able to specify whether pretty permalinks should be used, directly in the config. It may not be the best example, but you can imagine it could be anything:

1. `config.production.php` :

    ```php
    <?php

    return [
        'baseUrl' => 'site.example.com',
        'production' => true,
        'prettyUrls' => true,
        'collections' => [],
    ];
    ```

2. I have a `tasks/php/config` script where I get the (merged) configuration, based on the environment:

    ```php
    #!/usr/bin/env php
    <?php

    /*
    |--------------------------------------------------------------------------
    | Get Site Config
    |--------------------------------------------------------------------------
    |
    | Get the environment-specific site configuration and output it as JSON.
    | This JSON is then used in webpack.mix.js, to trigger scripts based
    | on your config files, respecting the build environment.
    |
    */

    $env = getopt('e:');
    $config_dev = require_once('config.php');

    if($env) {

        $file = 'config.' . $env['e'] . '.php';

        if(file_exists($file)) {

            $config_env = require_once($file);
            $out = array_merge($config_dev, $config_env);

            print json_encode($out);
            exit();

        }

    }

    print json_encode($config_dev);

    exit();
    ```

3. In the `AfterBuild` Webpack plugin, I run that task with `command.get()`, passing the command to `jigsaw build` as a callback:

    ```javascript
    new AfterBuild(() => {

            command.get('php tasks/php/config -e' + env, (error, stdout, stderr) => {
                if (error) {
                    console.log(stderr)
                    process.exit(1)
                }

                config = JSON.parse(stdout)

                const prettyUrls = (config && !config.prettyUrls) ? '--pretty=false ' : ''

                command.get(jigsaw.path() + ' build ' + prettyUrls + env, (error, stdout, stderr) => {
                    console.log(error ? stderr : stdout)

                    if (browserSyncInstance) {
                        browserSyncInstance.reload()
                    }
                });
            });

        })
    ```

This does work, but I don't know if it's a good approach. 

Again, I would be grateful for your input. And thank you so much for the wonderful work on Jigsaw - love it!

**Comment by damiani** [comment]
Ah, I see. In general, there's no easy way to access any of the data that gets built when the PHP side of Jigsaw runs (like the merged `config`) in the JS `AfterBuild()` step, since the PHP hasn't run yet. There is the ability to monkey with things in `bootstrap.php`, or, shortly, in the `beforeBuild` event, but that wouldn't help for your specific use case either, since there's no way to change the `outputPathResolver` before the `Jigsaw` class is instantiated.

So, your solution is as good as any :) 

If there seems to be a common need to change the `prettyUrl` setting based on something other than the `--pretty` flag in the console command, we can consider adding another event hook and/or a setter method in `SiteBuilder.php` to allow you to change the `outputPathResolver` in `bootstrap.php`.

**Comment by hellocosmin** [comment]
Found another use case :)

As I'm using collections to build individual sites, I realized I could use per-collection control over pretty URLs, so that some sites use pretty URLs, while other's don't.

Ideally, maybe a key on the collection?

```php
'collections' => [
    'site-1' => [
        'prettyUrls' => true, // if missing, default to true or let --pretty flag handle it?
    ],
    'site-2' => [
        'prettyUrls' => false,
    ],
],
```

For regular, non-collection folders, maybe let `--pretty` handle them, or perhaps check for a `prettyUrl: true` in Front Matter?

What do you think?
