### ISSUE TITLE
Custom Blade directives?

### ISSUE THREAD

**Issue by hellocosmin** [tightenco/jigsaw#196]
Hey guys,

Was checking out `jigsaw-core.php` and saw this on line 102:

`(new BladeDirectivesFile($c['cwd'] . '/blade.php'))->register($bladeCompiler);`

I see BladeDirectivesFile will register directives from a given file. Am I right in assuming one can add a `blade.php` file where custom directives can be registered?

If so, where would you add this? And how would custom directives be registered in it? Tried adding it to `/source` and root of project, but it doesn't work with `Blade::directive()`. Appreciate any insight/pointers.

**Comment by damiani** [comment]
You would add the `blade.php` file to the root of the project (same level as `config.php`), and return an array of directives to register. Each directive receives two parameters:

- `$expression`, which is specified when you call the directive, e.g. `@mydirective('expression')`
- `$page`, which is the usual `$page` variable for whichever page the directive is called on.

So, for example:

```php
<?php

return [
    'datetime' => function($expression, $page) {
        return '<?php echo date("Y-m-d H:i:s", ' . $expression . '); ?>';
    },
];
```

The feature came from [this request](https://github.com/tightenco/jigsaw/pull/67#issuecomment-296311562) but hasn't been documented. I'll make a note to add it to the docs on the next update.
