### ISSUE TITLE
Empty evaluates as true

### ISSUE THREAD

**Issue by andrew-s** [tightenco/jigsaw#199]
I just wanted to confirm if this is known/a bug/or the way i'm utilising the templates.

An example structure;

```
_layouts
  - blog.blade.php (extends into master.blade.php)
  - master.blade.php 
_posts (collection)
  - first-post.md
```

And your first-post.md looks like;

```
---
title: My Article
date: 2017-05-20T00:01:59+00:00
extends: _layouts.blog
---
# My Article
```

Everything compiles and it utilises blog.blade as expected, and the following works;

```
{{ $page->title }}
```

However, if you do;

```
@if(!empty($page->title))
 Title: {{ $page->title }}
@endif
```

It'll always evaluate as false (or as, empty is always true). Not sure where this bug exists really or if this is intended? Workout would be to just use `strlen()` which seems to work as intended.

Any guidance appreciated. Thanks!

**Comment by damiani** [comment]
Variables on `$page` are actually accessed with a getter, so the property doesn't technically exist on the `$page` object, and thus evaluates as empty. But you should get the results you're expecting by just checking for the existence of `$page->title`, without the need for `empty` or `strlen`:

```php
@if ($page->title)
    ...
@endif
```
