### ISSUE TITLE
PHP Notice when using getCollections() in afterCollections event

### ISSUE THREAD

**Issue by hellocosmin** [tightenco/jigsaw#202]
First, thanks so much for the event bus, it's extremely useful :)

So I've been playing around with events in 1.1.1, and either I've come across an issue, or I'm doing something I'm not supposed to. I want to `getCollections()` in the `afterCollections` event, so that I can loop through them and do some stuff with each collection's items before the build starts.

Issues:

1. When ran inside the `afterCollections` event, `getCollections()` no longer returns the array with collection names, instead it returns an array of all collections (like you would do with `getCollection($name)`. 

    Although it was confusing at first, this is actually great, as I don't need to loop over each key and do a `getCollection($name)`. However: 

2. I get this PHP notice:

```php
Notice: Trying to get property of non-object in [project root]\vendor\tightenco\jigsaw\src\SiteBuilder.php on line 71
```

Which comes from this in the `SiteBuilder` class:

`$meta = $this->getMetaData($file, $siteData->page->baseUrl);`

My `baseUrl` is the default (empty string) and I run `npm run dev`.

This is what I have in `bootstrap.php` - `var_dump` in there for quick debugging, it throws the same notice without it:

```php
<?php

/** @var $container \Illuminate\Container\Container */
/** @var $events \TightenCo\Jigsaw\Events\EventBus */
/** @var $jigsaw \TightenCo\Jigsaw\Jigsaw */

$events->afterCollections(function ($jigsaw) {
    $collections = $jigsaw->getCollections();

    var_dump($collections);
});
```

Am I doing something wrong? Thanks!

**Comment by hellocosmin** [comment]
To add to the above, getting collections in the `afterCollections` event also has issues with helper functions.

For example, I have a helper defined in `config.php` that builds a relative asset path for each page, so that I can view the site offline as well:

`config.php`

```php
collections: [...],

'getAsset' => function ($page, $assetPath) {
  $path = $page->getPath();
  $relativePath = preg_replace('/\b([a-zA-Z0-9]*-?[a-zA-Z0-9]*)\w+\b/', '..', $path);

  return ltrim($relativePath, '/') . mix($assetPath);
},
```

Using it in a layout file, i.e. `<link rel="stylesheet" href="{{ $page->getAsset('/css/main.css') }}">`, because I can't get those relative URLs with Mix. Not perfect, but it works. Doesn't even matter what it does, even `return`ing a simple string triggers the same error.

Next, I'm using this to create some JSON files with each collection's data:

```php
$events->afterCollections(function ($jigsaw) {
    $collections = $jigsaw->getCollections();

    foreach ($collections as $name => $contents) {
        $jigsaw->writeSourceFile($name.'.json', $contents);
    }

});
```

`npm run dev` and:

```sh
In PageVariable.php line 16:

  No function named "getAsset" was found in the file "config.php". (View: [project root]\source\_layouts\master.blade.php) (V
  iew: [project root]\source\_layouts\master.blade
  .php)


In PageVariable.php line 16:

  No function named "getAsset" was found in the file "config.php". (View: [project root]\source\_layouts\master.blade.php)


In PageVariable.php line 16:

  No function named "getAsset" was found in the file "config.php".


```

**Comment by hellocosmin** [comment]
For what it's worth, I got around it by getting collections from `getConfig()` and then looping over them:

```php
$events->afterCollections(function ($jigsaw) {

    $config = $jigsaw->getConfig();
    $collections = $config->collections;

    $collections->each(function ($item, $key) use ($jigsaw) {

        $site = $jigsaw->getCollection($key);

        // do stuff with collection

    });
});
```
Still, I wonder: if `getCollections()` worked in the `afterCollections` event, wouldn't it be faster than doing `getCollection($key)` for each collection? Thanks!

**Comment by damiani** [comment]
This should be fixed in https://github.com/tightenco/jigsaw/pull/203 . Run `composer update` to pull down v1.1.2 and let me know!

**Comment by hellocosmin** [comment]
Thanks Keith, that error is now gone in v1.1.2 :)

However, besides dumping the result to a file, I can't do anything with it. For example, doing this causes the Jigsaw build to fail:

```php
$collections = $jigsaw->getCollections();

$collections->each(function ($item, $key) use ($jigsaw) {
    var_dump($item);
});
```

`var_dump($key)` works fine and it correctly returns the collection key, but I'm not able to get the collection's content.
