### ISSUE TITLE
Blade tags in markdown source files cause unexpected rendering results

### ISSUE THREAD

**Issue by adamwathan** [tightenco/jigsaw#21]
Learning this as I build out the Jigsaw docs page :)

Basically if we have a Blade tag in a code block in a Markdown file, Blade actually tries to compile it. Need to sanitize that stuff before it hits the blade file.

**Comment by adamwathan** [comment]
Alternatively escape that crap manually in your Markdown and it works fine.

**Comment by dannyweeks** [comment]
Seems like something similar to twig's [verbatim](http://twig.sensiolabs.org/doc/tags/verbatim.html) would be good. It could also tie in nicely with #20 and have it serve as an example to the user.
