### ISSUE TITLE
How to change path of specific page?

### ISSUE THREAD

**Issue by raniesantos** [tightenco/jigsaw#210]
Scenario:

I'm trying to do [this](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/).

I have created this simple page:

**404.blade.php**
```blade
@extends('_layouts.master')

@section('content')
    <div class="has-text-centered content">
        <h1>404 Error</h1>
        <p>The page you were trying to access could not be found.</p>
        <a href="/" class="button is-primary">
            Go to home page
        </a>
    </div>
@endsection
```

How do I tell Jigsaw I want to output this file as `404.html` instead of `404/index.html`?

**Comment by damiani** [comment]
You can add a YAML header to the file (which would work for either a Blade or a markdown file) with a `permalink` key, and Jigsaw will use that for the final path:

```
---
permalink: 404.html
---
@extends('_layouts.master')
...
```

**Comment by raniesantos** [comment]
Right thanks, I was using the wrong key, I wrote `path: 404.html`

**Comment by damiani** [comment]
Haha as did I, I don't recall why we settled on `permalink`.
