### ISSUE TITLE
Jigsaw + Netlify custom 404

### ISSUE THREAD

**Issue by robbinfellow** [tightenco/jigsaw#211]
Hey,

Thanks for jigsaw, it's awesome. 🌟 

Was wondering if anyone tried setting up a custom 404 page using jigsaw + netlify as hosting service?

Reading from the [netlify docs](https://www.netlify.com/docs/redirects/#custom-404):

> Just add a 404.html page to your site and it’ll be picked up automatically.

Is that possible using jigsaw? My `404.blade.php` in `source/` will be rendered as `/404/index.html` on build.

Thanks

**Comment by hellocosmin** [comment]
You can use a `permalink` YAML front matter key to specify where that file should be output:

> 404.blade.md

```markdown
---
extends: _layouts.master
title: "404 Error"
permalink: 404.html
section: body
---

### Oops! Maybe you did lost your path.
```

Feature added in #93, but not documented.

**Comment by robbinfellow** [comment]
Cool! That's exactly what I was looking for, thanks! @hellocosmin

**Comment by damiani** [comment]
Thanks @hellocosmin!
I've added documentation for [how to do this](http://jigsaw.tighten.co/docs/custom-404-page/) now :)
