### ISSUE TITLE
Make php serve not only localhost

### ISSUE THREAD

**Issue by parotikov** [tightenco/jigsaw#216]
https://github.com/tightenco/jigsaw/blob/0b96887c62b4d8a9871b9b09887412ce273e2b23/src/Console/ServeCommand.php#L42

Hi!

At my VPS I serve scripts not on localhost, but on my external interfaces.
Please, update serve command to serve scripts on all interfaces (0.0.0.0) not only "localhost", or make a new argument like --ip

**Comment by reed-jones** [comment]
I believe the built in webserver is designed for testing/development. To expose it publicly you should use a proper web server such as Apache or nginx. http://php.net/manual/en/features.commandline.webserver.php
