### ISSUE TITLE
building not updating anymore

### ISSUE THREAD

**Issue by andreliem** [tightenco/jigsaw#219]
Has there ever been any known cases where the scripts command do not update the `build_local` or `build_production` anymore? It seems like after I installed the "tree" package to OSX (which updated brew), my jigsaw project will not update the build directories anymore.

Also, it seems like if I run ` ./vendor/bin/jigsaw serve` I get

```
Parse error: parse error in /.../vendor/illuminate/support/Collection.php on line 179
```

I'm wondering if the brew upgrade messed up my configuration. It says I'm on php 7.1 which seems right.

Any help is much appreciated

**Comment by andreliem** [comment]
Looks like I needed to setup brew to use php 7.1 again....

**Comment by dougblackjr** [comment]
For anyone coming here, check your config. I had an error in my `config.php` that was making it die quietly. (Note to self: Submit a PR to throw that error)
