### ISSUE TITLE
How to filter query collection by key/value pair?

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#223]
I try to get a filtered version of my `testimonial` collection.
I want to filter by the key/value pair: `active = 'yes'`

I cannot find my error.

In my collection:
```php
'collections' => [
        'testimonials' => [
            'path' => 'testimonial/{-slug}/'
        ],
```

In my markdown:
```
active: yes OR
active: no
```

In my blade:
```html
@php
          $testies->whereIn('active', ['yes'])->all()
@endphp
@foreach ($testies as $testy)
        {{ $testy->content  }}
@endforeach
````

This returns ALL testimonials, not the ones with `active: yes`.

What am I doing wrong?

**Comment by damiani** [comment]
From what I can tell, you're not setting the results of your `whereIn` to anything. You can also just use `where`, and you don't need the `all()`. This should work:

```php
@foreach ($testimonials->where('active', 'yes') as $testimonial)
    {{ $testimonial->getContent() }}
@endforeach
```

**Comment by minthemiddle** [comment]
Thanks a lot, @damiani - I mixed up `where` with `wherein`. The snippet works perfectly.
