### ISSUE TITLE
How to debug Markdown Handler problems?

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#225]
When building my Jigsaw page, I get quite a lot of errors, all saying the following:

`PHP Notice:  Trying to get property 'extends' of non-object in /Users/machine/Sites/site/vendor/tightenco/jigsaw/src/Handlers/MarkdownHandler.php on line 45`

How can I find out which markdown files cause the problem?

**Comment by linuxjuggler** [comment]
I guess the simplest way is to search all your files to see which file use the `extends` layout feature.
