### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by ralf57** [tightenco/jigsaw#227]
Hi all,
I'm thinking about adding an Admin UI (possibly based on Vue.js) to jigsaw, similar to the one that comes with https://www.getlektor.com/.
This would first require a REST API implementation from jigsaw to be consumed by a SPA client-side application.
Since I haven't find any plugin support in jigsaw, I was wondering about what would be the cleanest way to implement such API.

**Comment by cjf** [comment]
I have one (mostly) built for work.  I've been thinking of open sourcing it, but haven't asked for clearance to do so yet.  If there is interest in this, I'll see what I can do.

**Comment by raniesantos** [comment]
This is just a static site generator, I don't think it's meant to come with a CMS interface.

I do have a suggestion, try hosting it on Netlify and take advantage of their Netlify CMS. I have tried it and was able to successfully add it to my Jigsaw site.
