### ISSUE TITLE
[Proposal] Laravel presets

### ISSUE THREAD

**Issue by reed-jones** [tightenco/jigsaw#229]
Every time I start a new Jigsaw project, I need to change a number of config files to set it up just the way I like. It would be great if Jigsaw could have a preset system similar to [Laravel presets](https://laravel.com/docs/5.6/frontend)

**Comment by raniesantos** [comment]
This would be a great feature. I've had this idea to make a Jigsaw starter template for a while, but I think it would be better to package my setup as a preset.

**Comment by mattstauffer** [comment]
FYI, this is definitely happening. :) It's just going to take time for @damiani and me to finish it up and it may not look exactly like you're thinking, but we are definitely building something in this vein.

**Comment by mattstauffer** [comment]
Closing because #236.
