### ISSUE TITLE
Getting Cross-Origin Request Blocked error

### ISSUE THREAD

**Issue by ithardeep** [tightenco/jigsaw#231]
Hello,

I am facing the strange issue. Fonts being displayed if I open the HTML file that is placed in [root](https://i.imgur.com/2IWFOxt.png) but not from the subfolder. Jigsaw creates a directory for each MD file and when I try to open 
HTML file from subfolder then it throws [this](https://i.imgur.com/mPcNHyz.png) error

This is my site structure 
https://i.imgur.com/iFggQJY.png

And my site looks like [this](https://i.imgur.com/naznyn7.png)

I am using this URL for accessing the assets
  'assetUrl' => 'file:///G:/Hardeep Work/BCANotes/vendor/bin/build_local',

Please correct me where I am making a mistake

**Comment by ithardeep** [comment]
The reason why I am using that path because when I create md page jigsaw creates new folder and create index file and that file does not has path of ../ to return back to the root folder so css could be accessed by page.

Could you please suggest how I can handle this?

**Comment by lxqueen** [comment]
Don't use local filepaths for asset URLs. They *a)* won't work for production sites of course, and *b)* but most local file requests are now blocked in Chrome for security reasons (as they should be - iirc Firefox hasn't done this yet however).

Make sure you're BrowserSync (setup in the default Elixir/Mix file) to give you a "domain" to work with, and you can change your `assetUrl` to `/assets/` or similar, without using a local filepath.
