### ISSUE TITLE
Add feature: Jigsaw Generators

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/jigsaw#236]
@damiani and I are building a tool called Jigsaw Generators. I can't say for sure what the syntax will look like, but here's the current plan:

Jigsaw will come with a few "generators" out of the box, which will be like skeleton templates that you can generate your new sites with. Imagine a blog skeleton and an open source documentation skeleton.

We hope to also make it easy for other people to make their own generators and put them up on GitHub, and then make Jigsaw able to generate using those as well.

The templates we offer out of the box will be robust and well-designed, using Tailwind. I built really ugly versions of each and then handed it off to our designer Steve, and now some of our team members are updating the skeletons with the designs Steve made. Once we're done with those, @damiani will finish the work of adding the generators functionality to Jigsaw, and then we'll release it.

Here are screenshots of the ugly, before-design versions of the two templates I built:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/151829/43320872-aaf3c650-916f-11e8-8553-2964aa01e66e.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/151829/43320881-b55c6e08-916f-11e8-961a-e9a808697364.png">

/cc #229

**Comment by raniesantos** [comment]
I'm definitely going to contribute a blog skeleton/starter. Can't wait!

**Comment by m1guelpf** [comment]
Hey, what's the status on this?

**Comment by mattstauffer** [comment]
We decided to tank the whole idea ‘cause it was stupid.



Just kidding. We released it a few weeks ago. https://tighten.co/blog/jigsaw-starter-templates
