### ISSUE TITLE
Collection inside Collection

### ISSUE THREAD

**Issue by ButGuc** [tightenco/jigsaw#240]
Hello,

I need Collection inside Collection, because ı need tree structure for wiki.

sample

-Documents (Main Collection)
| _ 1 - Content
| _ 2 - Content
| _ 1 - Part (Sub Collection)
|  | _ 1 - Content
|  | _ 2 - Content
| _ 2 - Part (Sub Collection)
|  | _1 - Content
|  | _2 - Content
| _ 3 - Finsh Content

**Comment by damiani** [comment]
Duplicate #160
