### ISSUE TITLE
Using Mix Versioning with a renamed source directory

### ISSUE THREAD

**Issue by drweissbrot** [tightenco/jigsaw#245]
I'm trying to use a source directory with a different name (following [the docs](https://jigsaw.tighten.co/docs/deploying-your-site/), "Changing the Source and Destination Directories"), and also use Laravel Mix's versioning.

Doing this seems to be not possible at the moment, since when calling ``mix()`` in a Blade template, Jigsaw tries to locate the Mix manifest file in the ``source`` directory (cf. https://github.com/tightenco/jigsaw/blob/master/src/Support/helpers.php#L89 and https://github.com/tightenco/jigsaw/blob/master/src/Support/helpers.php#L46). Of course, it can't be found there since that directory doesn't exist.

This appears to fix this issue, but is quite "untidy":
```php
function public_path($path = '') {
	global $container;

	$build = $container->config->get('build');
	$source = ($build && array_key_exists('source', $build)) ? $build['source'] : 'source';

	return $source . ($path ? '/' . $path : $path);
}
```

**Comment by damiani** [comment]
Changing your public path in `webpack.mix.js` should allow you to do this. The current default configuration is:

```
mix.setPublicPath('source/assets/build');
```

Change the `source` there to your customized source directory, and Mix should pick it up when looking for the manifest.
