### ISSUE TITLE
Question: How do I manage php sessions in jigsaw?

### ISSUE THREAD

**Issue by akoolenbourke** [tightenco/jigsaw#252]
Hi all. Just trying to get my head around sessions in Jigsaw. I need to have a php backend that ends up serving my files and processing them as it serves (Sometimes outputting javascript objects into the served html). I also need to support sessions. So I need to get a session_start() in final output. Of course these will need to also be .php files, not html as they are and be enclosed in tags.

Is there any way to do this with jigsaw?

**Comment by damiani** [comment]
No, Jigsaw is designed to generate a static HTML site, not one that runs on a PHP backend. You can accomplish interactivity in a Jigsaw site using JavaScript, but server-based functionality like PHP sessions isn't possible.

**Comment by akoolenbourke** [comment]
Thanks, and damn! I guess I should look at something like Laravel?

**Comment by damiani** [comment]
Yes, probably. Laravel has built-in, robust support for sessions.
