### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by espositodaniele** [tightenco/jigsaw#253]
Hello to everyone,

It is possibile to use Vue.js? I couldn't find nothing about it.

Thanks

**Comment by damiani** [comment]
Yes, you're free to incorporate JavaScript into your site however you'd like; at Tighten, we integrate Vue.js into Jigsaw sites quite regularly.

**Comment by espositodaniele** [comment]
Hi there thanks for your fast reply. 
So Just need to install it through npm and i’m Ready to go? Could you give me an example on how to set up correctly? 

Thanks anyway

**Comment by damiani** [comment]
Yep, install it through npm, then add a containing element to your master template:

```html
<div id="app">
    {{ message }}
</div>
```

Then, in your `app.js`, load Vue and mount it into that element:

```js
window.Vue = require('vue');

new Vue({
    el: '#app',
    data: {
        message: 'Hello Vue!'
    }
});
```

When you compile your JavaScript with `npm run dev`, you should now see your Vue instance up and running.
