### ISSUE TITLE
create multi lingual website

### ISSUE THREAD

**Issue by iz5clj** [tightenco/jigsaw#261]
Hi.

Some idea on how I can build a static multi lingual website with jigsaw?
The main problem is the menu!
How would it be possible to load the menu in the appropriate language?

Thanks in advance.
Michel.

**Comment by ButGuc** [comment]
I solved the problem by using separate build and data source for each language. but this method makes the development process extremely difficult.  I wrote a script to accelerate the process to some extent. but it does not help much.

**Comment by iz5clj** [comment]
Thank you for your reply.

**Comment by damiani** [comment]
Duplicate of #25
