### ISSUE TITLE
Allow optional helpers.php file

### ISSUE THREAD

**Issue by raniesantos** [tightenco/jigsaw#263]
### Proposal

I suggest enabling Jigsaw to check if a `helpers.php` file exists in the project root.

If true, merge the arrays in `config.php` and `helpers.php`.

If false, nothing breaks (similar to how the `blade.php` file is optional).

### Reason

Jigsaw's flexibility allows us to easily add any helper in the config file.

This is great, but generally a config file should consist of constant/static values. It would make sense to put helper functions in a separate file.

Users should have the option to use a separate file, but still be free to put everything in a single file if they prefer it that way.

**Comment by fawzanm** [comment]
I'd like to work on this one.

**Comment by damiani** [comment]
@fawzanm Wonderful, let me know if you need any help!

**Comment by fawzanm** [comment]
@damiani currently jigsaw loads the config files to an array in `ConfigFile.php`. We can either have a separate file to check for custom config files or have an additional method in the ConfigFile.php itself. 

I think we should have a separate class and use that in the ConfigFile to lookup for the extra config items. Can I ge tyour thoughts on this?

**Comment by fawzanm** [comment]
@damiani currently jigsaw loads the config files to an array in ConfigFile.php. We can either have a separate file to check for custom config files or have an additional method in the ConfigFile.php itself.

I think we should have a separate class and use that in the ConfigFile to lookup for the extra config items. Can I ge tyour thoughts on this?

**Comment by fawzanm** [comment]
@damiani I am thinking of moving in this direction make more sense. 

We can take an optional second parameter (an array of file names) in the ConfigFile constructor and merge them to the config items. 

Can I have your input on this?

**Comment by raniesantos** [comment]
Note: I already made a PR for this in the past tightenco/jigsaw#264

Maybe if we could get input from @damiani on what could be improved here we could close both this issue and my PR

**Comment by damiani** [comment]
@raniesantos You are right, thanks for calling my attention to that PR.
@fawzanm Turns out that PR did close this issue... thanks for offering to pick this up, and if you're interested in tackling another Hacktoberfest issue, let me know and I'll help out as needed!

**Comment by fawzanm** [comment]
@damiani any other good first time issues available? :)
