### ISSUE TITLE
Error messages when building

### ISSUE THREAD

**Issue by buismaarten** [tightenco/jigsaw#265]
Hi,

Could you help me to solve the following problems?

![problem1](https://user-images.githubusercontent.com/16333228/44950330-2b771100-ae45-11e8-910c-4355b039f01d.png)

![problem2](https://user-images.githubusercontent.com/16333228/44950331-2b771100-ae45-11e8-8209-7e9ae7eee762.png)
The message says: The system can not find the specified file.

This errors messages suddenly come up since an hour ago.

**Comment by hellocosmin** [comment]
I sometimes get that too, happens particularly when saving a .scss file. I think there’s a race condition somewhere (probably between Webpack and Filesystem?).

**Comment by hellocosmin** [comment]
Just remember this: do you have the `watch` command configured to exclude `_tmp` directories?

Take a look at the Webpack config for reference:

https://github.com/tightenco/jigsaw/blob/eb20254b75e4eb72d5d6d9a7b1010ecf0dfaa88e/stubs/mix/webpack.mix.js#L10
