### ISSUE TITLE
Ctrl + C cannot stop it in the terminal

### ISSUE THREAD

**Issue by medmin** [tightenco/jigsaw#268]
I use MINGW64, vscode, WINDOWS 10

**Comment by fabalv** [comment]
I have exactly the same problem.

MINGW64, vscode, WINDOWS 10.

**Comment by Ostap34JS** [comment]
but, it maybe problem in MINGW64 O_o

**Comment by hellocosmin** [comment]
I've also had this happen in VSCode, which is setup to use Git Bash. It's only been doing that recently (less than 2 weeks?), so I'm starting to think there may be an issue as @Ostap34JS says, but perhaps only when run in VSCode?

Does it happen for you guys if you run the `watch` command in Git Bash, outside VSCode? For me, it doesn't.

**Comment by fabalv** [comment]
It happens when I run the command in standalone MINGW64, outside VSCode.

**Comment by damiani** [comment]
Is there any indication that this is a Jigsaw-specific issue? Or a Windows, or VSCode issue?
