### ISSUE TITLE
Jigsaw slugify removes accented characters

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tightenco/jigsaw#269]
Using the dash slugify of Jigsaw removes accented characters.

Example:
```
'posts' => [                                                             
            'extends' => '_layouts.post',                                        
            'path' => '{language}/{collection}/{-title}',
             'items' => [
                  'title' => 'Fútbol solidario'
]
```

The generated slugified title is `.../es/posts/ftbol-solidario/` with the `ú` dropped.

Would it be possible to instead of dropping the accented character just remove the accent, this would make it easier to use the Laravel `str_slug` function which removes accents and not the whole character.

**Comment by bhulsman** [comment]
I'll give this a try!
