### ISSUE TITLE
Jigsaw tries to process dot files and won't build the website

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tightenco/jigsaw#274]
I use VIM to edit my code and VIM creates swap files, for example, `.index.blade.php.swp`.

Jigsaw is trying to process these files and generates errors which cause the website to not build at all.

I think it would be best to not build any dot file or provide an option to do so.

**Comment by ruman63** [comment]
I don't see any point using dot files, when you can simply use underscore files (`_index.blade.php`) which are already supposed to be ignored by the jigsaw.

**Comment by anthonyterrell** [comment]
Hey @Anthony-Gaudino, 

Thank you for reporting this. Are you still running into this bug and Is there a repository we could use to replicate the issue with?

**Comment by sebsel** [comment]
I can confirm that this is very much a thing still.

```
./vendor/bin/jigsaw serve

Building local site
Building files from source...


In Factory.php line 291:

  Unrecognized extension in file: ./source/.index.blade.php.swp
  .


serve [--host [HOST]] [-p|--port PORT] [--no-build] [--] [<environment>]
```

The best way to reproduce is just start a new Jigsaw project and touch a file:

```
mkdir new-jigsaw && cd new-jigsaw
composer require tightenco/jigsaw
./vendor/bin/jigsaw init
touch source/.file.blade.php.swp
./vendor/bin/jigsaw serve
```

Note that it does not happen when I do `touch source/.file.swp`, seems like the `.blade.php` throws it off.
