### ISSUE TITLE
How do you run jigsaw in Windows 10 ? 

### ISSUE THREAD

**Issue by abrhambas01** [tightenco/jigsaw#275]
$  ./vendor/bin/jigsaw serve

Do you know how to run that in windows 10 ?

**Comment by raniesantos** [comment]
https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-

**Comment by raniesantos** [comment]
`php ./vendor/bin/jigsaw serve`

**Comment by abrhambas01** [comment]
@raniesantos  yeah man, figured it this one out just forgot to close the issue, but thanks anyways dude

**Comment by raniesantos** [comment]
you forgot to close the issue again

**Comment by abrhambas01** [comment]
@raniesantos oh yeah man, hahaha lol
