### ISSUE TITLE
HTML Minifier?

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#278]
Would it make sense to run a jigsaw site through an html minifier? Since the sites are static, I don't see why this shouldn't be in the build process by default as it saves $$ at scale. 

@damiani @mattstauffer

**Comment by mattstauffer** [comment]
I don't see the value for the majority of sites, and we try to address the needs of the majority with our out-of-the-box build processes, but I'm confident that the few people who need something like this can write it.

If this is something you've written, I'm sure writing up a blog post about it and then linking it on Builtwithjigsaw.com would be a great idea. Thanks!
