### ISSUE TITLE
Purge Css No Content Provided

### ISSUE THREAD

**Issue by espositodaniele** [tightenco/jigsaw#287]
Hello there, 

I'm trying to use the purgeCss/laravel mix plugin from [Spatie ](https://github.com/spatie/laravel-mix-purgecss) in my webpack configuration to remove unused css from my project with no success. 

### webpack.mix.js
 
```javascript
const { mix } = require('laravel-mix');
let build = require('./tasks/build.js');
var tailwindcss = require('tailwindcss');
require('laravel-mix-purgecss');

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/build');
mix.webpackConfig({
    plugins: [
        build.jigsaw,
        build.browserSync(),
        build.watch(['source/**/*.md', 'source/**/*.php', 'source/**/*.scss', '!source/**/_tmp/*']),
    ]
});

mix.options({
    postCss: [ tailwindcss('./tailwind.js') ],
    processCssUrls: false,
});

mix.js('source/_assets/js/main.js', 'js')
    .sass('source/_assets/sass/main.scss', 'css')
    .purgeCss();
```

When i run `npm run production` i got this error: 

> :point_right: **Erorr: No content provided**

Did anyone face this error? 
I will really appreciate any help. 

Thanks

**Comment by hellocosmin** [comment]
When using `laravel-mix-purgecss` outside of Laravel, [you need to tell it where to look](https://github.com/spatie/laravel-mix-purgecss#usage-outside-of-laravel).

Here's how I do it in the [jigsaw-tailwindcss](https://github.com/hellocosmin/jigsaw-tailwindcss) starter kit:

https://github.com/hellocosmin/jigsaw-tailwindcss/blob/565ee02fc256d02ea14ef0951c620ee24750b2e1/webpack.mix.js#L16-L28

**Comment by espositodaniele** [comment]
Yeah, Thanks a lot. 

Didn't read with attention the documentation provided. It happens sometimes :laughing:

**Comment by espositodaniele** [comment]
Yeah, Thanks a lot. 

Didn't read with attention the documentation provided. It happens sometimes :laughing:
