### ISSUE TITLE
Jigsaw consumes too much memory while building the website

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tightenco/jigsaw#290]
We have a website with multiple remote collections and Jigsaw consumes a lot of memory and takes a while to build the website, I'm more concerned about the memory consumption though.

As I understand the `$page` variable allows access to every single collection, and each collection data from every page, I have dumped my `$page` variable to find a 2.5GB text file!

It seems that Jigsaw copies the whole array defined on `config.php` for every single page created and also provides all this data for every single page!
I have for example more than 1200 occurrences of a collection that I just need to be visible on a few pages.

I'm following the idea presented here http://jigsaw.tighten.co/docs/collections-remote-collections/ where I get the data from a JSON file and using a template I just add the data to each page automatically.

Is there any way to reduce memory consumption and build time?

**Comment by damiani** [comment]
We have a feature in the works that might help with your situation, but whether or not it does depends on the makeup of your site; remote collections, in particular, are difficult to optimize. But could you give it a shot and report back your findings?

You would need to install the branch `dev-kd-speed-optimization`, and then run `jigsaw build -c` twice (make sure you use the `-c` parameter). The first run will build a cache, which will be used on the second run.

There are optimizations on that branch that might make even the first run of `jigsaw build` faster and less memory-intensive.
