### ISSUE TITLE
generating a menu!

### ISSUE THREAD

**Issue by simpel** [tightenco/jigsaw#293]
Hi Jigsaw!

I have a simple question, what would be the best way of generating a menu for my site? I've created several pages that I would like to be part of the site menu. I can't find an example that shows how to loop them out to a menu. Ideally I'd like some of the pages to be part of the main menu based on a page variable for example or something similar. 

My pages are stored in directories like this:

- index.blade.php
- the-story.blade.php
- About us
   - index.blade.php
   - locations.blade.php
   - loremipsum.blade.php
- Products
   - index.blade.php
   - somecategory.blade.php
   - our-promise.blade.php
...

**Comment by JoshuaBehrens** [comment]
You can make an event listener that collects all files in your source directory and build a menu tree that has to be put it in your configuration. This menu tree can be later on be evaluated in your blade files. I've done this before following the basics from this page [event listeners](https://jigsaw.tighten.co/docs/event-listeners/#registering-event-listeners-as-classes). The example for creating a sitemap file is similar to your case.

**Comment by anthonyterrell** [comment]
This can be done by adding a multidimensional array to your `config.php`. Then within your Blade files, you can traverse the array and it's nested pages. [See example Blade structure](https://github.com/tightenco/jigsaw-docs-template/tree/master/source/_nav).

```php
    'Getting Started' => [
        'url' => 'docs/getting-started',
        'children' => [
            'Customizing Your Site' => 'docs/customizing-your-site',
            'Navigation' => 'docs/navigation',
            'Algolia DocSearch' => 'docs/algolia-docsearch',
            'Custom 404 Page' => 'docs/custom-404-page',
        ],
    ],
    'Jigsaw Docs' => 'https://jigsaw.tighten.co/docs/installation',
```

There is an example of this in the new [Docs Template](https://github.com/tightenco/jigsaw-docs-template). Providing more code examples within our documentation is something we are currently working on.
