### ISSUE TITLE
Please add a feature description to the website / readme

### ISSUE THREAD

**Issue by wowcut** [tightenco/jigsaw#294]
Reading the website does not make clear what kind of features one can expect from jigsaw - I could not find any description of features available. What makes it different from e.g. [Grav](https://github.com/getgrav/grav) or [Hugo](https://gohugo.io/) - why does it exist? To better understand that it would be very good to have a feature list.

Thanks for your attention!

**Comment by damiani** [comment]
I think the [docs](https://jigsaw.tighten.co/docs/installation/) are a pretty sufficient outline of what features are available, but you are welcome to make a PR to https://github.com/tightenco/jigsaw-site if you think the docs be improved!
