### ISSUE TITLE
How to gate content?

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#297]
I would love to use Jigsaw for writing a book and let people access it on the web with a custom login. For this, I would need to gate the static pages that Jigsaw delivers.

How would you do that?

Things I researched so far:
- Netlify's Identify is not an option as it is super expensive (99$/month for 100 users)
- On [Surge Plus](https://surge.sh/help/adding-password-protection-to-a-project) ($30/month) you can password protect your content (good but still too expensive)
- Using basic HTTPAuth with Nginx/Apache is possible but hard to manage and has a horrible UX
- I could try to put it within a Laravel app ( deploy to a subfolder of `/public` such as `/public/book` as described [here](https://laracasts.com/discuss/channels/laravel/how-to-route-to-a-custom-html-file-in-public-folder#reply=349599) ) and use Laravel's perfect auth system, but I guess I cannot protect this new folder from direct access

**Comment by mattstauffer** [comment]
One option would be to put it within a Laravel or other non-static backend, but don't make your HTML public. Then have your backend app read the files and serve them. You could either have your backend app serve *all* files, or have a build step that moves just the content (HTML) into the private area but keeps the style/ss/etc. files public.

We've long wanted to build a "Jigsaw's-Markdown-parsing-tooling-as-a-Laravel-package" but it's gonna be a while before that happens, I think.

Another option would be to build some tooling to manage editing your Nginx/Apache files (the .htaccess or whatever it is that configures who can log in) and then put it behind HTTP basic auth.

I bet there are other ideas that smarter people than me can come up with.
