### ISSUE TITLE
Local Install

### ISSUE THREAD

**Issue by timgavin** [tightenco/jigsaw#30]
Followed these exact steps (copy/paste from docs)

```
cd ~/Sites
mkdir my-site && cd my-site
composer require tightenco/jigsaw
./vendor/bin/jigsaw init
jigsaw build
```

Received this
`-bash: jigsaw: command not found`

**Comment by adamwathan** [comment]
Use `./vendor/bin/jigsaw build` if you haven't added `./vendor/bin` to your `PATH`. I'll make a note to make that more clear in the docs! Thanks.
