### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by diazgilberto** [tightenco/jigsaw#303]
Hi Jigsaw team,

I'm used to the `read the docs` tool to write Markdown to create documentation. However, I'm enjoying this tool and we decide to use it at my work palce. 

Inside a markdown file, right after the main title at the top, I can insert `[TOC]` and `mkdocs` will parse all the `#` inside the file markdown starting with `##` since the title of the markdown file is `#`; just a way to not to include the title in the table of contents.

It is a way to create TOC with `jigsaw`?

**Comment by mattstauffer** [comment]
Hey @diazgilberto, 
There isn't right now, but that's a really clever idea. 

It's certainly possible! But we don't have it as a feature yet.

**Comment by diazgilberto** [comment]
Another markdown notation that the current markdown parser doesn't do is special notes. When you do the following...

```markdown
!!!note
    This is a special note.

!!!info
    This is a special info.

!!!warning
    This is a special warning.

!!!danger
    This is a special danger.
```

Some markdown parsers create a markup like this...

```html
<note>
    <header>Note</header>
    <p>This is a special note.</p>
</note>
<br>
<info>
    <header>Info</header>
    <p>This is a special info.</p>
</info>
<br>
<warning>
    <header>Warning</header>
    <p>This is a special warning.</p>
</warning>
<br>
<danger>
    <header>Danger</header>
    <p>This is a special danger.</p>
</danger>

```

With a style that looks like this...

<img width="839" alt="screen shot 2019-01-07 at 11 19 26 am" src="https://user-images.githubusercontent.com/9165819/50782625-3831c880-126e-11e9-8f11-0d58de36a0eb.png">

Since the current markdown parser doesn't do it, at my workplace we are using just `html` to credate the markup and added the tailwin css to make it happen.

I'm wondering if that is something you would like to pr.

**Comment by prb01-work** [comment]
Hey Jigsaw team,

I was wondering if this issue was closed because it was implemented as a feature? 
I couldn't find anything in the docs, and I tried the option that redeemefy had mentioned (`[TOC]`) without success. My use-case is to have a TOC that links to the relevant heading sections as well. Any pointers appreciated!
