### ISSUE TITLE
Can't use Blade in fenced code blocks with .md files

### ISSUE THREAD

**Issue by cossssmin** [tightenco/jigsaw#304]
I suppose this is related to #21.

However I try to use Blade code in a Markdown fenced code block, it always tries to compile it and fails.

Tried this:

```
    ```php
      @@if($page->title)<title>@{{ $page->title }}</title>@@endif
    ```
```

... and I get `syntax error, unexpected '&'`:

```
<pre><code class="language-php"><?php echo e('@'); ?><?php if($page-&gt;title): ?>&lt;title&gt;@{{ $page-&gt;title }}&lt;/title&gt;@endif</code></pre>
```

If I don't escape Blade:

```
    ```php
      @if($page->title)<title>{{ $page->title }}</title>@endif
    ```
```

... I get:

```
<pre><code class="language-php"><?php echo e('@'); ?>if($page-&gt;title)&lt;title&gt;{{ $page-&gt;title }}&lt;/title&gt;<?php endif; ?></code></pre>
```

It only happens with `.md` files - it works fine with `.blade.md`.

Am I doing something wrong?

**Comment by damiani** [comment]
This seems to only be an issue for single-line `@if`/`@endif` statements; it works as expected if formatted as 
```
    ```php
        @if ($page->title)
            <title>{{ $page->title }}</title>
        @endif
    ```
```

I'll take a look and see if there's an easy fix.

**Comment by hellocosmin** [comment]
Tried it, doesn't work. I get:

```sh
In ed9f9af4ae15eb98a23492d6d18096f0b70a79fa.php line 757:

  syntax error, unexpected ','
```

Here's what's at line 757 in that file:

```php
<?php $__env->stopSection(); ?>
<?php echo $__env->make(, \Illuminate\Support\Arr::except(get_defined_vars(), array('__data', '__path')))->render(); ?>
<?php echo $__env->make('_layouts.documentation', \Illuminate\Support\Arr::except(get_defined_vars(), array('__data', '__path')))->render(); ?>
```

**Comment by linuxjuggler** [comment]
I faced a similar issue with multiple characters such as `{{`,`}}`,`?php` and `@`

an example:
```
In 83f7f48d984c58c7467bc71e5a5e845875ad5b67.php line 9:

  syntax error, unexpected '<'
```

and here is the rendered php content for that line

```
<pre><code class="hljs language-php">&lt;<?php echo e(<span class="hljs-string">'?php'</span>); ?> 
```

The text in the MD file is :

```
```php
<?php 
```

for some reason, it added an apostrophe before and after `?php` and tried to echo the content of the code

```<?php echo e(<span class="hljs-string">'?php'</span>); ?>```

I though this is something related a small modification I did, but it looks like am not the only one facing the problem here

**Comment by clementblanco** [comment]
I'm experiencing a similar problem where if I mix blade+markdown in a `.blade.md` file with the following:

`source/_layouts/foo.blade.php`:
```html
<html>
    ...
    <body>
        <section>
            @yield('content')
        </section>
    </body>
</html>
```

`source/_components/foo.blade.php`:
```html
</section>
<section>
    <img src="/assets/images/foo.png" />
</section>
<section>
```

`source/page.blade.php`:
```md
---
extends: _layouts.foo
section: content
---

## Heading

Some text

@include('_components.foo')

## Another heading

Some other text
```

I'll get the following HTML output:
```html
<html>
    ...
    <body>
        <section>
            <h2>Heading</h2>
            <p>Some text</p>
        </section>
        <section>
            <img src="/assets/images/foo.png" />
<pre>...</pre>
            <h2>Another heading</h2>
            <p>Some other text</p>
        </section>
    </body>
</html>
```

It seems like the include of the partial gets messed up with automatic `<pre>` injection.

It doesn't happen if I make sure my partial is a one liner:
```html
</section><section><img src="/assets/images/foo.png" /></section><section>
```

Happy to investigate and submit a PR if I get pointed towards the right direction...

**Comment by damiani** [comment]
Recent changes (specifically https://github.com/tightenco/jigsaw/pull/416 and https://github.com/tightenco/jigsaw/pull/427) have fixed all the above issues.

As a general rule, in code blocks, `@` characters in `.md` files should render correctly now with no modifications. For `.blade.md` files, they should be escaped with an additional `@` so Blade ignores them: so, in a `.blade.md` file:

```php
```php
@@if(true) Foo @endif
```

should render as

```
@if(true) Foo @endif 
```
