### ISSUE TITLE
jigsaw init blog not working on windows

### ISSUE THREAD

**Issue by DominikGeimer** [tightenco/jigsaw#305]
Hi,

I installed jigsaw without any problem, but I would like to use the new blog template. 
I am using Windows 10. 

When i run:

    jigsaw init blog

I get the following error message.

   
    In Process.php line 1058:
    TTY mode is not supported on Windows platform.

Is there another way to use the blog template?

**Comment by ludo237** [comment]
Dockerize it

**Comment by DominikGeimer** [comment]
Thanks for your suggestion.

I went with the Linux Subsystem (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and it works fine!
