### ISSUE TITLE
clean up when building

### ISSUE THREAD

**Issue by vladdu** [tightenco/jigsaw#312]
I am new with Jigsaw, so maybe I am doing something wrong, but when I delete or rename a file, the old one is not removed from build_local. 

I think that either 'build' shluld always clean up before generating, or there should be a 'jigsaw clean' command. 

From a quick glance at the code, I thought that the "-c" option would help, but it doesn't. Am I missing something?

**Comment by damiani** [comment]
It should indeed remove the old file from `build_local`, and I just confirmed that it isn't, which is a bug. I will investigate and fix today.

**Comment by damiani** [comment]
OK, fixed and tagged release v1.3.4.

**Comment by vladdu** [comment]
Excellent, thank you!
