### ISSUE TITLE
Call to a member function format() on boolean

### ISSUE THREAD

**Issue by diomed** [tightenco/jigsaw#317]
I'm pretty sure I didn't change anything in that file, yet I have this error. 
Can you help me troubleshoot?

C:\laragon\www\texaco>vendor\bin\jigsaw build

Building local site
Building files from source...

In bb30513a70a468210a67b321b61f781d2c886df9.php line 3:

  Call to a member function format() on boolean (View: C:\laragon\www\texaco\source\_components\post-preview-inline.blade.php) (View: C:\laragon\www\texaco\source\_components\post-preview-inline.blade.php)

In bb30513a70a468210a67b321b61f781d2c886df9.php line 3:

  Call to a member function format() on boolean (View: C:\laragon\www\texaco\source\_components\post-preview-inline.blade.php)

In bb30513a70a468210a67b321b61f781d2c886df9.php line 3:

  Call to a member function format() on boolean

build [--pretty PRETTY] [-c|--cache [CACHE]] [--] [<env>]

**Comment by damiani** [comment]
Did you change the `getDate()` helper function in `config.php`? It seems to be returning a `boolean` instead of a `Datetime` object.

**Comment by diomed** [comment]
this is my config.php... anything wrong?
```
<?php

return [
    'baseUrl' => '',
    'production' => false,
    'siteName' => 'Monoplus',
    'siteDescription' => 'some stuff',
    'siteAuthor' => 'diomed',

    // collections
    'collections' => [
        'posts' => [
            'author' => 'diomed', // Default author, if not provided in a post
            'sort' => '-date',
            'path' => 'blog/{filename}',
        ],
        'categories' => [
            'path' => '/blog/categories/{filename}',
            'posts' => function ($page, $allPosts) {
                return $allPosts->filter(function ($post) use ($page) {
                    return $post->categories ? in_array($page->getFilename(), $post->categories, true) : false;
                });
            },
        ],
    ],

    // helpers
    'getDate' => function ($page) {
        return Datetime::createFromFormat('U', $page->date);
    },
    'getExcerpt' => function ($page, $length = 255) {
        $content = $page->excerpt ?? $page->getContent();
        $cleaned = strip_tags(
            preg_replace(['/<pre>[\w\W]*?<\/pre>/', '/<h\d>[\w\W]*?<\/h\d>/'], '', $content),
            '<code>'
        );

        $truncated = substr($cleaned, 0, $length);

        if (substr_count($truncated, '<code>') > substr_count($truncated, '</code>')) {
            $truncated .= '</code>';
        }

        return strlen($cleaned) > $length
            ? preg_replace('/\s+?(\S+)?$/', '', $truncated) . '...'
            : $cleaned;
    },
    'isActive' => function ($page, $path) {
        return ends_with(trimPath($page->getPath()), trimPath($path));
    },
];
```

**Comment by damiani** [comment]
That looks fine, could you show me the source of `post-preview-inline.blade.php`?

**Comment by diomed** [comment]
I don't think I changed anything there, but sure:

```
<div class="flex flex-col mb-4">
    <p class="text-grey-darker font-medium my-2">
        {{ $post->getDate()->format('F j, Y') }}
    </p>

    <h2 class="text-3xl mt-0">
        <a
            href="{{ $post->getUrl() }}"
            title="Read more - {{ $post->title }}"
            class="text-black font-extrabold"
        >{{ $post->title }}</a>
    </h2>

    <p class="mb-4 mt-0">{!! $post->getExcerpt(200) !!}</p>

    <a
        href="{{ $post->getUrl() }}"
        title="Read more - {{ $post->title }}"
        class="uppercase font-semibold tracking-wide mb-2"
    >Read</a>
</div>
```

**Comment by damiani** [comment]
Yes, you could, [here's a demo of a Jigsaw site that uses Netlify CMS](https://github.com/raniesantos/artisan-static) though I haven't used it myself yet.

**Comment by Jampire** [comment]
This can also happen if 'date' key in the YAMl header consists of time. 
For example, I need such key:
date: 2020-01-24 11:24
Seems, like Jigsaw can't parse date with time internally. Can it be fixed?
