### ISSUE TITLE
If Jigsaw is not installed globally, gulp tasks fail.

### ISSUE THREAD

**Issue by petemcfarlane** [tightenco/jigsaw#32]
Ideally I would like to install jigsaw globally with composer, but this is not yet possible because of a dependency conflict I have between some other packages.
I noticed that in the `gulpfile.js` the exec command is calling `jigsaw build` as if it is in the $PATH. Maybe a note in the docs would be enough here, saying that "if you are using jigsaw as a composer dependency , be sure to update the `gulpfile.js` to use `.vendor/bin/jigsaw` instead"?

An alternative solution might be to make a post install composer command that replaces the command with sed, something like `sed -i '' 's|jigsaw build|./vendor/bin/jigsaw build|' gulpfile.js` so the user doesn't even have to be aware of this?

Happy to create a PR but thought I'd get your thoughts first.

**Comment by adamwathan** [comment]
Hey Pete! One thing I actually have set up on my machine is to add `./vendor/bin` near the beginning my $PATH, so if I'm in a project directory, locally installed tools are preferred.

It's probably not a great idea to force everyone else to do that though, so definitely open to ideas to make this just work automatically.

Could we check for the existence of `./vendor/bin/jigsaw` and use that if it exists, falling back to the global install? Haven't worked with filesystem APIs in Node/Gulp before but can definitely look into it.

**Comment by petemcfarlane** [comment]
Yup, you could create a bash file, something like this, to check for existence. Not sure if it's too much of a hack though?
```bash
#!/bin/bash
if type jigsaw &> /dev/null; then
    echo jigsaw exists
elif type ./vendor/bin/jigsaw &> /dev/null; then
    sed -i '' 's|jigsaw build|./vendor/bin/jigsaw build|' gulpfile.js
    echo ./vendor/bin/jigsaw exists, updated your gulpfile.js
else
    echo jigsaw executable not found in your \$PATH
fi
```

**Comment by petemcfarlane** [comment]
Maybe just documenting it as something to be aware of would be cleaner?

**Comment by adamwathan** [comment]
I think we can use something like this directly in the gulpfile: https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback

Will have a play in a bit :+1:

**Comment by erickpatrick** [comment]
Hi @petemcfarlane, the `gulp` command now is able to check whether one has a global or local version of `jigsaw`. Things are easier for us, now =)

**Comment by damiani** [comment]
Addressed in https://github.com/tightenco/jigsaw/pull/85
