### ISSUE TITLE
Disable Pretty Urls

### ISSUE THREAD

**Issue by badalsurana** [tightenco/jigsaw#320]
I am not able to disable Pretty Urls. I have added `'prettyUrls' => false` in my config.php file but it's still not working.

**Comment by simonhamp** [comment]
For reference, you _can_ set this in your `config.php` now - the key is simply `pretty` and defaults to true.

I haven't dug into the source or issues to find out when this became possible or if it's even intentional, but it works.

**Comment by husseinalhammad** [comment]
@simonhamp this was added in v1.3.31
https://github.com/tighten/jigsaw/releases/tag/v1.3.31

Relevant:
https://github.com/tighten/laravel-mix-jigsaw/pull/18
