### ISSUE TITLE
Remote variables

### ISSUE THREAD

**Issue by Jamesking56** [tightenco/jigsaw#321]
Hello,

I want to get some variables during build from a remote API. I know you can create remote collections but can you create remote variables?

My use-case is that I want my site to display the prices set by my separate billing system.

**Comment by damiani** [comment]
Yes, you can do this with an event listener, during the `beforeBuild` event. There's an [example in the docs](https://jigsaw.tighten.co/docs/event-listeners/) that demonstrates fetching the weather from a remote API, and storing it in a config variable.

**Comment by Jamesking56** [comment]
Cool, I think I might go down the JavaScript route though since if the pricing changes then I don't have to redeploy the entire site :+1:
