### ISSUE TITLE
npm run watch --pretty=false

### ISSUE THREAD

**Issue by iainheng** [tightenco/jigsaw#323]
How do I disable pretty URL `--pretty=false`  while developing with `npm run watch` ?

**Comment by hellocosmin** [comment]
You could do something based on the environment, in `tasks/build.js`.

For example, in [Maizzle](https://github.com/maizzle/maizzle/blob/master/tasks/js/build.js), I create a variable:

https://github.com/maizzle/maizzle/blob/07727e20944b3ae53820f064a86b155384466c6f/tasks/js/build.js#L24

and then I use it in the `command.get()`:

https://github.com/maizzle/maizzle/blob/07727e20944b3ae53820f064a86b155384466c6f/tasks/js/build.js#L29

**Comment by damiani** [comment]
That's a great solution, you're also free to add `--pretty=false` directly to the `build` command in `tasks/build.js` if you don't need it controlled by environment.
