### ISSUE TITLE
301 Redirects

### ISSUE THREAD

**Issue by dgursh** [tightenco/jigsaw#327]
Hi What is the best way to do lots of 301 redirect with a jigsaw static site?

I was thinking about running the following in the afterCollections event, but it seems to be throwing this error: 

```
Warning: Cannot modify header information - headers already sent by (output started at
```

```
$diagrams = $jigsaw->getCollection('posts')->where('category', 'technology')->each(function ($item) use ($jigsaw) {;
        if ($item->title == 'Post 1') {
            header("Location: /post1/", true, 301); 
        }
     });
```

Or should this be done on the server side like with Amazon S3?

**Comment by stancl** [comment]
This is a static site generator, so it generates HTML. You can't return a header from HTML. You can use a meta tag for redirecting the browser.
