### ISSUE TITLE
Collection Item pages not displaying data

### ISSUE THREAD

**Issue by marcschneider123** [tightenco/jigsaw#333]
$page data is not rendering in collection item pages if i use `@yield('content')` in my base.blade template.
Renaming 'content' to something else like `@yield('body')` is working fine.
Not sure what the problem here is, if it´s a bug or if you just cant name your blade section 'content' when using Collections.

I use a base.blade template looking something like this:
```
<!DOCTYPE html>
<html lang="de">
<head>
    @include('_layouts.header')
</head>
<body>
	<div id="app">
		@yield('content')
	</div>
	@include('_layouts.footer')
</body>
</html>
```

My collection in config.php:
```
'collections' => [
	'events' => [
		'extends' => '_layouts.events',
		'items' => function() {
			$events = json_decode(file_get_contents('./source/assets/events/events.json'));
			return collect($events)->map(function ($event) {
				return [
					'title' => $event->title,
					'location' => $event->location,
					'date' => $event->date,
				];
			});
		},
		'path' => 'events/{title}',
	],
],
```

My events.blade:
```
@extends('_layouts/base')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1>{{$page->title}}</h1>
				<p>
					{{$page->location}}
					<br>
					{{$page->date}}
				</p>
			</div>
		</div>
	</div>
@stop
```

**Comment by damiani** [comment]
The happens when using _remote_ collections, since Jigsaw expects a key named `content` to be in each item in the `items` array. Having a section in your `base` template named `content` is conflicting with this, which is why nothing is getting rendered.

**Comment by benmcm1994** [comment]
> The happens when using _remote_ collections, since Jigsaw expects a key named `content` to be in each item in the `items` array. Having a section in your `base` template named `content` is conflicting with this, which is why nothing is getting rendered.

Surely this shouldn't be an issue? In the Jigsaw and Blade documentation the base template uses a content section. Maybe the named key should be something other than content.
