### ISSUE TITLE
Remote collection error handling/aborting the build

### ISSUE THREAD

**Issue by philvv** [tightenco/jigsaw#335]
I have been rebuilding a website with JigSaw and pulling remote collections from a Directus CMS. All works well (although I did get tripped up with our master template using @yield('content') and it clashing with the collections 'content' variable). 

The site will utilise automatic builds on Netlify and a build will be kicked off from some CMS events, so we need to be sure the remote collections are successful. 

Question: If the CMS fails during a build, how best to abort? 

I tried throwing exceptions and exiting in php but the build passes with empty collections. I am an NPM novice but I did find a hacky way by passing a string in php exit and looking at stdout in the build.js. 

Thanks,
Phillip

**Comment by damiani** [comment]
If you're retrieving remote data using `file_get_contents` (as demonstrated in the documentation), it only throws a PHP warning if it fails; but you should be able to check the results of that remote call, and `die()` if it doesn't retrieve the data you expect:

```
'items' => function() {
    $posts = json_decode(file_get_contents('https://api.mycms.com/posts'));

    if (! $posts) {
        die('Error retrieving remote posts.');
    }

   ...
```
