### ISSUE TITLE
Collections + blade + generating PHP file

### ISSUE THREAD

**Issue by godbout** [tightenco/jigsaw#336]
I'm switching my static sites from Nanoc to Jigsaw. I love it.

I have a site though that is using one PHP file to randomly throw a writing from the site to the user.

I was able to generate the PHP file with Jigsaw through quite a lot of tinkering, and I'm wondering if there's a better way because the current one feels a bit dirty to me.

Here's the Jigsaw source file:
```php
---
permalink: random/index.php
---
<?php
    $urls = $writings->map(function ($writing) {
        return "'{$writing->getUrl()}'";
    });

    $urls = implode(",\r\n    ", $urls->toArray());

    echo <<<EOT
<?php

\$urls = [
    $urls
];

header('Location: ' . \$urls[array_rand(\$urls)], true, 303);

EOT;

```

Here's the generated PHP file:
```php
<?php

$urls = [
    '/writings/3',
    '/writings/again'
];

header('Location: ' . $urls[array_rand($urls)], true, 303);

```

So I had to use a blade source file to have access to the collections of writings, then I had to add the permalink so that the generate file stays a PHP file, then I had to use heredoc to generate the PHP file. It works, but not as pretty as I expected.

Am I being more complicated that I need to? Is there a better way to achieve that? Actually writing this I'm thinking about the event listeners, maybe?

I have it working but still very curious if there's a better way, for future projects. Thanks!

**Comment by damiani** [comment]
This might be a good place to use JavaScript instead, adding this to `random.blade.php` should do the trick:

```
<script>
    var writings = @json($writings->map->getUrl()->values())

    window.location = writings[Math.floor(Math.random() * writings.length)];
</script>
```

**Comment by godbout** [comment]
OH. Thank you! In another project with Jigsaw I redirect the 404 to the homepage through an HTML redirect. For this one here I went with redirect through PHP. For whatever reason JavaScript went over my head. Looks good thanks!

**Comment by godbout** [comment]
A little informative update: I ended up using my first version of generating a PHP file because the JavaScript redirect flickers the site. The PHP one does not, and after quite some tests I assume it's due to it being a server 303 server redirect. The non-flickering experience is much better, feels like a 'writing' is just being inserted in the page 😍️
