### ISSUE TITLE
Read page variables within "events"

### ISSUE THREAD

**Issue by amadeann** [tightenco/jigsaw#337]
I'd like to exclude certain pages from the sitemap generated using the method described in #189.

My pages include a variable 'robots' defined in the front matter, as in:

    ---
    robots: noindex, follow
    ---

The value of this variable is used in my master template:
`<meta name="robots" content="{{ $page->robots ?? 'all' }}">`

I'd like to read that variable from within the `afterBuild` event hook, and do not add pages to the sitemap which are defined as `noindex`.

Is this doable? Basically what I don't know how to do is to read page variables having only the output path strings (returned from `$jigsaw->getOutputPaths()`).

EDIT:
Another way I can think of is to iterate through all the source pages, and read page variables from there, creating an array of `noindex` pages. But again - I do not know how to loop through all source pages in a way that will give me page variables.

**Comment by damiani** [comment]
There isn't a way to get the parsed contents of your source files within the event listener. It might be easier to modify your sitemap generator to include an array of files to exclude; see, for example, [how we do it on the docs template](https://github.com/tightenco/jigsaw-docs-template/blob/master/listeners/GenerateSitemap.php).

**Comment by amadeann** [comment]
This is what I ended up doing, but it means I have to maintain the indexing exclusion logic in two places: 
- page template
- sitemap generator

I could probably move it to the `config.php` file, but then I need to make sure that file names (paths) are consistent. The best place in my opinion to keep the index/noindex logic is "front matter" of a given page.

**Comment by damiani** [comment]
This is possible as of version 1.3.20, through the `$jigsaw->getPages()` method. For each page in the collection that's returned, you can access any `$page` variables—such as `robots` in your case—as well as metadata methods like `getPath()` and `getModifiedTime()`. 

See #433 and the [`getPages()`](https://jigsaw.tighten.co/docs/event-listeners/#helper-methods-in-$jigsaw) section in the docs.
