### ISSUE TITLE
Pass options to browsersync from webpack.mix.js 

### ISSUE THREAD

**Issue by godbout** [tightenco/jigsaw#338]
It seems the only option we can pass to `browsersync` from the `webpack.mix.js` is the `proxy` option (see https://github.com/tightenco/jigsaw/blob/cce154fa8063348f95e7cdc714fe054fbe36d74d/stubs/mix/tasks/build.js#L32)

I needed to pass the `browser` option (default to Safari in my case, by choice, but developing with Chrome). I ended up editing the `build.js` file, it works of course, but I think it'd be nice to have only one place to play with the options, that is the `webpack.mix.js`.

What do you guys think? Interested in a PR?

**Comment by damiani** [comment]
I think it's best to keep `build.js` as-is by default, and to make any modifications that you need to make to the BrowserSync setup there. The BrowserSync build options were intentionally separated out from `webpack.mix.js` to help simplify `webpack.mix.js` for users who are less comfortable working with Webpack.

That said, once those files are initialized into your project, they're yours—you're free to combine them into a single file, or modify them however you wish.

**Comment by godbout** [comment]
Fair enough, thanks @damiani. Although I didn't mean to modify where the BrowserSync options are, but just to allow a way to pass an array of them to override (or add) the defaults if needed, like it happens with `watch`. It wouldn't affect people not comfortable with Webpack, but it would ease those familiar with it and/or BrowserSync. But I might be wrong as I'm not extra familiar with frontend. I first looked at the doc of Jigsaw but couldn't find anything related to those `tasks` files, then checked `laravel-mix`, then dig in the code and finally found what I was looking for. At first I just passed my options to the `browserSync()` function expecting it to work as I do with my other Laravel projects, took a bit of time to find out what was the issue :))

**Comment by godbout** [comment]
nice. it seems i was trying again to do the same thing and ended up on my own issue 😅️ finding out that now it's possible to pass all `browserync` options through the jigsaw config, super cool: https://github.com/tighten/laravel-mix-jigsaw/blob/c9dcb24ca7aca8a8d50f1aef637c4c9ed1667663/index.js#L46

thanks!
