### ISSUE TITLE
Working with PHP 7.0+

### ISSUE THREAD

**Issue by rafaelcavalcanti** [tightenco/jigsaw#341]
Hello, i read that project is only supported by php 7.1+. I would like to know if is needed so much effort for working with php 7.0 or it's better to looking for some other instead?

Thank you

**Comment by rafaelcavalcanti** [comment]
I'm trying to working with Laravel 5.5.*. + php 7.0.*

**Comment by mattstauffer** [comment]
@rafaelcavalcanti Jigsaw isn't a package you bring into Laravel, it's a separate tool on its own. And you just run it on your local machine; your remote machine doesn't need PHP at all. So as long as your local machine has a modern version of PHP, you should be fine.
