### ISSUE TITLE
Accessing collections in config

### ISSUE THREAD

**Issue by godbout** [tightenco/jigsaw#343]
Wondering if there's a way to do that. I want to change my page title if the page is the newest item in my collection. I can do that by passing the latest item through my helper but it's a little dirty. Would be nice to access directly the collection through my helper, within the `config.php`. Is there a way to do that? Thanks!

**Comment by damiani** [comment]
There is a way, though it's somewhat unofficial, but should work in your situation. In `config.php`, every helper method inside a collection automatically receives an instance of `CollectionItem` as the first parameter. This doesn't give you full access to the collection, but it _does_ give you the same methods that are used for linking to other collection items within your templates, namely `getFirst()`, `getLast()`, `getNext()` and `getPrevious()`. So if you're sorting your collection by date, you could access `getFirst()` or `getLast()` (depending on what direction you're sorting in) and use that to determine if a page is the newest item:

```php
'getTitle' => function ($page) {
    return $page->getFirst()->getFilename() === $page->getFilename()
        ? 'This is the newest post!'
        : $page->title;
},
```

**Comment by godbout** [comment]
Oh, great! Thanks @damiani. Guess I should have found that out.
