### ISSUE TITLE
Can't use non-ascii characters in filename.

### ISSUE THREAD

**Issue by jdssem** [tightenco/jigsaw#344]
I would like to use Korean file name such as '세종대왕께서-한글을-창제하셨다.md' but the post url only returns '/posts/--'. Do you have any plan to support non-ascii languages?

**Comment by mattstauffer** [comment]
We would love to! But we don’t have a ton of experience with that. Do you?

**Comment by damiani** [comment]
That filename works as expected when I build a Jigsaw site with `세종대왕께서-한글을-창제하셨다.md` (it builds as expected to `posts/세종대왕께서-한글을-창제하셨다`). Can you provide a repo of your project, and give more information about your setup? There may be some other issue going on, or possibly a difference in PHP configurations.

**Comment by jdssem** [comment]
@mattstauffer Thanks. I'm not a developer so I might not be able to PR for this, but I'd like to help fixing this problem.

@damiani That's interesting. This is my repo. https://github.com/jdssem/dev.jaedong.kim
I've tested on MacOS Mojave with PHP 7.2

I've tried to build the site using these commands both `jigsaw build` and `npm run watch`.
I've also checked on browser with `jigsaw serve` and foldername.test domain with laravel valet.

**Comment by jdssem** [comment]
I've just jumped into the source code and found this.

CollectionPathResolver.php 165 line

```
    /**
     * Transliterate a UTF-8 value to ASCII.
     *
     * @param string $value
     * @param string $language
     *
     * @return string
     */
    private static function ascii($value, $language = 'en')
    {
        $languageSpecific = static::languageSpecificCharsArray($language);

        if (!is_null($languageSpecific)) {
            $value = str_replace($languageSpecific[0], $languageSpecific[1], $value);
        }

        foreach (static::charsArray() as $key => $val) {
            $value = str_replace($val, $key, $value);
        }
        
        return preg_replace('/[^\x20-\x7E]/u', '', $value);
    }
```

Before preg_replace the `$value`, `$value` is `/세종대왕께서-한글을-창제하셨다/`. But after preg_replace, it returns `/--/`. Korean unicode starts from AC00 to D7AF.



![image](https://user-images.githubusercontent.com/978944/58406170-f9c56a80-80a3-11e9-981d-1059328912a9.png)

**Comment by damiani** [comment]
Ah, I did a test with a regular file named `세종대왕께서-한글을-창제하셨다.md`, not a collection item. That `ascii` method is definitely the culprit. I'll see what we can do!

**Comment by jdssem** [comment]
Thanks @damiani

**Comment by jdssem** [comment]
I've just found that there is something more for supporting non-ascii language filename.

I have `인디스쿨.md` in categories directory.
When I try to build for production, it says

```
 DONE  Compiled successfully in 9155ms                                                                                                                                               22:10:42

          Asset      Size  Chunks             Chunk Names
    /js/main.js   157 KiB       0  [emitted]  /js/main
/js/main.js.map   458 KiB       0  [emitted]  /js/main
   css/main.css  12.7 KiB       0  [emitted]  /js/main

In Sitemap.php line 243:

  The location must be a valid URL. You have specified: https://domainname/categories/인디스쿨.


build [--pretty PRETTY] [-c|--cache [CACHE]] [--] [<env>]
```

This is because of the FILTER_VALIDATE_URL.

Sitemap.php
```
    /**
     * Takes a string and validates, if the string
     * is a valid url
     *
     * @param string $location
     * @throws \InvalidArgumentException
     */
    protected function validateLocation($location) {
        if (false === filter_var($location, FILTER_VALIDATE_URL)) {
            throw new \InvalidArgumentException(
                "The location must be a valid URL. You have specified: {$location}."
            );
        }
    }
```

**Comment by damiani** [comment]
@jdssem I've opened a PR (https://github.com/tightenco/jigsaw/pull/346) that will fix the filename issue. 

The Sitemap generation, however, uses the package `samdark/sitemap` which runs the function containing `FILTER_VALIDATE_URL`. The author of that package points out in [this issue](https://github.com/samdark/sitemap/issues/64) that the XML sitemap specification requires non-ASCII characters in URLs to be encoded, which you would need to do in the `GenerateSitemap.php` file. For example, the added line with `implode` below would `urlencode` each segment of the path, so your sitemap would be valid:

```php
collect($jigsaw->getOutputPaths())
    ->reject(function ($path) {
        return $this->isExcluded($path);
    })->each(function ($path) use ($baseUrl, $sitemap) {
        $path = implode('/', array_map('urlencode', explode('/', $path)));
        $sitemap->addItem(rtrim($baseUrl, '/') . $path, time(), Sitemap::DAILY);
});
```

I can add this to the default `GenerateSitemap.php` code for the blog and docs templates, but you'd need to add this line manually to your installation (since the `GenerateSitemap.php` is part of the templates, not part of Jigsaw itself).

**Comment by jdssem** [comment]
@damiani Thanks for your great help!!
