### ISSUE TITLE
@includes inside of @yield('content') not working correctly

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#350]
I think this may be related to https://github.com/tightenco/jigsaw/issues/304

Here goes.

I have been running a site using blade markdown files and and some of the content there may be a line like....

`@include('partials.form')`

This generally works fine.

Now, however, I'm trying to use the remote collections utility to pull in this page content from an api.  That same content has that same line in it, but now it doesn't process it and I get the above line verbatim in the generated page.

After some digging, I found that if I separate that @include line from all the other content and make sure there are newlines around it, it will process.  So that's the first bug.

The second, related bug, is that sometimes that @include line takes some arguments like so...

`@include('partials.form', ['is_cool' => true])`

Same as above, it won't process unless I separate it from all the other content with a newline or two on both top and bottom, but now it has a new problem.  Whatever utility is processing that line hates the '=>' in there.

I isolated it and took a look in the temporary cache file.  This is what is being generated...

```
<?php $__env->startSection('content'); ?><p>  <?php echo $__env->make('_partials.form', ['is_cool' =&gt; true], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>  </p><?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.page', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
```

And the error on line 1 of that file is 
`syntax error, unexpected '=', expecting ']'`

I've tinkered with this to the end of my wits and have no idea how to proceed.  Anyone have any insight?

**Comment by damiani** [comment]
It's very possible those two issues are related...I'll take a look, thanks for the detailed writeup!

**Comment by cjf** [comment]
I did a bit more digging, and have more "clues" for you.  Two important things...

1. `.md` files handle @include differently than `.blade.md` files
2. There is magic in`<p>` tags

I've attached a sample project that goes through all the below scenarios if you're interested.  It uses the blog template, but it should be fairly obvious where everything lives if you fire it up.  Hope this helps.

**_Scenario 1:_**
If you have a straight markdown file (say 'test.md') and you put `@include('_partials.test')` on it's own line, it will print it out verbatim.  The system doesn't attempt to process it.

If you have a blade markdown file (say 'test.blade.md') and you put `@include('_partials.test')` on it's own line, it will process it and do what you expect.

**_Scenario 2:_**
If you have a straight markdown file (say 'test.md') and wrap the include in <p> tags `<p>@include('_partials.test')</p>` it will process it and do what you expect.

If you have a blade markdown file (say 'test.blade.md') and wrap the include in <p> tags `<p>@include('_partials.test')</p>` it will ignore it and print nothing.

If you have a blade markdown file (say 'test.blade.md') and wrap the include in some other tag, (I've only tested span and div) `<span>@include('_partials.test')</span>` it will process it and do what you expect.

**_Scenario 3:_**
If you have a straight markdown file (say 'test.md') and you put `@include('_partials.test', ['page_title' => 'My Amazing Site'])` the build process fails complaining about the syntax error that I reported originally.

`syntax error, unexpected '=', expecting ']'`

If you have a blade markdown file (say 'test.blade.md') this parameter passing syntax works.

**_Scenario 4:_**
For remote collections, it appears as though the system treats them as if they are straight markdown files, not blade markdown files, with all the oddities mentioned above consistent with those scenarios.  Perhaps treating these collections as .md files is desired behavior, but it isn't for me.  So in the process of figuring out a fix for this, if there was a way to make these remote collections behave as blade.md files, it would definitely make my life easier.


[jtest.zip](https://github.com/tightenco/jigsaw/files/3281401/jtest.zip)

**Comment by damiani** [comment]
Your test site (thanks for that!) has all scenarios working correctly now, after https://github.com/tightenco/jigsaw/pull/416. Note, however, that in a straight `.md` file, `@include()` should never be processed as a Blade directive; it should always output verbatim as the text `@include()`.
