### ISSUE TITLE
How do I remove the html tags in my markdown files, also giving my suggestion

### ISSUE THREAD

**Issue by abrhambas01** [tightenco/jigsaw#351]
So, I now got it I was really confused with the documentation, I'm hoping someone can really give their time and effort to make it really straightforward and not really confusing to understand, for a beginner like me

Such as like : 
If you'd like to generate an individual page for each of your collection items—for example, a page for each blog post—specify a parent template file in the extends key of the YAML front matter, or with the @extends directive in a Blade file, just as you would with a regular Jigsaw page. For example:

Because what I've done is
```
---
extends : _layouts.content
title  : Blogs
section : content
---
<h1 class="text-3xl">All Blogs</h1>

@forelse ( $blogs as $blog)
<p>{{ $blog }}</p>
@empty
<h1 class="font-bold text-3xl font-display text-red-600 mt-4">501. Blogs will be added in the near future</h1>
@endforelse
```
but it doesn't loop the blogs key in the collections in the config.php instead it loops the one inside the _blogs folder. Also in the blogs list the <p tags show such as

<p>blog 1....</p> with p tags.

instead of just seeing 

Blog 1

Can someone help me ? I'm a newb in static sites :)

**Comment by damiani** [comment]
The `collections` key in `config.php` is where you tell Jigsaw the names of your collections and what settings (if any) they have, not where the collection items live; if you have a collection named `blogs`, then the collection items themselves live in the `_blogs` folder. Check out the [Defining a Collection](https://jigsaw.tighten.co/docs/collections/#defining-a-collection) section of the docs, which goes into detail about how `config.php` is used for collections.

In your case, `config.php` could be as simple as:

```php
<?php

return [
    'collections' => [ 'blogs' ],
];
```

As for why you are seeing `<p>` tags, it's hard to guess what's going on by looking at what you've posted above. Can you give me a link to your repo so I can see the whole site?

**Comment by abrhambas01** [comment]
I thought I can add the contents of my blogs in the collections array in the config.php file, so it makes sense to me now

**Comment by abrhambas01** [comment]
Hey @damiani 

```
@forelse ($projects as $project)
{{ $project }}
@empty
<p>No projects yet</p>
@endforelse
```
And this is my blog content
> 1-Project.blade.md
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque provident minus ab dicta fuga reiciendis? Voluptas sed minima fuga consectetur.


> 2 - Project2.blade.md
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet nulla iure hic quaerat at reprehenderit impedit obcaecati vitae? Dolores, obcaecati.

It displays when i'm on my /projects uri

```<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque provident minus ab dicta fuga reiciendis? Voluptas sed minima fuga consectetur.</p><p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque provident minus ab dicta fuga reiciendis? Voluptas sed minima fuga consectetur.
</p>
```
