### ISSUE TITLE
[Feature request] Default Collection filtering

### ISSUE THREAD

**Issue by carbontwelve** [tightenco/jigsaw#354]
Currently it seems that Jigsaw provides collection filtering via usage of the filter method provided by Laravels collection class. However I can't seem to figure out how to filter a collection by frontmatter when accessed via pagination.

I want to filter out all posts that have draft set to true so it would be useful to be able to define that filter in the collections configuration.

**Comment by wing5wong** [comment]
also interested in this - in our case "upcoming events" and would like to filter out events before todays date.

```
---
pagination:
    collection: events
    perPage: 25
---
```

**Comment by damiani** [comment]
This is already possible with the `filter` key, which you can add to your collection settings in `config.php` (see https://jigsaw.tighten.co/docs/collections-filtering/); for example, if you have a `draft` setting in the frontmatter for a post, this filter will exclude it:

```php
'collections' => [
    'posts' => [
        'filter' => function ($item) {
            return ! $item->draft;
        },
        ...
```

I just tested, and this functions correctly for paginated collections as well.
