### ISSUE TITLE
[Question] Build Count

### ISSUE THREAD

**Issue by g33kcentric** [tightenco/jigsaw#355]
Hi there! 

I was just wondering if there were any built in ways that I could find out how many times a file has been built, in an event? 

There are certain processes I need to execute, but only on first build of a file, I know how I could implement it, but is there anything existing? 

Thank you! :)

**Comment by damiani** [comment]
No, there isn't any built-in way to do that.

**Comment by g33kcentric** [comment]
Ok great thanks :)
