### ISSUE TITLE
[Question] Is there a way to add multiple menus?

### ISSUE THREAD

**Issue by mikebronner** [tightenco/jigsaw#356]
I am trying to make a hybrid of both the blog and docs templates, and would like a horizontal top nav menu, as well as a left-sidebar nav menu. The problem I'm running into is having both render when clicking the hamburger menu on small screens.

Any thoughts how this might be achieved? Thanks!

**Comment by anthonyterrell** [comment]
Hey @mikebronner 

Both of the Jigsaw templates (docs & blog) were built with Tailwindcss. You can use a combination of [display classes](https://tailwindcss.com/docs/display) to render the appropriate navigation on mobile views. 

E.g.

```html
<nav class="hidden md:block"> <!-- hide on mobile / render on medium up -->
<nav class="md:hidden"> <!-- render on mobile / hide on medium up -->
``` 

> Note: `.invisible` will still render the DOM space required for the navigation, but the navigation itself will be hidden. 

The [menu-toggle-blade.php](https://github.com/tightenco/jigsaw-docs-template/blob/13e3cbf54c87552934460b4c110ab7346855dcda/source/_nav/menu-toggle.blade.php) file is what toggles the visibility of the lefthand navigation on the docs template.
