### ISSUE TITLE
Bug new sitemap generator

### ISSUE THREAD

**Issue by SHOCKStudio** [tightenco/jigsaw#360]
Hello, I've been thinking for a few good hours about starting a sitemap generator...
I tried according to the documentation (https://jigsaw.tighten.co/docs/event-listeners/) and this thread but it still doesn't work and throws a bug:

 ```
 DONE  Compiled successfully in 441ms                                                                                                                                                                                  3:25:40 PM
       Asset     Size    Chunks             Chunk Names
css/main.css  147 KiB  /js/main  [emitted]  /js/main   
 + 1 hidden assetPHP Fatal error:  Uncaught Error: Class 'App\Listeners\GenerateSitemap' not found in C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Events\EventBus.php:33    Stack trace:
#0 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\illuminate\support\Collection.php(475): TightenCo\Jigsaw\Events\EventBus->TightenCo\Jigsaw\Events\{closure}('App\\Listeners\\G...', 0)
#1 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Events\EventBus.php(35): Illuminate\Support\Collection->each(Object(Closure))#2 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Jigsaw.php(69): TightenCo\Jigsaw\Events\EventBus->fire('afterBuild', Object(TightenCo\Jigsaw\Jigsaw))       
#3 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Jigsaw.php(34): TightenCo\Jigsaw\Jigsaw->fire in C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Events\EventBus.php on line 33

[Browsersync] Reloading Browsers...
```

My files:
![Adnotacja 2019-07-16 152720](https://user-images.githubusercontent.com/26645762/61298308-4729a280-a7de-11e9-84ad-5405b13c051c.png)

_Originally posted by @SHOCKStudio in https://github.com/tightenco/jigsaw/issues/332#issuecomment-511815559_

**Comment by anthonyterrell** [comment]
Hi @SHOCKStudio , 

It looks like this error is the result of trying to build the npm assets. I noticed you initially commented on https://github.com/tightenco/jigsaw/issues/332. Have you tried running `composer dump-autoload` prior to running `npm run dev`?

**Comment by SHOCKStudio** [comment]
@anthonyterrell I tried running `composer dump-autolad` but not work
Add my project files listeners/GenerateSitemap.php, edit bootstrap.php and composer.json as on the attached screenshot. Then I started to run `npm run watch` and page build and active in browser but not create sitemap and show error

**Comment by SHOCKStudio** [comment]
Problem fixed:
Correct appearance and structure on the screenshot, the content of the files below
**Key elements highlighted**
Folder **listeners must be in the root directory** of the page, the same level as the config.php file.

Must install package sitemap:
`composer require samdark/sitemap `

![Adnotacja 2019-07-16 214459](https://user-images.githubusercontent.com/26645762/61324559-01d39800-a813-11e9-83ad-967ceb447b05.png)

_bootstrap.php_
```php
<?php

use TightenCo\Jigsaw\Jigsaw;

/** @var $container \Illuminate\Container\Container */
/** @var $events \TightenCo\Jigsaw\Events\EventBus */

/**
 * You can run custom code at different stages of the build process by
 * listening to the 'beforeBuild', 'afterCollections', and 'afterBuild' events.
 *
 * For example:
 *
 * $events->beforeBuild(function (Jigsaw $jigsaw) {
 *     // Your code here
 * });
 */
$events->afterBuild(App\Listeners\GenerateSitemap::class);
```

_composer.json_
```php
{
    "require": {
        "tightenco/jigsaw": "^1.3",
        "samdark/sitemap": "^2.2"
    },
    "autoload": {
        "psr-4": {
            "App\\Listeners\\": "listeners/"
        }
    }
}
```

_listeners/GenerateSitemap.php_
```php
<?php namespace App\Listeners;

use TightenCo\Jigsaw\Jigsaw;
use samdark\sitemap\Sitemap;

class GenerateSitemap
{
    public function handle(Jigsaw $jigsaw)
    {
        $baseUrl = $jigsaw->getConfig('baseUrl');
        $sitemap = new Sitemap($jigsaw->getDestinationPath() . '/sitemap.xml');

        collect($jigsaw->getOutputPaths())->each(function ($path) use ($baseUrl, $sitemap) {
            if (! $this->isAsset($path)) {
                $sitemap->addItem($baseUrl . $path, time(), Sitemap::DAILY);
            }
        });
        $sitemap->write();
    }
    public function isAsset($path)
    {
        return starts_with($path, '/assets');
    }
}
```

**Comment by anthonyterrell** [comment]
🎉I'm glad this was sorted out!

**Comment by SHOCKStudio** [comment]
Is it possible to set the item from the collection not to be generated for sitemap? Not typing "@extends('_layouts.master')" causes that there is no such subpage but in the sitemap we have empty main page e.g:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
 <url>
  <loc>http://localhost:3000/</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
 <url>
  <loc>http://localhost:3000/</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
 <url>
  <loc>http://localhost:3000/</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
 <url>
  <loc>http://localhost:3000/</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
 <url>
  <loc>http://localhost:3000/</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
 <url>
  <loc>http://localhost:3000/studio-programistyczne</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
 <url>
  <loc>http://localhost:3000</loc>
  <lastmod>2019-07-16T19:59:36+00:00</lastmod>
  <changefreq>daily</changefreq>
 </url>
</urlset>
```

**Comment by sir-red-dab** [comment]
I'm also trying to use the sitemap generator. I followed all the steps from the docs and yes I have `samdark/sitemap` installed. But when I try to run the `npm run production` or `npm run dev` or `npm run watch` the following errors keep popping up (also `composer dump-autoload` didn't work out as mentioned above):
```
The location must be a valid URL. You have specified: /about-us.
```

![afbeelding](https://user-images.githubusercontent.com/31503728/68257376-56ee2080-0033-11ea-86f2-086ad0809dd1.png)

Is there also a way that `.htaccess` is not generated, because I get the same error:
```
The location must be a valid URL. You have specified: /.htaccess.
```

**Comment by sir-red-dab** [comment]
I fixed the problem myself. Thanks though.

**Comment by mattstauffer** [comment]
@SHOCKStudio I just saw your latest note. Please feel free to open a new issue if you're still having that problem. Thanks!
