### ISSUE TITLE
Accessing config variables in config

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#361]
I know the wording there is a bit off.  Sorry.

I'm trying to use remote collections, but I don't want to have multiple config files with lots of duplicate setup code.

Basically, I do something like this in my config file for pages, posts, and a slew of other things...

```
return [
    'collections' => [
        'pages' => [
            'items' => function() {
                $profiles = json_decode(file_get_contents('http://example.com/api/pages);
                return collect($page)->map(function ($page) {
                    return [
                        'slug' => $page->slug,
                         ...
```

The problem I run into is that I have different api urls that I need to hit for production vs development.  However, I can't seem to find a way to set that url programatically so that it gets picked up when I run 

```./vendor/bin/jigsaw build <target>```

I know I can set up different config files, but that basically recreates the several hundred line config file just so the urls can change.  It also makes it a real PITA to make changes to both files any time something new comes up.

So, is there any way I can do this without duplicating gobs of config code?

**Comment by avr** [comment]
@cjf - did you ever get this sorted?  My solution is to move the fetching of remote collections out of config and into a "Listener" class.

For example, you can register your class in bootstrap.php like this: `$events->beforeBuild( RemoteCollections::class );`

And then your fetcher can use something like:

```
public function handle(Jigsaw $jigsaw)
{
    $this->jigsaw = $jigsaw;
    $this->buildPagesCollection();
}
```

The `buildPagesCollection` can use your environment to set the api urls.

**Comment by damiani** [comment]
As of v1.3.21, the callback used in `items` will receive the config array as a parameter, so you can add a top-level `api` key with your URL, and reference it as `$config['api']` inside the `items` callback:

```php
return [
    'collections' => [
        'pages' => [
            'items' => function ($config) {
                $profiles = json_decode(file_get_contents($config['api']);
                
                return collect($profiles)->map(function ($profiles) {
                    return [
                        'slug' => $profiles->slug,
                         ...
```

... then, specify different `api` values for local and production.
