### ISSUE TITLE
Treat remote collection items as blade.md files instead of md

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#362]
Right now, remote collection items are treated as straight markdown files.  For reasons, I need them treated as blade markdown files.  My hack it to change line 30 of CollectionRemoteItem.php to 

```        
return Arr::get($this->item, 'filename', $this->prefix . ($this->index + 1)) . '.blade.md'; 
```

as this forces the files to be processed as desired.

Can this be integrated as a permanent change or possibly added as a switch somewhere?

**Comment by zk433** [comment]
@cjf , @damiani 
If you are happy with this solution, could I implement the above change and submit a PR?

**Comment by damiani** [comment]
Yes please!
