### ISSUE TITLE
How to change date to other language?

### ISSUE THREAD

**Issue by nuno360** [tightenco/jigsaw#363]
I would like to change the dates to portuguese language?

How is the best way to do it?

**Comment by erdmenchen** [comment]
I just change  all occurrences of 
```php
        {{ $post->getDate()->format('F j, Y') }}
```

to 
```php
        @php
             setlocale(LC_TIME, 'de_DE'); 
             echo strftime('%e. %B, %Y', $post->getDate()->getTimestamp());
        @endphp
```

Not very pretty, but just works.

**Comment by damiani** [comment]
Are you referring to the blog template? If so, you can change the `getDate()` method in `config.php` to whatever you wish, so you can move `setlocale` there.
