### ISSUE TITLE
[Feature Request] Better collection organisation

### ISSUE THREAD

**Issue by knorthfield** [tightenco/jigsaw#365]
Unless I've missed something, currently collections need to be in the root of the source directory. Once you have more than a few collections it starts getting untidy. Is there scope for a solution? Here's a few ideas:

- _collections directory in source (I suppose anything in here could be automatically parsed as a collection without adding to config)
- Specify collection location in config (thought this might already exist but couldn't find anything in the docs)
- Have a _collection subdirectory (e.g. source/people/_collection). Currently I have source/people/ and source/_people directories, this duplication gets more & more untidy as we add sections to the site. (this would be covered by 2nd option so probably irrelevant)

**Comment by reynaldo22** [comment]
hey, assign me please
let me help you

**Comment by tao** [comment]
You can create and use a separate collections folder using the Event Listeners as a current solution.

The folder structure here is:
```
- collections (new)
- source 
- listeners
- tasks
- vendor
```


In `bootstrap.php` you can include the events:
```php
$events->beforeBuild([
    PushCollections::class,
]);

$events->afterBuild([
    ...
    PullCollections::class
]);
```

Make sure that PullCollections is the very last event.

The two events copy everything in the `collections` folder and place it in the `source` folder, and then at the end of the build they remove the collections to tidy up the `source` folder again.

```php
<?php

namespace App\Listeners;

use Illuminate\Filesystem\Filesystem;
use TightenCo\Jigsaw\Jigsaw;

class PushCollections
{
    protected $storage;

    public function __construct()
    {
        $this->storage = new Filesystem();
    }

    public function handle(Jigsaw $jigsaw)
    {
        // move the directories in collections folder to the source folder
        $directories = $this->storage->directories('collections');

        collect($directories)->each(function($dir) {
            $segments = explode('/', $dir, 2);
            $filename = $segments[1];

            $from = getcwd()."/{$dir}";
            $to = getcwd()."/source/{$filename}";

            $this->storage->copyDirectory($from, $to);
        });
    }
}
```

```php
<?php

namespace App\Listeners;

use Illuminate\Filesystem\Filesystem;
use TightenCo\Jigsaw\Jigsaw;

class PullCollections
{
    protected $storage;

    public function __construct()
    {
        $this->storage = new Filesystem();
    }

    public function handle(Jigsaw $jigsaw)
    {
        // clean up the collections in the source folder
        $directories = $this->storage->directories('collections');

        collect($directories)->each(function($dir) {
            $segments = explode('/', $dir, 2);
            $filename = $segments[1];

            $source = getcwd()."/source/{$filename}";

            $this->storage->deleteDirectory($source);
        });
    }
}
```

**Comment by damiani** [comment]
Merging with #448
