### ISSUE TITLE
[Feature Request] Create markdown file with a command line

### ISSUE THREAD

**Issue by satyakresna** [tightenco/jigsaw#366]
Hi there, thanks for creating this static site for Laravel. I have a plan to make a blog for my community using this static generator. So, anyone can clone the blog repo and contribute the content as long as they understand how to use PHP and Laravel. Normally, when I create a post using markdown, I use a manual way like ```right click and then create a new file``` or ```touch [filename.md]```. But, I get an empty file without content like this picture.

![screenshot-jigsaw tighten co-2019 08 08-10_08_15](https://user-images.githubusercontent.com/11099186/62670179-e0ef0480-b9c4-11e9-9b4c-c99e8f8c339c.png)

In another side, Hugo (another static generator using Golang) gives a command to create a file by using command ```hugo new path_directory/your_post.md``` and generate a new file with a 
specific content like this picture below.

![screenshot-gohugo io-2019 08 08-10_14_31](https://user-images.githubusercontent.com/11099186/62670304-5bb81f80-b9c5-11e9-88a1-92e827d05d8c.png)

My expectation is Jigsaw can provide that feature as Hugo does. I'm not sure that Jigsaw already provides this or not because in [this page](https://jigsaw.tighten.co/docs/content-markdown/) it doesn't provide a command to create a markdown file using command line.

**Comment by atymic** [comment]
I'd be happy to create a PR for this if the feature request is accepted. It would be easier that copy/pasting.

**Comment by damiani** [comment]
@atymic I would definitely welcome a PR for this.
