### ISSUE TITLE
Handling tags across multiple collection

### ISSUE THREAD

**Issue by chrisvidal** [tightenco/jigsaw#367]
Currently, I am having some categories handled in the `config.php`

```php
 'categories' => [
            'path' => '/categories/{filename}',
            'posts' => function ($page, $allPosts) {
                return $allPosts->filter(function ($post) use ($page) {
                    return (($post->published == true) && ($post->categories ? in_array($page->getFilename(), $post->categories, true) : false));
                });
            },
        ],
```

But I also need to handle tags across multiple collections, which posts, projects and logs.

How can we achieve this please?

**Comment by damiani** [comment]
You could merge each of the collections you want to include, when passing them to your `posts` helper. 

For example (changing the method name from `posts` to `entries` since you're no longer dealing with just posts):

```php
@foreach ($page->entries($posts->merge($projects)->merge($logs)) as $entry)
   ...
```
