### ISSUE TITLE
[IN PROGRESS] Replace build tasks with a Mix plugin

### ISSUE THREAD

**Issue by Log1x** [tightenco/jigsaw#368]
Hi.

I am currently working on a project and decided to take a break and write the Jigsaw build tasks into a [mix plugin](https://github.com/Log1x/laravel-mix-jigsaw).

I was curious if there was any interest in doing this in core? I think the end result is rather clean.

I'd gladly transfer ownership and/or contribute / help maintain a repository on tightenco's side & scrap mine.

**Comment by damiani** [comment]
🎉 I really like this idea; it would give us the the freedom to update the build tasks separately, and it really streamlines the config. I'd definitely take you up on your offer to put this under Tighten's namespace, and would also love if you continued contributing to it!

**Comment by Log1x** [comment]
Glad you like it!

I went ahead and added eslint rules just now to match Laravel Mix's core rules and cleaned up a few things.

Would you prefer to start a new repo and grant me access? We can probably restart the versioning to `1.0.0` as I had to bump it a few times as I stumbled across little things.

Also, is there any interest in using CircleCI for testing the linting? If so, I can add a config file. Otherwise, writing actual tests falls a little short being that we would need a Jigsaw environment with the bin to actually test– but I don't think that's necessary.

**Comment by damiani** [comment]
I think we're OK without CircleCI on this. I'll set up a new repo for this shortly.

**Comment by bakerkretzmar** [comment]
@Log1x thank you so much for this!

We've set up a repo at [tightenco/laravel-mix-jigsaw](https://github.com/tightenco/laravel-mix-jigsaw) and I made some updates and restarted the versioning to `1.0.0`. I'll PR this repo shortly to update Jigsaw to actually use this package—I've added you to that repo, would you be open to updating the `laravel-mix-jigsaw` npm package to point to it too?

**Comment by Log1x** [comment]
No problem.

I invited you to the npm package so you can transfer it to the tightenco org.

**Comment by bakerkretzmar** [comment]
Thanks! I see it in my account but I'm getting a 403 if I try to publish or do anything on the command line. I think you may need to add me as an owner, not just a collaborator?

`npm owner add bakerkretzmar` should do it.

**Comment by Log1x** [comment]
`npm owner add bakerkretzmar` is what I had done after adding you as a maintainer and then removed myself (so you could move it or do whatever with it) – so now I'm also getting a 403 myself. Oops.

I'll toss them an email.

**Comment by bakerkretzmar** [comment]
Looks like it's working now actually. Thanks!
