### ISSUE TITLE
Help: PWA with Workbox. Having issues with "Current page does not respond with 200 when offline"

### ISSUE THREAD

**Issue by pmochine** [tightenco/jigsaw#369]
I created a repository for you to download [here](https://github.com/pmochine/Workbox-Jigsaw-Test).

I really struggle to implement the Workbox Plugin with Webpack. I know this is not an issue for jigsaw itself, but I asked in StackOverflow and had no luck.

Is there someone who successfully installed the Workbox Plugin and got it to work, so the html files were cached?

It really feels a bit "hacky", but here are the current settings:

**_webpack.mix.js_**
```
mix.webpackConfig({
    plugins: [
        build.jigsaw,
        build.browserSync(),
        build.watch(['source/**/*.md', 'source/**/*.php', 'source/**/*.scss', '!source/**/_tmp/*']),
        new WorkboxPlugin.GenerateSW({
            // these options encourage the ServiceWorkers to get in there fast
            // and not allow any straggling "old" SWs to hang around
            clientsClaim: true,
            skipWaiting: true,
            swDest: '../../service-worker.js', // Need to move the service-worker to the root
        }),
    ],
    output: {
        publicPath: '/assets/build/', // fixes the output bug
    },
});
```

But the precaching-manifest does not save any *.htmls...
Thus I still get the error: 

![image](https://user-images.githubusercontent.com/25006691/63636124-7946e380-c66b-11e9-862c-3278695d1d34.png)

**Comment by damiani** [comment]
As you said, this doesn't seem like a Jigsaw issue, but a Workbox/Webpack one.

**Comment by GenieTim** [comment]
You can use the config option [`additionalManifestEntries`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#GenerateSW) to force-add your html (e.g.:
```
new GenerateSW({
            // these options encourage the ServiceWorkers to get in there fast
            // and not allow any straggling "old" SWs to hang around
            clientsClaim: true,
            skipWaiting: true,
            swDest: '../../service-worker.js', //Need to move the service-worker to the root
            additionalManifestEntries: [
                {
                    url: "index.html"
                }
            ]
}),
```
). This seems a bit ugly, admitedly, and might need some scripting to get a list of all urls you are generating, therefore leading to duplication between PHP & JavaScript code, but it works.
