### ISSUE TITLE
Add ability to hook into ViewFactory instance.

### ISSUE THREAD

**Issue by incraigulous** [tightenco/jigsaw#370]
I'm using Jigsaw in a package that provides both HTML and blade versions of email temples. The package uses blade hint paths e.g. `email:components::section`.  This works when importing as a package, because the hint path is registered by the package service provider. I also want to be able to publish HTML files, but the jigsaw built is failing because the hint path isn't registered. I am thinking of making a PR, but I wanted to check and see if there is already a way to add the hint path that I'm missing.

**Comment by incraigulous** [comment]
Anybody know if there is a way to do this, or should I make a PR?

**Comment by damiani** [comment]
No, Jigsaw doesn't support Blade hint paths/namespaces at the moment.

**Comment by incraigulous** [comment]
@damiani, I've just submitted a pull request with a config option added for this.
