### ISSUE TITLE
Could not find jigsaw

### ISSUE THREAD

**Issue by aw3some-dev** [tightenco/jigsaw#371]
A rather annoying problem, my jigsaw project was working fine one minute, the next I'm getting the error `Could not find jigsaw. Please install jigsaw either locally or globally` every time I run `npm run watch`. I can't even run jigsaw commands like` jigsaw build` or `jigsaw serve` because my system for some reason isn't detecting the jigsaw installation. Its actually a fresh installation. I've barely touched the project except for a few html modifications (I've just added some header tags, thats all)

**Comment by aw3some-dev** [comment]
I'm in m project directory, inside the vendor/bin directory. Yes I have run composer install. I couldn't have installed jigsaw without it. Jigsaw is installed locally in my project directory. My jigsaw site was working properly meaning both composer and jigsaw were working fine. Then I restart my computer and I start getting the error `Could not find jigsaw. Please install jigsaw either locally or globally`.

**Comment by jasonlbeggs** [comment]
Since you have Jigsaw installed locally, unless you have an alias set up, you should be running `./vendor/bin/jigsaw` instead of `jigsaw`.

**Comment by damiani** [comment]
Sounds like a path issue unique to this user, closing for now unless we get some further info.
