### ISSUE TITLE
Can't get past "additional dependencies must be installed" 

### ISSUE THREAD

**Issue by jszobody** [tightenco/jigsaw#373]
Completely fresh install:

```
mkdir jiggy && cd jiggy
composer require tightenco/jigsaw

npm install

./vendor/bin/jigsaw init
./vendor/bin/jigsaw build
```

So far everything looks great. I have a local build with a "hello world!" page. Npm installed dependencies and created a package-lock.json file.

But then I run `npm run dev` to compile assets and I get this:

```
 	Additional dependencies must be installed. This will only take a moment.

 	Running: npm install vue-template-compiler --save-dev --production=false

 	Okay, done. The following packages have been installed and saved to your package.json dependencies list:

 	- vue-template-compiler

 	Additional dependencies must be installed. This will only take a moment.

 	Running: npm install  --save-dev --production=false

 	Okay, done. The following packages have been installed and saved to your package.json dependencies list:

 	Finished. Please run Mix again.
```

Fine. I run `npm run dev` again, and get the nearly the same output (minus the `vue-template-compiler` part).

```

 	Additional dependencies must be installed. This will only take a moment.

 	Running: npm install  --save-dev --production=false

 	Okay, done. The following packages have been installed and saved to your package.json dependencies list:

 	Additional dependencies must be installed. This will only take a moment.

 	Running: npm install  --save-dev --production=false

 	Okay, done. The following packages have been installed and saved to your package.json dependencies list:

 	Finished. Please run Mix again.
```

I can't seem to get past this. I'm using latest NPM 6.11.3. 

I have not run any commands other than what I've shown here, and I haven't edited any files. Just trying to get the default `main.scss` to compile with mix.

**Comment by damiani** [comment]
Hmm, I'll take a look!

**Comment by damiani** [comment]
Seems to be a new and known issue with Laravel Mix (https://github.com/JeffreyWay/laravel-mix/issues/2216), I'll see if we can fix it on Jigsaw's end or if we need to wait for a fix in the Mix package.

**Comment by damiani** [comment]
@jszobody Mix has been updated to version 4.1.4, which fixes this issue. You can run `npm update` to pick up the Mix update, and then it should work as expected.

**Comment by jszobody** [comment]
Confirmed, thanks!
