### ISSUE TITLE
Alternative front matter dialect

### ISSUE THREAD

**Issue by lesichkovm** [tightenco/jigsaw#375]
Can we have alternative tag/json based front matter?

Using YAML for front matter breaks the build as autosave removes the leading spaces:
```
---
pagination:
  collection: resources
  perPage: 5
---
```

becomes after the Blade formatter executes:
```
---
pagination:
collection: resources
perPage: 5
---
```

JSON or XML tags would solve this, and probably even make more sense

**Comment by lesichkovm** [comment]
Example
```
---
{
    "pagination": {
        "collection": "resources"
        ''perPage'': ''5".
    }
}
---
```

**Comment by damiani** [comment]
This is already possible, using the alternative YAML syntax for mappings:

```
---
pagination: { collection: resources, perPage: 5 }
---
```

**Comment by lesichkovm** [comment]
I couldn't find it anywhere in the documentation

**Comment by lukebouch** [comment]
I'm having the same issue. I will try that.
