### ISSUE TITLE
[Feature] Allow installation to sub-directory of project

### ISSUE THREAD

**Issue by goodevilgenius** [tightenco/jigsaw#376]
I wanted to be able to use Jigsaw to generate documentation within an existing project that already uses Laravel libraries. But, obviously, I wouldn't want any current files to be overriden. I also didn't want to have a separate set of composer files and vendor directory, since my project already contained most of Jigsaw's needed dependencies.

But `jigsaw init` doesn't provide an option to install to a sub-directory, and if I manually created the sub-directory, `cd`ed into it, and did `jigsaw init` in there, I'd be duplicating libraries.

I think it would be really useful to be able to use it alongside an existing project in this fashion.

**Comment by damiani** [comment]
We get a lot of requests (https://github.com/tightenco/jigsaw/issues/374, and others in the past) for being able to run Jigsaw within a Laravel project, but I haven't had a chance to wrap my head around how we could pull that off or what conflicts we might encounter. 

This might be a good Hacktoberfest endeavor for a brave soul!

**Comment by stevebauman** [comment]
Maybe it's possible to publish Jigsaw's builds *into* your Laravel project? Haven't tried this yet myself though...

**Comment by goodevilgenius** [comment]
@stevebauman I'm no longer working on that project, and we ended up deciding not to use jigsaw because of this limitation.

**Comment by damiani** [comment]
At this point, Jigsaw is intended to be used as a standalone static site generator, not integrated into a Laravel project.
