### ISSUE TITLE
[Proposal] Support AMP HTML output

### ISSUE THREAD

**Issue by ronlobo** [tightenco/jigsaw#38]
https://www.ampproject.org/

**Comment by mattstauffer** [comment]
@ronlobo I've only read up on AMP a little bit. What would need to change about Jigsaw in order for this to happen?

Thanks!

**Comment by mattstauffer** [comment]
@ronlobo Ping--any thoughts here? Will close if I don't hear back. Thanks!

**Comment by ronlobo** [comment]
@mattstauffer sry for the late reply. Actually this is totally up to how users setup their blade templates, thus closing it.

**Comment by m1guelpf** [comment]
I've started researching on AMP again, to make it work you'd need to render two views for each content (a `_layouts.post` and a `_layouts.amp`). Is this currently possible?

**Comment by damiani** [comment]
@m1guelpf Yes, you can do this for collection items. Check out the "Collection items with multiple parent templates" section of the [docs](https://jigsaw.tighten.co/docs/collections-extending-parent-templates/); your markdown file would start with something like this:

```md
---
extends:
  web: _layouts.post
  amp: _layouts.amp
section: content
---
```
