### ISSUE TITLE
What would be the correct way to load and use blade templates from a composer library?

### ISSUE THREAD

**Issue by psymeon** [tightenco/jigsaw#380]
We are looking to build a composer library which will consist of blade components that we can reuse among different jigsaw projects.

My questions are:

- Is this something doable in the current version of jigsaw?
- If yes, what would be the correct way of doing this?

Any suggestions towards the right direction would be really appreciated.

Thanks

**Comment by xy2z** [comment]
You could probably add a function that copies files from the vendor directory to source, in the beforeBuild method, see https://jigsaw.tighten.co/docs/event-listeners/#vue-app

You could also consider using git submodules

**Comment by damiani** [comment]
We just tagged a version today (v1.3.15) that allows you to specify a hint path for Blade files, which might be a good way to do this. You should be able to point to the library's directory in `vendor` and then refer to the components using a namespace; check out [the docs](https://jigsaw.tighten.co/docs/content-blade/#specifying-blade-hint-paths) for the syntax on how to use `viewHintPaths` in `config.php`.
