### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by IANirab** [tightenco/jigsaw#383]
I found this warning in console warning when i submit email newsletter .

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://000webhostapp.us19.list-manage.com/subscribe?u=1734596026f52625a59cc6369&id=3e5623d927&c=jQuery19005659933434405229_1570828623751&EMAIL=project%40gmail.com&b_25582686a9fc051afd5453557_189578c854=&subscribe=Subscribe&_=1570828623752 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by damiani** [comment]
This isn't really a Jigsaw issue, but a Mailchimp one. Are you using the [Jigsaw Blog template](https://github.com/tightenco/jigsaw-blog-template)? If so, could you move your issue to that repo and see if others have encountered it, and post some more details about the Mailchimp code you're using?
