### ISSUE TITLE
Documentation ahead of production build

### ISSUE THREAD

**Issue by kurucu** [tightenco/jigsaw#385]
I have spent the last few hours pulling my hair out over filtering.

It turns out that Jigsaw 1.3.12 has a beta dependency, so composer wasn't pulling it and I didn't notice until I gave up thinking "it's like Jigsaw just doesn't have this functionality".

I don't know what the appropriate answer is - I've allowed dev stability in composer and preferred stable - but you might prefer to mark up the documentation or change the jigsaw dependency.

The offending dependency is `erusev/parsedown`.

**Comment by tao** [comment]
I encountered this when I tried to use the new `helpers.php` functionality that was recently added.

I had to update my composer file to include:
```json
  "minimum-stability": "beta",
  "prefer-stable": true,
```

The problem it seems is that `erusev/parsedown` and `erusev/parsedown-extra` haven't been updated since March '19 and May '18.

**Comment by damiani** [comment]
Yeah, looks like `composer require tightenco/jigsaw` won't pull in beta packages unless `minimum-stability` is added directly to the local `composer.json` file, which defeats the purpose of a simple one-line install. 😞 

Working on a fix, that might involve rolling back to the stable `1.7.3`, or even dropping Parsedown in favor of a different parser, if it looks like `1.8.0-beta` isn't going to make it out of beta anytime soon.

**Comment by damiani** [comment]
I've tagged a new release, v1.3.14 (https://github.com/tightenco/jigsaw/pull/388) that should resolve this problem for new Jigsaw installs, removing the reliance on `beta` versions of Parsedown and Parsedown Extra.
