### ISSUE TITLE
Remote content for pages

### ISSUE THREAD

**Issue by ChrisButterworth** [tightenco/jigsaw#386]
Looking for a way to integrate Jigsaw with a CMS to create and manage the content but can't seem to find a way of creating pages using remote content - all the documentation and examples given use collections and not pages.

Any guidance?

**Comment by damiani** [comment]
For adding remote content to a regular (non-collection) page, the principle is the same as described in the docs, but you can do it directly in your Blade template:

```php
<p>{{ json_decode(file_get_contents('https://jsonplaceholder.typicode.com/posts/1'))->body }}</p>
```

... or, you can move that to `config.php` and reference it as a variable in your page: 

```php
// config.php
'remoteContent' => json_decode(file_get_contents('https://jsonplaceholder.typicode.com/posts/1')),

// page.blade.php
<p>{{ $page->remoteContent->body }}</p>
```

... or, you could use a helper function in `config.php`:

```php
// config.php
'getRemoteContent' => function ($page, $path) {
    return json_decode(file_get_contents('https://jsonplaceholder.typicode.com/' . trim($path, '/')));
},

// page.blade.php
<h2>{{ $page->getRemoteContent('posts/2')->title }}</h2>
```

If you need to do this on a Markdown page, use the `.blade.md` extension and you'll be able to echo the remote content as shown above.
