### ISSUE TITLE
Installing Jigsaw on Windows 10

### ISSUE THREAD

**Issue by sir-red-dab** [tightenco/jigsaw#390]
I'm trying to install Jigsaw locally. I followed these steps form the docs:
`mkdir my-site`
`cd my-site`
`$ composer require tightenco/jigsaw`

When I try to initialize the project with the following command:
`./vendor/bin/jigsaw init`

I get the following error:
> '.' is not recognized as an internal or external command, operable program or batch file.

I tried also the following command:
`cd vendor/bin`
`jigsaw init`

But then I get the following error:
> Fatal error: Uncaught Error: Class 'Illuminate\Container\Container' not found in <path>\vendor\tightenco\jigsaw\jigsaw-core.php:55
Stack trace:
#0 <path>\vendor\tightenco\jigsaw\jigsaw(8): require_once()
#1 {main}
  thrown in <path>\vendor\tightenco\jigsaw\jigsaw-core.php on line 55

Is there a way I can get this framework installed?
Maybe there's a better way to install the framework in the future, without two seperate composer/install commands?

**Comment by damiani** [comment]
If you're not using the Linux shell, I believe the init command would be:

```
vendor\bin\jigsaw init
```

Give that a shot!

**Comment by sir-red-dab** [comment]
Thanks for the reply, it worked!
