### ISSUE TITLE
Getting an error upon Jigsaw init

### ISSUE THREAD

**Issue by ithardeep** [tightenco/jigsaw#395]
I am trying to install Jigsaw on windows 8, I followed exact steps as mentioned on your website but getting an error please see

And PHP version I am using is 7.4

B:\hardeep work\Bcanotes\vendor\bin>jigsaw init
PHP Fatal error: Uncaught Error: Class 'Illuminate\Container\Container' not found in B:\hardeep work\Bcanotes\vendor\tightenco\jigsaw\jigsaw-core.php:55
Stack trace:
#0 B:\hardeep work\Bcanotes\vendor\tightenco\jigsaw\jigsaw(8): require_once()
#1 {main}
thrown in B:\hardeep work\Bcanotes\vendor\tightenco\jigsaw\jigsaw-core.php on line 55

**Comment by ithardeep** [comment]
I found this post
https://github.com/tightenco/jigsaw/issues/390

And I followed the same steps and it works, however, I have to use vendor\bin\jigsaw init
vendor\bin\jigsaw build
vendor\bin\jigsaw serve 
from the directory I installed jigsaw.

and when I try to execute commands under bin folder like
jigsaw build
jigsaw server

I am getting above error 
 Uncaught Error: Class 'Illuminate\Container\Container' 

Could you please explain what I am missing?

**Comment by josecanhelp** [comment]
Jigsaw core will look for an autoload file relative to where the command is run. If you run the command _from_ the bin file, it will not find the autoload file and the required classes will not be loaded. However, if you run the `vendor/bin/jigsaw` _from_ your project root, it will work.

We recommend running jigsaw from the project root using `vendor/bin/jigsaw`.

**Comment by ithardeep** [comment]
Did you update the code, I am asking because a year ago I had installed jigsaw and I was executing commands under bin folder since it is very convenient to use short commands.

Is there any way to use commands under bin folder?

**Comment by josecanhelp** [comment]
If you add the `vendor/bin` directory to your PATH environment variable, you should be able to run `jigsaw` without prefacing the `vendor/bin` path every time.
