### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by stevebauman** [tightenco/jigsaw#396]
I had to create an issue here to tell you how much I honestly love using Jigsaw. After I discovered it, I converted a full Laravel application to Jigsaw in about an hour using your docs template, and I'm blown away by the results.

Thanks so much for putting so much time and effort into this! :heart: :smile:

If you're wondering, the website I built is https://ldaprecord.com

**Comment by damiani** [comment]
This is my new favorite issue. Thanks for the kind words, @stevebauman! ❤️
