### ISSUE TITLE
Extending the same layout in two partials show only first include sections values

### ISSUE THREAD

**Issue by cristiangervasi** [tightenco/jigsaw#397]
Hi, i have a number of partials that extend a certain layout.
When i include those partials in a page, only the first included partial's sections values are taken and repeated on every other partials even if i declare other values. I tried with @overwrite ending all sections but then there is a problem when i don't want to declare any value for an optional @yield.
Is there a way to disable this "cache" behaviour?

**Comment by damiani** [comment]
This is standard Blade behavior in Laravel; `@overwrite` is the only way I am aware of where you can include multiple sub-views that all `@extend` the same parent and which reference the same `@section` reference. I would consider using components and slots instead of `@extend`.
