### ISSUE TITLE
Compile blade file to .php instead of .html

### ISSUE THREAD

**Issue by sir-red-dab** [tightenco/jigsaw#399]
I want to compile a blade to `.php` instead of `.html`.  I use PHPMailer to send emails and I want to use `Session_start ()` to tell the `contact.blade.php` if the mail has been sent or if an error has occurred.

How can I achieve this?

**Comment by josecanhelp** [comment]
@sir-red-dab the idea behind Jigsaw is to create a static website that can be hosted on simple hosting services like Github Pages and Netlify. If Jigsaw started generating PHP files and requiring users to host those, it would not be a static website and would not be able to be hosted on those platforms.
