### ISSUE TITLE
Generate paths to css and other assets automatically

### ISSUE THREAD

**Issue by dreamxcape** [tightenco/jigsaw#40]
When the build is generated, if I have second-level pages (for example: about-us/index.html) the header css files in this about-us index file still have the standard path and are not appended with a ../. Is this the default behaviour? How do I call in the css files in second-levels of the site?

I tried to use something like {{ asset('css/app.css') }}, but it doesn't work.

**Comment by adamwathan** [comment]
Hey @dreamxcape, at the moment I recommend using absolute URLs for your assets, not relative.

If you know your site will always be deployed at the root of wherever you're serving it, just prefix the asset path with a forward slash:

`<link href="/css/main.css" rel="stylesheet" />`

That will work no matter what level the page is at.

**Comment by dreamxcape** [comment]
@adamwathan Thanks for that Adam!
