### ISSUE TITLE
Are tasks/build.js meant to be edited?

### ISSUE THREAD

**Issue by amadeann** [tightenco/jigsaw#402]
I wanted to customize the `startPath` in Browser Sync, and the only way to do it I found was to add `startPath: '/en/'` setting directly to the `tasks/build.js` file. 

Is this file meant to be edited, or is it considered a part of Jigsaw and may be updated/brought back to default with the new version of the package?

**Comment by damiani** [comment]
The webpack build-related files are definitely open to editing, including those in the `tasks` directory. We've set them up to handle the most common build setups, but feel free to modify them if needed.

When updating Jigsaw via Composer, only the files in `vendor/tightenco/jigsaw` are modified. In future versions, if changes are made to the default installation files (such as `webpack.mix.js` or `config.php`), those changes would be noted in the upgrade notes in the documentation.
