### ISSUE TITLE
How to copy file after Jigsaw built is complete?

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#404]
- I'm using the Github Pages deployment strategy from [Jigsaw's documentation](https://jigsaw.tighten.co/docs/deploying-your-site/#vue-app)
- As I'm using an apex domain (`martinbetz.eu`) and no subdomain (`githubpages.martinbetz.eu`), I need to have a `CNAME` in my `build_production` folder or I would get git issues when pushing (I'm not doing pull requests for the static site)
- That's why I want to copy it from my `source` or root Jigsaw folder after the page was built with `npm run production`
- I tried to add `mix.copy('CNAME', 'build_production/CNAME');` to the `webpack.mix.js`, but that does not work
- When I change the copy directory to something else (say: `mix.copy('CNAME', 'test/CNAME');`, it works
- This might mean that the building process comes after Webpacks build script

How can I copy the `CNAME` safely after Jigsaw's built is done?

**Comment by josecanhelp** [comment]
You can try using Jigsaw's build [event listeners](https://jigsaw.tighten.co/docs/event-listeners/). If you have a file called `CNAME` in your project root, you can use the following lines of code in your `bootstrap.php` file:

```php
$events->afterBuild(function ($jigsaw) {
    if($jigsaw->getEnvironment() === 'production') {
        $jigsaw->writeOutputFile('CNAME', $jigsaw->getFilesystem()->get('CNAME'));
    }
});
```

**Comment by minthemiddle** [comment]
Yes, that's solves it.

**Comment by minthemiddle** [comment]
🤦🏼‍♂️ Or even simpler: Just copy `CNAME` to `source/CNAME` and let the build system do the heavy-lifting…
