### ISSUE TITLE
[Proposal] Add support for active links.

### ISSUE THREAD

**Issue by iolson** [tightenco/jigsaw#41]
Add support for navigations to be able to display a class based on if the href is equal to the current page. This solution would be best in blade and markdown flavors.

**Comment by nerdmediallc** [comment]
This is a duplicate of #19

**Comment by iolson** [comment]
My fault. I will close.

**Comment by nerdmediallc** [comment]
I've updated #19 with a way to do it. It's not a pretty solution but it works.
