### ISSUE TITLE
Build time syntax highlighting

### ISSUE THREAD

**Issue by ghost** [tightenco/jigsaw#410]
Currently it looks like Jigsaw only offers runtime highlighting:

> Syntax highlighting using highlight.js

https://jigsaw.tighten.co/docs/starter-templates

Other projects offer build time highlighting. For example Hugo uses the Go Chroma library for highlighting:

https://gohugo.io/content-management/syntax-highlighting

Can Jigsaw do something like this?

**Comment by cup** [comment]
I found this:

https://github.com/scrivo/highlight.php

**Comment by damiani** [comment]
Jigsaw doesn't offer any syntax highlighting at all out of the box, but the [Docs template](https://github.com/tightenco/jigsaw-docs-template) does use client-side highlighting. The recent markdown parser change, and recent updates to v1.3.18, would make this pretty easy to add, by hooking into the parser's `code_block_content_func` setting.

- Add the library you mention, with:

`composer require scrivo/highlight.php`

- In `bootstrap.php`, add:

```php
$container['markdownParser']->code_block_content_func = function ($code, $language) {
    return '@verbatim' .
        highlightCode(removeEscapeCharacters($code), $language) .
        '@endverbatim';
};

function highlightCode($code, $language)
{
    return (new Highlight\Highlighter)->highlight($language ?: 'php', $code)->value;
}

function removeEscapeCharacters($code)
{
    return strtr($code, [
        "<{{'?php'}}" => '<?php',
        "{{'@'}}" => '@',
        '@{{' => '{{',
        '@{!!' => '{!!',
    ]);
}
```

If you think this would be a worthy addition to the Docs template, please open an issue in [that repo](https://github.com/tightenco/jigsaw-docs-template) and we can explore it further.
