### ISSUE TITLE
Retrieving all pages

### ISSUE THREAD

**Issue by luthfiampas** [tightenco/jigsaw#411]
In this situation, my event listener needs to access `getModifiedTime()` method from each page to assign `lastmod` value in my generated sitemap.

As far as I know, in this case, we can only iterate pages that are living inside a collection. Is there a way to retrieve all pages (_including index page or any other pages located inside root source directory_)?

Here's my current solution, almost the same as https://github.com/tightenco/jigsaw-blog-template/blob/master/listeners/GenerateSitemap.php

### Sitemap for all collections
```php
foreach ($jigsaw->getCollections() as $collection) {
    collect($collection)->each(function ($page) use ($baseUrl, $sitemap) {
        $sitemap->addItem(rtrim($baseUrl, '/') . $page->getPath(), $page->getModifiedTime(), Sitemap::DAILY);
    });
}
```

### Sitemap only for the pages located inside the root source directory
```php
collect($jigsaw->getOutputPaths())->reject(function ($path) {
   
   // exclude collection..
   // collection path always set to /{collection name}/name
   return count(explode("/", trim($path, '/'))) > 1 || Str::is($this->exclusions, $path);

})->each(function ($path) use ($baseUrl, $jigsaw, $sitemap) {

   // get the source path
    $sourcePath = empty(trim($path, '/')) 
          ? $jigsaw->getSourcePath() . $path . "/index.blade.php" 
	  : $jigsaw->getSourcePath() . $path . ".blade.php";

   // i'm on Windows
    $sourcePath = str_replace('\\', '/', $sourcePath);

   // use php filemtime
    $sitemap->addItem(rtrim($baseUrl, '/') . $path, filemtime($sourcePath), Sitemap::DAILY);
});
```

Please tell me if there any better way to do this 😃

**Comment by damiani** [comment]
I just added a `getSourceFileInfo()` method to v1.3.19 (it effectively replaces `getOutputPaths()`), which will give you a collection containing the `SplFileInfo` for the source file of every built page. From there, you can check the `getMTime()` for each file. (See the PR https://github.com/tightenco/jigsaw/pull/429, or [the updated docs](https://jigsaw.tighten.co/docs/event-listeners/#helper-methods-in-$jigsaw), for details.)

**Comment by chrisvidal** [comment]
@luthfiampas Im trying to achieve the same, as in, properly set the sitemap time for new blog post without changing the time for static pages. Did you manage to do it please ?

**Comment by luthfiampas** [comment]
@chrisvidal I utilized the `getPages()` and `getModifiedTime()`, I'm not sure if this is what you meant, but here's my old code snippet

```php
<?php

namespace App\Listeners;

use samdark\sitemap\Sitemap;
use TightenCo\Jigsaw\Jigsaw;
use Illuminate\Support\Str;

class GenerateSitemap
{
    protected $exclude = [
        '/assets/*',
        '*/favicon.ico',
        '*/404*'
    ];

    public function handle(Jigsaw $jigsaw)
    {
        $baseUrl = $jigsaw->getConfig('baseUrl');

        if (!$baseUrl) {
            echo ("\nTo generate a sitemap.xml file, please specify a 'baseUrl' in config.php.\n\n");
            return;
        }

        $sitemap = new Sitemap($jigsaw->getDestinationPath() . '/sitemap.xml');

        collect($jigsaw->getPages())
            ->reject(function ($page) {
                return $this->isExcluded($this->normalizePath($page));
            })->each(function ($page) use ($baseUrl, $sitemap) {
                $url = rtrim($baseUrl, '/') . $this->normalizePath($page);
                $sitemap->addItem($url, $page->getModifiedTime(), Sitemap::DAILY);
            });

        $sitemap->write();
    }

    public function normalizePath($page)
    {
        return str_replace('\\', '/', $page->getPath());
    }

    public function isExcluded($path)
    {
        return Str::is($this->exclude, $path);
    }
}

```
