### ISSUE TITLE
Can't parse md, if 'date' key holds time

### ISSUE THREAD

**Issue by Jampire** [tightenco/jigsaw#412]
Hi. Jigsaw can't parse markdowm file if 'date' YAML key consists of time. For example, such key
`date: 2020-01-24 23:24`
generates an error:
`Call to a member function format() on boolean`

**Comment by nhedger** [comment]
Hi,

After a bit of investigation, it appears that this is related to the fact that the YAML parsing library used by this package (`symfony/yaml`) will try to automatically convert dates and datetimes to timestamps but in your case it fails detecting the string as a valid datetime and returns a simple string instead.

For the parser to recognize the string as a date or datetime, it must follow the ISO8601 format. Following dates and times are valid an correctly detected:

- `2020-02-02`
- `2020-02-27T19:05:06.0Z`

Cheers.
