### ISSUE TITLE
Need Help to configure access to dabatase

### ISSUE THREAD

**Issue by mulp** [tightenco/jigsaw#414]
Is there a way to configure the starter project to be able to use the Laravel Facade DB and so access to a mysql database?

I need to generate the content of the templates in a beforeBuild event. I was able to make it work but in my Class Listener I need to get some data from db and make them available to the blade templates. 

Is there a way to do that?

Thanks in advance.

**Comment by stevebauman** [comment]
No there isn't. You'd have to set this up on your own. Jigsaw is a completely static site generator - it's not meant to be used with databases at all.

Blade is really the only feature that is carried over here - you can see in the `composer.json` of what Laravel components are in use:

```
    "require": {
        "erusev/parsedown-extra": "^0.8",
        "erusev/parsedown": "^1.7",
        "illuminate/container": "^5.8",
        "illuminate/support": "^5.8",
        "illuminate/view": "^5.8",
        "mnapoli/front-yaml": "^1.5",
        "mockery/mockery": "^1.0.0",
        "php": "^7.1.3",
        "symfony/console": "~3.0|^4.0",
        "symfony/process": "~3.0|^4.0",
        "symfony/var-dumper": "^4.0",
        "symfony/yaml": "^4.0",
        "vlucas/phpdotenv": "^3.3"
    },
    "require-dev": {
        "mikey179/vfsstream": "^1.6",
        "phpunit/phpunit": "~7.0",
        "friendsofphp/php-cs-fixer": "^2.12"
    },
```
