### ISSUE TITLE
Blog article: How to deploy Jigsaw to Github Pages

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/jigsaw#415]
I wrote an article on how to deploy to Github Pages that is a bit more detailed than the current Jigsaw docs. Maybe it helps someone:

https://martinbetz.eu/articles/jigsaw-github-pages/

**Comment by stevebauman** [comment]
Hi @minthemiddle! Your link is 404'ing.

I think you should close this as it isn't an issue. If someone searches for it in the GitHub issues index they would find it.

**Comment by mattstauffer** [comment]
@minthemiddle Thanks! If you end up re-publishing that, https://github.com/tightenco/builtwithjigsaw would be a great spot for it since we have an articles list there. Thanks!

**Comment by minthemiddle** [comment]
@mattstauffer Oh, 

> Hi @minthemiddle! Your link is 404'ing.
> 
> I think you should close this as it isn't an issue. If someone searches for it in the GitHub issues index they would find it.

Oh, I somehow unpublished it. Will republish…

**Comment by minthemiddle** [comment]
@stevebauman Sorry, is up again. Did not rebase my `gh-pages` on the second machine and undeliberately unpublished the post with it.

**Comment by stevebauman** [comment]
Great! Glad you got it up and running now :smile:
