### ISSUE TITLE
Debugging Jigsaw is difficult

### ISSUE THREAD

**Issue by stevebauman** [tightenco/jigsaw#417]
While trying to resolve my own issues (#413), I found that debugging Jigsaw is extremely difficult without any code docs informing me what the method does or what the variables for the methods are supposed to contain.

I basically have been modifying the vendor files, adding `dd()` to variables, run the build process and see what the value of the argument is. This is tedious and very time consuming.

I can write a PR to add code docs to all the methods and not touch the actual code as to leave all tests and functionality the same, but I wan't to make sure it's something that has a possibility of being accepted before I dive into the work.

This is similar to #299 and #281, but without any opinionated nature on type-hints or return types.

Would love to hear any honest opinions, thanks!

**Comment by mattstauffer** [comment]
@stevebauman Thanks! We certainly want it to be easier to debug.

Would you mind explaining briefly why adding doc blocks would make it easier to debug? This is an honest question--at Tighten, as I'm sure you can see from this codebase, we tend to be very minimal in our usage of doc blocks in internal projects, but we're trying to make sure that that doesn't have a negative impact on our open source work, so this is a good and timely conversation.

Thanks!

**Comment by stevebauman** [comment]
Hi @mattstauffer! Appreciate the response.

Docblocks allow me to scan the code and know immediately what variables and arguments are objects, strings, integers and more. It also gives PHPStorm the ability to auto-complete when I'm debugging the code, rather than go into each and every file and have to manually scan the files to see what methods are public or protected.

For example, the core `Jigsaw` classes constructor:

```php
public function __construct($app, $dataLoader, $remoteItemLoader, $siteBuilder)
{
    $this->app = $app;
    $this->dataLoader = $dataLoader;
    $this->remoteItemLoader = $remoteItemLoader;
    $this->siteBuilder = $siteBuilder;
}
```

What is `$app`, `$dataLoader`, `$remoteLoader` and `$siteBuilder`? Looking upon the class, I have no idea, they are just plain arguments. Now take a look at this example below:

```php
/**
 * Jigsaw constructor.
 *
 * @param \Illuminate\Contracts\Container\Container             $app
 * @param \TightenCo\Jigsaw\Loaders\DataLoader                  $dataLoader
 * @param \TightenCo\Jigsaw\Loaders\CollectionRemoteItemLoader  $remoteItemLoader
 * @param \TightenCo\Jigsaw\SideBuilder                         $siteBuilder
 */
public function __construct($app, $dataLoader, $remoteItemLoader, $siteBuilder)
{
    $this->app = $app;
    $this->dataLoader = $dataLoader;
    $this->remoteItemLoader = $remoteItemLoader;
    $this->siteBuilder = $siteBuilder;
}
```

Now, it is immediately clear what the arguments are instances of and what the constructor requires.

Now when I debug, I get:

- IDE Auto-completion
- I know exactly what variables are
- I know the public API that each object contains
- I can CTRL+Click into each class to open the file automatically

This brings clarity, speed, efficiency, and without these on any methods I have to *guess* what they may be instances of.

What is the `$remoteDataLoader` an instance of? I can take a wild guess after digging through the source and *assume* it's an instance of `TightenCo\Jigsaw\Loaders\CollectionRemoteItemLoader` (and I actually had to spend time to dig into folders to see if that was truly the case).

This becomes harder when class methods come into play and they return values. I have to dig into each classes API and see what is returned (if anything is even being returned) - or worse use `dd()` everywhere and see what gets dumped.

Since you are the creators of Jigsaw, you will immediately know what most of these arguments, variables and methods contain / return - but contributors will have no idea (myself included).

I absolutely love Jigsaw - it's fantastic. I hope this doesn't come off in any certain way, I'm only looking for easier debugging :heart: :smile:

**Comment by stevebauman** [comment]
For another small example, the `write` method in the `CollectionRemoteItemLoader`:

```php
public function write($collections, $source)
{
    collect($collections)->each(function ($collection, $collectionName) use ($source) {
        $items = $this->getItems($collection);

        if (collect($items)->count()) {
            $this->writeTempFiles($items, $this->createTempDirectory($source, $collectionName), $collectionName);
        }
    });
}
```

Immediately looking, what does this return? Well, I have to scan the entire method to find out. Rather than having a docblock indicating that it actually returns nothing. It would be *super* helpful to have a small descriptor of what the method does as well:

```php
/**
 * Iterates through the collections and writes temporary files.
 *
 * @param \TightenCo\Jigsaw\IterableObject $collections
 * @param string                                              $source
 * 
 * @return void
 */
public function write($collections, $source)
{
    // ...
```

Now I know immediately what it does, and that it doesn't actually return anything.

**Comment by mattstauffer** [comment]
@stevebauman Thanks for the examples!

I can say *for sure* that we're happy to take any PR adding type hints when appropriate.

We're still on the fence about doc blocks and return type hints. Not saying they're "no" but just that we may be better off handling them in separate PRs.

Is that something you're interested in being a part of?

Thanks!!

**Comment by stevebauman** [comment]
No problem @mattstauffer!

I honestly thought you'd prefer to have docblocks only as it doesn't change the actual code base - only adding information to it.

I'd definitely be interested in adding docblocks and type-hints (don't like return types), but I don't know Tighten's code style and where exactly you want them and where you don't. Investing that time without that knowledge and then having the PR shutdown would deter me from trying to send further PRs.

Is there a style guide you have at Tighten that contributors can follow to give (me and) them confidence that they are writing code adhering to your specifications?

**Comment by mattstauffer** [comment]
@stevebauman If you're OK with it, I'd say: let's start with type hints on any classes where it's clear only one thing will get passed in. 

#299 and #281 introduced new interfaces, return type hints, and other stuff that was a bit beyond what we were ready to introduce at that point. But type-hints-as-documentation is something we're definitely warming up to.

Is that enough clarity for now? Basically, I literally mean type hints on the constructors. If each class defines its expected constructor injections in a way that doesn't keep us from modifying things in the future (e.g. the dreaded type hinting an array when later you realize you want a traversable), that's a big step forward imho.

**Comment by stevebauman** [comment]
I guess type-hints on constructors is a start. I'm am curious however on your opinion on docblocks (if you've got a minute).

In my own "programming come-up" it's been drilled into my skull over the years that docblocks are basically mandatory. I'm not saying my way is right or correct, but I'd love to hear your thoughts on why they shouldn't be added and what exactly benefits the code base from having them omitted?

Thanks for all your time @mattstauffer!

**Comment by mattstauffer** [comment]
I tend to hate doc blocks, because they seldom provide value but they frequently get out of sync.

On a stable open source project those things are both less likely to be the case. Descriptions are more helpful, and things move more slowly, and there are more eyes noticing drift. Which is why I'm becoming open to them as a possibility.

But they're *anything* but mandatory. In my mind, doc blocks across the programming community and the code bases I've had to review have done more damage than good. If even 1+% of your doc blocks are out of sync, which seems to be extraordinarily common, then every doc block is untrustworthy. Further, seldom do doc blocks do anything other than reiterating what a good method name, well-named parameters, and possibly type-hinted parameters could do.

My general rule is: Add a docblock if you need to describe something that can't be easily inferred from the code.

**Comment by stevebauman** [comment]
Thanks for sharing your thoughts! I definitely have the opposite belief, so I will definitely agree to disagree. :heart:

I'll get some time this Sunday and add some of those type-hints to the constructors.

**Comment by mattstauffer** [comment]
@stevebauman :) Honestly, I can't even agree to disagree, because while the statement I made above is true, I deeply appreciate Laravel's doc blocks and think they should be there. I think my perspective has matured to the point that I'm leaning toward considering revising my take and saying "Doc blocks are appropriate everywhere in open source". I'm not 100% there yet but I feel I might be soon. :)

**Comment by stevebauman** [comment]
Understandable! I'm trying to keep an open perspective as well, but honestly I haven't done any code reviews (no one reviews my code where I work and vice-versa). If I was bitten by them, I can absolutely understand that they can cause harm.

Since I haven't experienced the challenges you have faced, my perspective is so different. I really enjoy getting experienced developers views on these things though, as it will only help me improve my own style 👍 :smile:
