### ISSUE TITLE
Elixir : copy images

### ISSUE THREAD

**Issue by chrisvidal** [tightenco/jigsaw#42]
Im trying to copy some images from the _assets folder to the build_local folder with this in the gulp.s

`.copy(elixir.config.assetsPath + "/img", "build_local/img") // to perform after the jigsaw build`

with the command gulp, it wokrs fine
however with the command gulp watch, the copied folder is always removed.

Any ideas please ?

**Comment by adamwathan** [comment]
Hey @chrisvidal, you don't need to use Gulp at all for this, Jigsaw copies all of your files to build_local when it builds the site.

Instead, just put your images inside `source/img` and you're done! Like we do here:

https://github.com/tightenco/jigsaw-site/tree/master/source

The only stuff that needs to go in `_assets` is stuff that needs to be pre-processed, like less/sass/coffeescript/etc. Any other normal files are just copied over automatically as part of the build process.

**Comment by chrisvidal** [comment]
Hi Adam, 
ok got it now :)
Thanks for the generator, really easy and fast to use and build 👍

**Comment by adamwathan** [comment]
Awesome! Glad you are digging it.
