### ISSUE TITLE
Code block CSS class missing language prefix

### ISSUE THREAD

**Issue by jreviews** [tightenco/jigsaw#424]
In a previous version when I used a code block with a specific language, the class name would appear as `language-php`. After updating to the latest version, the class name is now only `php`.

Is there a configuration setting somewhere to be able to automatically add the language prefix?

Or should the code blocks now be marked up to also include the prefix?

![image](https://user-images.githubusercontent.com/31069418/74439927-78855200-4e43-11ea-9c68-8e2852554898.png)

**Comment by damiani** [comment]
The latest version switched Markdown parsers, so I suspect that's the source of this change, but I'll take a look!

**Comment by Jampire** [comment]
Both `php` and `language-php` are fine here. Code highlighting is done by `highlight.js` or similar package. Markdown parser just inserts the class that you assigned to it. In this case it's `php` or `language-php`. Please, show your final html parsed code and check what package you are using to highlight the code.

**Comment by jreviews** [comment]
I understand that both are fine. The issue is that before `php` alone would result in a final html parsed code with `class="language-php"` and after the change in Markdown parsers  the output is just `class="php"`.

**Comment by Jampire** [comment]
@jreviews are you using Prism for syntax highlight? Prism requires `language-*` class to be added to class attribute. That's why Parsedown generates it. But highlight.js, shipped with Jigsaw templates, doesn't require it. If you are not using highlight.js, could you try it as workaround?

**Comment by jreviews** [comment]
I can make changes needed inside my project to get this working. However, the point of this issue is that any previous project that expected to have the `language-*` prefix as it did before, now needs to be updated to take this into account.

**Comment by damiani** [comment]
@jreviews Fortunately, the new parser exposes a configuration setting for that class name prefix, and I think we should set the default to match the previous Parsedown behavior so we don't break a bunch of existing Jigsaw sites. I've updated that in #426, and also added a way for those config settings to be more easily accessed in `bootstrap.php`, should anyone want to remove the `language-*` prefix (or change any other [PHP Markdown setting](https://michelf.ca/projects/php-markdown/configuration/)).

**Comment by jreviews** [comment]
Thank you!
