### ISSUE TITLE
[Feature Idea] View Models

### ISSUE THREAD

**Issue by lokmanm** [tightenco/jigsaw#425]
Hey guys,

I use Jigsaw on multiple websites that I run, and I have had the case when I need to transform/manipulate data before its rendered or compiled. I have seen some solutions with the Event Listeners but I'm not sure it can be used in this context. The context that I'm suggesting is available on [statamic v3 ](https://v3.statamic.com/blog/view-models) and I thought it a really cool idea for Jigsaw also. Basically, if we introduce ViewModels on a collection it can make it easier for us to play with data before it enters the view, maybe we can define the class on the config file at the collection itself. 

I'm not sure if this idea is feasible or doable for Jigsaw as that's something for the maintainers of the project to decide, I just thought it's a really cool feature to have. 

Thanks

**Comment by damiani** [comment]
Can you elaborate on the use case? Are you envisioning this for a remote collection, when retrieving data from an external API?

**Comment by lokmanm** [comment]
Hey @damiani, sorry for taking your time on this. I will try to explain what I mean. 

It can also be used when retrieving data from an external API, but basically the use case would be an easier way to manipulate with data before it's on the view.

Say I have an array of authors on my Collection, from the view model I can transform the array and add extra columns or do additional stuff before it's passed down to the view, and then the modified array can be rendered inside with blade. 

I could try and give this one a try If I can implement it but I wanted to ask first what is your opinion on this. Thanks and sorry again

**Comment by damiani** [comment]
This is now possible with #447; we can now map over a collection and instantiate a class for each item, in which you can modify/transform any item variables before the page is rendered. I'll add documentation for this shortly.
