### ISSUE TITLE
[Feature Request] GitHub Pages

### ISSUE THREAD

**Issue by vinkla** [tightenco/jigsaw#43]
Wouldn't it be cool if we added an command which published to the `gh-pages` branch automagically?

``` sh
jigsaw gh-pages
```

The command would build the site, checkout the `gh-pages` branch, commit with the current date and then push to the remote `gh-pages` branch.

Inspiration and idea taken from https://github.com/shinnn/gulp-gh-pages

**Comment by erickpatrick** [comment]
Just as a reminder, for people looking into the issues, this can be done by using one tip from [this page](http://jigsaw.tighten.co/docs/deploying-your-site/) on the doc site. 

It points to a `deploy` command for `npm` that is used on the very own docs site. [See it here](https://github.com/tightenco/jigsaw-site/blob/master/package.json#L12).
