### ISSUE TITLE
Building outside from root directory

### ISSUE THREAD

**Issue by balintawak-eskrima** [tightenco/jigsaw#430]
This issue [#222](https://github.com/tightenco/jigsaw/issues/222) marked as closed, but problem not solved.

*config.php*
```php
return [
    'build' => [
        'destination' => '../public_html',
    ],
];
```
dots symbols are swallowed

**Comment by balintawak-eskrima** [comment]
I think that is in trimPath() function
*./vendor/tightenco/jigsaw/src/Support/helpers.php*

```php
/**
 * Remove slashes (including backslashes on Windows),
 * spaces, and periods from the beginning and/or end of paths.
 */
function leftTrimPath($path)
{
    return ltrim($path, ' .\\/');
}

function rightTrimPath($path)
{
    return rtrim($path, ' .\\/');
}

function trimPath($path)
{
    return rightTrimPath(leftTrimPath($path));
}
```
Please update your documentation on https://jigsaw.tighten.co/docs/deploying-your-site/#changing-the-source-and-destination-directories

**Comment by damiani** [comment]
This should be working again now.
