### ISSUE TITLE
Collection called collections

### ISSUE THREAD

**Issue by majorminors** [tightenco/jigsaw#431]
Hello,

This might be a dumb question, but I'm not familiar enough with any of this stuff to know the answer or even where to look (e.g. is a Jigsaw thing, or a Laravel thing - no idea). Very new to coding. As such, hopefully you won't mind if I ask here for any advice you might have.

I'm wondering if it's possible to make a collection called 'collections'. Reason being, I'm trying to do exactly that but it won't build and throws no output during the build process to tell me that something is wrong. Whether I do the jigsaw build, or any npm variant, it just runs through the build process but displays no changes in the files that it has 'built'. If I delete, for example, build_local, and then try to build locally again, it will run through the build process with apparent success, but not actually produce a build_local directory. So either I have the code wrong (which I'm happy to try and troubleshoot myself), or this actually isn't a thing I can do, which is my sneaking suspicion.

So my question is, is it theoretically possible to create a collection called 'collections', and if so, should I be able to do that in the usual manner, e.g.:

in config.php
```
'collections' => [
    'path' => '{collection}/{filename}',
    'articles' => function ($page, $allArticles) {
        return $allArticles->filter(function ($article) use ($page) {
            return $article->collections ? in_array($page->getFilename(), $article->collections, true) : false;
        });
    },
],
```

with a successfully built 'articles' collection.

Any advice you might have is much appreciated. Feel free to even just tell me what kinds of search terms I need to use to figure this out myself.

Warm regards,

Dorian

p.s. big fan of this project - despite this issue, and despite being a beginner, I'm having enormous fun creating various websites with Jigsaw. I'd say it's an equivalent entry-level to any kind of customised Wordpress, with the integration to Netlify/Github pages. Extremely easy to use and usually pretty easy to figure out how I've broken it when I break it. Recommending it to everyone. So thank you.

**Comment by damiani** [comment]
Welcome to Jigsaw! You are right, though, naming a collection `collections` conflicts with the way Jigsaw works under the hood; each collection gets eventually added as a key to the array that starts in `config.php`, so that they can be accessed by their variable name (e.g. `$posts`) in Blade templates. Adding a collection named `collections` overwrites the original config key for `collections`, and then it all falls apart :) 

Are you able to choose a different name for your collection?

**Comment by majorminors** [comment]
Ok, makes sense. Thanks very much for the feedback. I certainly can choose a different name. I'll close the issue.

I wonder though. Let's say I call the collection 'categories'. Am I correct to think that if I were to specify the path as 'collections', with a corollary page called 'collections', the site-viewer would see the categories collection as 'collections'? Albeit by confusing the code. Or am I likely to run into some unforseen problem here?

**Comment by damiani** [comment]
Yes, you're free to specify `path` as whatever you want:

```
'categories' => [
    'path' => 'collections/{filename}',
    'articles' => function ($page, $allArticles) {
        return $allArticles->filter(function ($article) use ($page) {
            return $article->categories ? in_array($page->getFilename(), $article->categories, true) : false;
        });
    },
],
```

In this case, visitors to the site would never encounter the word "categories".

**Comment by majorminors** [comment]
Amazing. Thank you very much!!
