### ISSUE TITLE
Method to re-write all static file output URLs?

### ISSUE THREAD

**Issue by cameron-elliott** [tightenco/jigsaw#437]
So, imagine I need to use by build_local output,
at a different sub-directory  than / , say maybe under /foo,
using a reverse proxy or using the build_local output as static files in another Laravel project.
(Please try not to judge. ) :smile:

To accomplish this, one needs the URLs in the static build_local output to represent the
place where the assets can actually be found, say '/foo/assets/images/*', rather than '/assets/images/*' for example.

Is there a way to do this with Jigsaw or the existing blog/docs template ?

Looking at this code line, kind of says to me 'no', but I thought I'd ask:
[source line](https://github.com/tightenco/jigsaw-docs-template/blob/7c053b086a28ffafad4acb868b70a8a160aa661b/source/index.blade.php#L20)

        <img src="/assets/img/logo-large.svg" alt="{{ $page->siteName }} large logo" class="mx-auto mb-6 lg:mb-0 ">

That path to "/assets/img/logo-large.svg" doesn't have any code that would allow modifying the path, but I have to ask incase I am missing something.

Is there a way to have all the 'output' paths in the generated code have a different base?

Thanks,
Cameron

**Comment by cameron-elliott** [comment]
Maybe I should be looking at the browser-based <base> element

**Comment by damiani** [comment]
You could append `{{ $page->baseUrl }}` to each image path, and specify different URLs in `config.php` and `config.production.php`.

**Comment by cameron-elliott** [comment]
Oh! Cool, thanks, Keith.
