### ISSUE TITLE
[Question] Is it possible to use Laravel 7 Blade Component Tags?

### ISSUE THREAD

**Issue by cristiangervasi** [tightenco/jigsaw#439]
Hi, Laravel 7 introduced a new way to define and use components, is it possible to adapt a Jigsaw project to use this way of working with components? 
Do you plan to update Jigsaw to use the latest version of the Illuminate View component in the near future?
Thank you for your amazing work on this project!

**Comment by damiani** [comment]
Working on it! See https://github.com/tightenco/jigsaw/pull/440

**Comment by damiani** [comment]
Merged #440
