### ISSUE TITLE
[Feature Request] Generated navigation

### ISSUE THREAD

**Issue by ToddSmithSalter** [tightenco/jigsaw#44]
I would love to have the ability to generate [navigation](https://github.com/tightenco/jigsaw-site/blob/master/source/_layouts/documentation.blade.php#L24-L34) from a directory of markdown files. 

We have a repo of markdown files I would like to pull in as a submodule, have a rebuild triggered, and navigation generated in the template. Regarding sorting, navigation could be spit out alphabetically, or a standardized filename syntax could be established to number the files with prefix to specify the order.

```
// This spits out an alphabetized array
my_awesome_file.md
a_silly_file.md
stupid_post.md

// This spits out a numbered array
01_my_awesome_file.md
02_a_silly_file.md
03_stupid_post.md
```

Paired with #24, this could be really powerful, displacing the default source directly to wherever you wish and spitting out structured nav.

**Comment by legshooter** [comment]
Isn't using directories kind of inflexible? A menu item could live in whatever directory, when perhaps using something like [Page Meta / Front Matter](#7), with say:
```yaml
---
# yada yada yada
nav: main
# yada yada yada
---
```
And then outputting in a `.blade.php` file:
```php
<ul>
@foreach(nav('main') as $navItem)
    <li><a href="{{ $navItem->url }}">{{ $navItem->name }}<li>
@endforeach
</ul>
```
Or something along those lines...

**Comment by damiani** [comment]
Take a look at [collections](http://jigsaw.tighten.co/docs/collections/) in v1.0.0, which makes this possible. There's also example code for a generated nav in the [demo repo](https://github.com/tightenco/jigsaw-collections-demo/blob/master/source/_layouts/sidebar/post-menu.blade.php).
