### ISSUE TITLE
How to change date to other language?

### ISSUE THREAD

**Issue by allrude** [tightenco/jigsaw#441]
Are you referring to the blog template? If so, you can change the `getDate()` method in `config.php` to whatever you wish, so you can move `setlocale` there.

_Originally posted by @damiani in https://github.com/tightenco/jigsaw/issues/363#issuecomment-595601560_

Hi Damiani, can you give an example of how to do this I surfed Stackoverflow and other documentation but can't get to work, I think many of us need to use it with our own language so it should be part of the documentation how to change it

greetings

**Comment by bakerkretzmar** [comment]
If you're using the [Blog starter template](https://github.com/tightenco/jigsaw-blog-template), you can modify [the included `getDate()` helper function](https://github.com/tightenco/jigsaw-blog-template/blob/366eee853bfa84c18d3498215820e387ad80ce58/config.php#L30-L32) to set the locale there.

Based on the comments in #363, that could look something like:

```php
'getDate' => function ($page) {
    setlocale(LC_TIME, 'de_DE');
    return strftime(
        '%e. %B, %Y',
        Datetime::createFromFormat('U', $page->date)->getTimestamp()
    );
},
```

or

```php
```
