### ISSUE TITLE
Links are broken in build

### ISSUE THREAD

**Issue by brltdxd** [tightenco/jigsaw#442]
Hello,

I am trying to host a static [site](https://brltdxd.github.io/jigsaw-test/) in GitHub pages but the links generated for the assets (css, images, js) after the build, either local or production, are broken.

Here is a test [repo](https://github.com/brltdxd/jigsaw-test/tree/gh-pages)

From #378, I know that keeping the `/` would resolve the path to `yoursite.com/assets/css/main.css` but it doesn't seem to be working and a possible workaround that I am thinking of is including a `baseUrl` in the `config.php` file and concatenating it to each links.

e.g.
```
<link rel="stylesheet" href="{{$page->baseUrl}}{{ mix('css/main.css', 'assets/build') }}">
```

Any help is appreciated.

Thank you.

**Comment by ryangjchandler** [comment]
Have you tried removing the URL before the `{{ mix() }}` call?

**Comment by brltdxd** [comment]
Hi @ryangjchandler,

If you are referring to the `$page->baseUrl`, yes. The default link is this:

```
<link rel="stylesheet" href="{{ mix('css/main.css', 'assets/build') }}">
```
And it is resulting to:
```
<link rel="stylesheet" href="/assets/css/main.css">
```
But this is not working in GitHub Pages.

**Comment by ryangjchandler** [comment]
Is GitHub Pages pointed / deploying the correct directory, along with all of the assets? Using Mix should point to `/assets/build/css/main.css` based on the code you put above.

**Comment by brltdxd** [comment]
Hi @ryangjchandler,

Yes, it is generating `/assets/build/css/main.css` but that is the problem.
With the `/` in front, the assets are not being loaded correctly.

**Comment by ryangjchandler** [comment]
> Hi @ryangjchandler,
> 
> Yes, it is generating `/assets/build/css/main.css` but that is the problem.
> With the `/` in front, the assets are not being loaded correctly.

Are you experiencing problems with others assets or just your CSS?

**Comment by brltdxd** [comment]
Hi @ryangjchandler,

All of my assets including the links are not working correctly.

**Comment by ryangjchandler** [comment]
I'm not too sure what's happening then. It seems like your build paths are incorrect, have you checked the output and made sure your assets are actually inside of the assets/build dir?

**Comment by brltdxd** [comment]
Hi @ryangjchandler ,

I've used the docs template and just modified the contents. I didn't changed anything with the file structure and all the assets stayed in their original place. The problem with the asset links is not just in gh-pages, it is the same even when just viewing the build (local or production) using live server in vscode.

**Comment by damiani** [comment]
Seems like some issue w/ GitHub pages; this is all rendering fine for me when I run your code locally:

![Screen Shot 2020-04-10 at 4 53 53 PM](https://user-images.githubusercontent.com/357312/79022517-26fbf980-7b4c-11ea-8a34-fb98f4be259a.png)

Are you using a custom domain on GH pages, or the `github.io` domain? If the latter, are you including your repo name in the `baseUrl`?

**Comment by brltdxd** [comment]
Hi @damiani ,

Not using a custom domain on GH pages although I am deploying it to our enterprise GH so the link to pages actually looks like this:
```
github.<company>.com/pages/<organization>/<repo>/
```

I've tried to include the `baseUrl` on production build by adding an `if` condition like this:

```php
// production config
// 'baseUrl' => 'https://github.<company>.com/<organization>/<repo>/
<link rel="stylesheet"
  @if($page->production)
  href="{{ mix('css/main.css', $page->baseUrl . 'assets/build') }}"
  @else
  href="{{ mix('css/main.css', 'assets/build') }}"
  @endif
>
```
But I'm getting a mix manifest error.
I'm still trying to think of another workaround.

**Comment by brltdxd** [comment]
Okay, so I've tried it this way because I don't want to include the whole URL of the repo to the config file.
```
@if($page->production)
<link rel="stylesheet" href="assets/build/css/main.css">
@else
<link rel="stylesheet" href="{{ mix('css/main.css', 'assets/build') }}">
@endif
```
I am losing the `id` from the `mix-manifest.json` file and I honestly don't know what would be the implications for that. Maybe you could enlighten me with this. 😄
```php
// mix-manifest.json file
"/css/main.css": "/css/main.css?id=1c4fcd0e6ddf85bd273d",
```

The CSS link in the production build
```html
<link rel="stylesheet" href="assets/build/css/main.css">
```

I'm not entirely sure if this is the right way to go to get it up and running with GH pages and I'm really open to any suggestions. 😂

**Comment by damiani** [comment]
```html
<link rel="stylesheet" href="assets/build/css/main.css">
```
^^ Leaving off the leading `/` won't work correctly if your page is nested more than one level down

---

```html
href="{{ mix('css/main.css', $page->baseUrl . 'assets/build') }}"
```
^^ This also doesn't work, because the 2nd parameter in the `mix` helper should be the path to the `mix-manifest.json`; that's why you get a Mix error in that circumstance.

---

Missing the `id` from `mix-manifest.json` means you lose cache-busting behavior (meaning changes to your CSS might require a hard refresh if a user has it cached locally).

---

I would:
- set your local `baseUrl` in `config.php` (or leave it blank)
- set your complete GitHub Pages root as the `baseUrl` in `config.production.php`:

```php
'baseUrl' => 'https://github.<company>.com/pages/<organization>/<repo>',
```
- prepend the `baseUrl` to your stylesheet `href`:

```html
<link rel="stylesheet" href="{{ $page->baseUrl }}{{ mix('css/main.css', 'assets/build') }}">
```

The correct GitHub Pages URL will then be prepended when building for production, but not when building locally.
