### ISSUE TITLE
Consider replacing Symfony Console with `illuminate/console`

### ISSUE THREAD

**Issue by ryangjchandler** [tightenco/jigsaw#445]
I'm currently writing some custom commands to make things a bit quicker for me. Once thing I noticed is that the vanilla `symfony/console` package is being used instead of `illuminate/console`. Is there any reason for this, since I was kind of expecting `illuminate/console` to have some parity with Laravel itself.

Would you ever consider switching too, since most people would probably find the `illuminate/console` classes / setup easier to use.

**Comment by damiani** [comment]
Yes, I think that's a great idea!

**Comment by ryangjchandler** [comment]
Perfect. I'm happy to make a PR for this if you're interested? Will involve moving the existing commands to the new format for consistency too.

I'm not sure if this would be considered a breaking change though since anyone who has implemented their own commands might have problems?

**Comment by damiani** [comment]
Yes, I'd welcome a PR for this. And I don't think it would be a breaking change, since custom commands aren't really a documented feature.

**Comment by ryangjchandler** [comment]
> Yes, I'd welcome a PR for this. And I don't think it would be a breaking change, since custom commands aren't really a documented feature.

Great! I'd start working on it and send it in next week :)

**Comment by damiani** [comment]
Looking forward to it, thanks!
