### ISSUE TITLE
Move `jigsaw` binary to project directory

### ISSUE THREAD

**Issue by ryangjchandler** [tightenco/jigsaw#446]
One thing that I do when using Jigsaw is setup Composer scripts for the `jigsaw` command line utility. 

I'm wondering what people think about copying this to the root directory of a project, so it acts like the `artisan` command and can be accessed as `php jigsaw` as opposed to `./vendor/bin/jigsaw`.

**Comment by ryangjchandler** [comment]
Closing this one since I think there would be some updating problems involved if any new command were introduced.

**Comment by damiani** [comment]
Yeah agreed, though something to consider for 2.0.
FWIW, I use a `jigsaw` alias; you can also add `./vendor/bin` to your PATH.

**Comment by ryangjchandler** [comment]
> Yeah agreed, though something to consider for 2.0.
> 
> FWIW, I use a `jigsaw` alias; you can also add `./vendor/bin` to your PATH.

Yeah have done this now, thanks!
