### ISSUE TITLE
storing cover-images / thumbnail into _posts collection

### ISSUE THREAD

**Issue by armansansd** [tightenco/jigsaw#449]
Hi, 
I would like to build my website with jigsaw but to do so, it would be easier for me to store all my data project by project into my collection. 
```
_posts/
      myproject1/
              myproject1.md
              images/
                   images1.png
                   images2.png 
```

This way I could even have gallery of pictures if needed.
For now I store the pictures under the ```assets``` folder but it seems a bit messy. 

Do you know if it's possible ? I tried but I get an error 
```No matching collection item handler for file : images1.png```
shall I use a nested collection like [here](https://github.com/tightenco/jigsaw/issues/160) ?

thanks a lot

**Comment by ryangjchandler** [comment]
You should prefix it with an underscore. Doing so will tell Jigsaw to ignore the file and it won't be processed.

**Comment by armansansd** [comment]
Thanks for your reply ! 
I tried your solution but because my file is ignore it can't be use it in my markdown. 
```![](images/_images1.png)``` return a broken link, and no images is export in my build-local folder . Maybe jigsaw is just not program for this ?  Or there is something i still don't understand ...

**Comment by damiani** [comment]
No, Jigsaw doesn't support this structure at the moment. Any file in a collection directory (like `myproject1`) will be processed as a content file; I would keep your images in `assets`, in subdirectories for each project.

**Comment by GeorgeGedox** [comment]
Resurrecting a dead issue maybe but I've just hit this wall, managing media for articles is a pain currently, could we add a filter to ignore specific directories or file types in the collection configuration? Sort of like this:
```
