### ISSUE TITLE
File size limit leads to memory error

### ISSUE THREAD

**Issue by chrisvidal** [tightenco/jigsaw#45]
Hi Adam,
i was adding a video folder with a video filesize of 65Mo
the gulp task seems to fails because of this filesize

here is the tracelog

`[10:34:05] Starting 'exec'...

Triggering Command...
jigsaw build
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 66534158 bytes) in /Users/chrisvidal/.composer/vendor/illuminate/filesystem/Filesystem.php on line 109
[10:34:05] 'exec' errored after 227 ms
[10:34:05] Error in plugin 'gulp-shell'
Message:
    Command `jigsaw build` failed with exit code 255
[10:34:05] Error in plugin 'run-sequence'
Message:
    An error occured in task 'exec'.
`

**Comment by nerdmediallc** [comment]
Increase your max memory size in your php.ini

**Comment by adamwathan** [comment]
^ That should help temporarily but gonna see if there's anything I can do
using streams to fix it too

**Comment by mrgodhani** [comment]
I recently had exact same problem I got 
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 2595368 bytes) in /Users/meetgodhani/Desktop/WebProjects/<project>/vendor/illuminate/filesystem/Filesystem.php on line 38
```

Even increasing limit didn't quite helped

**Comment by damiani** [comment]
I just added a fix on `dev-master` that should help with copying large files. Could you test it out by changing your Jigsaw version in `composer.json` to `dev-master`, running `composer update`, and then trying your build again?

**Comment by dgursh** [comment]
@damiani I am having this same issue

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes)
````

I've narrowed it down to the following code for a dropdown menu in my app

```
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        Dropdown<i class="fa fa-angle-down fa-fw" aria-hidden="true"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu">
        <li>
            <div class="row text-left" style="width:100%;">
                @foreach ($topics->chunk(6) as $chunk)
                <ul class="col-md-3 list-unstyled drop-column">
                    @foreach ($chunk->where('launched', true) as $topic)
                        <li><a href="{{ '/home/'.str_slug($topic->title).'/' }}"><img src="{{ '$topic->image }}" alt="Icon">{{ $topic->title }}</a></li>
                    @endforeach
                </ul>
                @endforeach
            </div>
        </li>
    </ul>
</li>
```

When I remove the chunk function it works, but I'm not sure why. Why is the chunk making me run out of memory on builds?
