### ISSUE TITLE
Browser-sync not found - npm run watch

### ISSUE THREAD

**Issue by piercemcgeough** [tightenco/jigsaw#455]
When running `npm run watch` I get Error: Cannot find module 'browser-sync'.

I noticed that it was removed from the package.json for a new laravel-mix-jigsaw but does not appear to be working.

Appears to be this merge.
https://github.com/tightenco/jigsaw/commit/d912252a1acc33b2a6ae504d882a0f8563de63c2

Is there a different way to run it that just hasn't been added to the docs or that i'm missing.
Thanks

**Comment by bakerkretzmar** [comment]
Thanks! Fixed in tightenco/laravel-mix-jigsaw#4.
