### ISSUE TITLE
The server doesn't work correctly with paths that start with a number

### ISSUE THREAD

**Issue by stancl** [tightenco/jigsaw#456]
I'm working on an implementation of tightenco/jigsaw-docs-template#31 but I found that if you have `source/1.x`, `source/2.x` etc instead of `source/docs`, the server will return a 404, but if you append `/index.html` it works.

**Comment by damiani** [comment]
It's not actually the leading number that's the problem, it's the period; PHP's built-in web server (which `jigsaw serve` launches) has a bug that messes up `PATH_INFO` if the final component of a URL contains a `.` but is not a file (see https://www.php.net/manual/en/features.commandline.webserver.php#115907 and https://bugs.php.net/bug.php?id=61286).

So, unfortunately, nothing we can do about that. You might want to use Laravel Valet for local testing, which handles directories with `.` in them correctly.
