### ISSUE TITLE
Line numbers for code blocks?

### ISSUE THREAD

**Issue by burzum** [tightenco/jigsaw#459]
Is there any plugin or other way of getting line numbers in front of code blocks in articles? I'm using markdown.

I couldn't really find any plugin or solution for Jigsam because it is a pain to find anything at all for it because jigsaw is such a generic term for a search. :(

**Comment by damiani** [comment]
The easiest way is probably to use a JavaScript-based syntax highlighter, like [prism.js](https://prismjs.com/plugins/line-numbers/), [codemirror](https://codemirror.net/) (both of which have line number support), or [highlight.js](https://highlightjs.org/) (which doesn't have built-in line number support, but does through [a plugin](https://github.com/wcoder/highlightjs-line-numbers.js/). There are also some nifty [CSS-only](http://www.formauri.es/personal/pgimeno/temp/numbering-code-demo.html) or [JS + CSS](https://jsfiddle.net/tovic/AbpRD) solutions floating around out there.
