### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by appkr** [tightenco/jigsaw#46]
I recently built a static site with jigsaw. In comparison with other static site builder, one missing feature was RSS feed generation. 

I did it manually using large data array in config.php and blade like the following..

```php
// config.php

return [
    'lessons' => [
        [
            'title' => 'Foo title',
            'url' => '/foo.html',
            'description' => 'Foo description...',
        ],
        [...],
    ],
];
```

```xml
<!--// feed.xml.blade.php -->

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{ $site_title }}</title>
    <description>{{ $site_description }}</description>
    <link>http://example.com</link>
    <atom:link href="http://example.com/feed.xml" rel="self" type="application/rss+xml"/>
    <pubDate>{{ (new DateTime)->format(DATE_ATOM) }}</pubDate>
    <lastBuildDate>{{ (new DateTime)->format(DATE_ATOM) }}</lastBuildDate>
    <generator>Blade templating engine</generator>

    @foreach($lessons as $lesson)
      <item>
        <title>{{ $lesson['title'] }}</title>
        <description>{{ $lesson['description'] }}</description>
        <pubDate>{{ (new DateTime)->format(DATE_ATOM) }}</pubDate>
        <link>http://example.com{{ $lesson['url'] }}</link>
        <guid isPermaLink="true">http://example.com{{ $lesson['url'] }}</guid>
      </item>
    @endforeach
  </channel>
</rss>
```

and then, in my build script

```sh
# build.sh

[ -f build_local/feed.xml.html ] && mv build_local/feed.xml.html build_local/feed.xml
```

No clean though, I was able to get a valid feed.xml.

While I'm at it, I'd like to ask one more. I hope I can access the array of the file to be compiled, so that I don't have to define the large data in config.php. Metadata like `title`, `description`, `published_at`, `...` may be read from front formatter of the markdown file.

**Comment by paslandau** [comment]
I have excatly the same issue. My first attempt was to reegineer the `jigsaw` command and make the componentes (Jigsaw, the DI-Containert, ...) available in my Blade template but then I realized that they don't expose the meta data from my mark down posts via public methods.

At that point it occured to me that I might not be the only one with that problem and before it got even messier I decided to check github :)

I would actually be nice to have the Jigsaw intance have available in the blade template and be able to call something like `$jigsaw->parseMetaData()` - although this might be really spceific to markdown for now, I feel like it's the most common format for static site generators. 

Before I write up a pull request I wanted to get your opinion on that approach.

Cheers
Pascal

**Comment by mattstauffer** [comment]
I think the need here is really #3. It's a big missing piece of Jigsaw, and once we have it, we'll need to expose the ability to get and loop through collections anywhere in the app--including RSS feeds.

**Comment by mattstauffer** [comment]
If I understand correctly, there are a few issues here:

1. Generating files that don't have `.html` as the extension
2. Adding collections like #3 so we can have a "collection of blog posts" that the RSS feed may be exposing
3. Adding the ability for any page (like this template) to iterate over a collection and spit out specific information for each item of the collection
4. Adding the ability for a Blade template to get the metadata about a Markdown post rendered within it 

Does this sum up the requests you are making, @appkr and @paslandau? Thanks!

**Comment by appkr** [comment]
@mattstauffer Thanks for the progress.

It's not clear that you are saying those are already added on new version. Anyway I'll try the new version.

For no.4 obviously YES. I'd like to pass any arbitrary variable to blade through yaml frontmatter(or any other mean). And by combining that variable and collections(like you mentioned in #3), I think people can build anything. One of them is RSS feed.

**Comment by mattstauffer** [comment]
@appkr these changes are *not* made. I'm rather trying to clarify whether this is what y'all are wanting.

With regard to your request, you already can pass arbitrary variables to Blade through Yaml frontmatter.

Sounds like these are the features y'all would like. I'll make sure they all exist as issues and then close this one. Thanks!

**Comment by colinmac17** [comment]
@mattstauffer or team, is this still something that is missing or was determined not necessary to include? I am about to add a blog to my jigsaw site and would love an rss feed. Thanks for any help!

**Comment by mattstauffer** [comment]
@colinmac17 It's totally included now! If you want to add a blog or a template, the simplest place to start is the Blog Template: https://github.com/tightenco/jigsaw-blog-template

You can see our RSS feed here: https://github.com/tightenco/jigsaw-blog-template/blob/master/source/blog/feed.blade.atom

**Comment by colinmac17** [comment]
@mattstauffer thanks! I will be implementing this into my site which is not using a template, but this should be very helpful.
