### ISSUE TITLE
BladeCompiler Error

### ISSUE THREAD

**Issue by dpritchard** [tightenco/jigsaw#462]
Apologies if this is not the right place, but it looks like a recent change has broken Jigsaw (at least for new users like me stepping through the [installation](https://jigsaw.tighten.co/docs/installation/) for the first time).

## Issue

The error arises when building the site. The general gist of it is:

```
Uncaught TypeError: Argument 1 passed to
Illuminate\View\Compilers\ComponentTagCompiler::__construct() must be of the type 
array, object given
```

## Steps to reproduce (on v. 1.3.25):

```
mkdir my-site
cd my-site
composer require tightenco/jigsaw
./vendor/bin/jigsaw init
./vendor/bin/jigsaw build
```

## Solution?

The issue seems to stem from #460 and [line 23](https://github.com/tightenco/jigsaw/blob/3294514309e113e10aeb7f80a18ee388123b60bc/src/View/BladeCompiler.php#L23) of `src/View/BladeCompiler.php` specifically.

```php
return (new ComponentTagCompiler(
  $this, $this->classComponentAliases
))->compile($value);
```

At least in my local version, if I reverse the order of the arguments to `new  ComponentTagCompiler(...)`, things seems to build OK. 

```php
return (new ComponentTagCompiler(
  $this->classComponentAliases, $this
))->compile($value);
```

Please let me know if more information or a PR is required.

**Comment by damiani** [comment]
Thanks @dpritchard, this should be fixed now in v1.3.26!
