### ISSUE TITLE
Not sure how to configure browsersync options in new webpack.mix.js setup

### ISSUE THREAD

**Issue by raniesantos** [tightenco/jigsaw#464]
Note: I'm using Laradock with Jigsaw

[Screen recording 1: Trying to add browserSync options in webpack.mix.js](https://giant.gfycat.com/LawfulFavoriteKiskadee.webm)

[Screen recording 2: Trying to change the port](https://giant.gfycat.com/SlimyWeepyBass.webm)

[Screenshot of terminal](https://user-images.githubusercontent.com/8528269/80558964-b50e2600-8a0e-11ea-830a-0d9233414d5c.png)

I'm likely putting the options in the wrong place. I don't know where they should go.

**Comment by bakerkretzmar** [comment]
Thanks! Closing this in favour of tightenco/laravel-mix-jigsaw#9.
