### ISSUE TITLE
After fresh install and init "tasks" folder is missing

### ISSUE THREAD

**Issue by otherpaco** [tightenco/jigsaw#465]
I started a fresh project

```bash
composer require tightenco/jigsaw
./vendor/bin/jigsaw init
npm install
```

I saw that there is no "tasks" folder and I miss "./tasks/build.js" what I normally require in my webpack.mix.js

```js
let build = require('./tasks/build.js');
```

I tried another fresh install with

```bash
./vendor/bin/jigsaw init blog
```

there a "tasks" folder is created.
The documentation shows a "tasks" folder, too.

Directory Structure
https://jigsaw.tighten.co/docs/installation/

Not sure if change or bug.

Thank you

**Comment by bakerkretzmar** [comment]
Thanks for the heads up, looks like I forgot to tag releases of the templates when we updated them a few weeks ago, will do that now!

That screenshot in the docs is also out of date, we'll update that.

A plain Jigsaw install should work fine though—when you run the code in your first example, does it fail?

**Comment by otherpaco** [comment]
Seems to be a change in v 1.3.22 #452
I guess the changes should be added to the default "blog" and "docs" templates and after that to the docs.

**Comment by otherpaco** [comment]
No the fresh install runs fine I was using a pre 1.3.22 webpack.mix.js configuration of another project and it conflicted because I required './tasks/build.js'.
Thank you for the fast answer, jigsaw and all the laravel stuff.

**Comment by bakerkretzmar** [comment]
Sounds good, glad it's working! The blog template should work now too, double check it installs `v1.1.0` in case Composer has cached stuff.

**Comment by otherpaco** [comment]
Thanks again, just wanted to add, the blog template and the basic init worked both fine I was just confused as one created a "tasks" folder and the other did not.
