### ISSUE TITLE
Generate a collection using another collection

### ISSUE THREAD

**Issue by Max13** [tightenco/jigsaw#466]
I'm playing with the blog template, and I would like to generate the `categories` collection using the `posts` collections.

Currently, the template contains 1 file in `source/_categories` for each category known, but as it's possible to loop in the `posts` collection and look for the categories, it seems not to be possible to use a collection to generate another one (due to the fact that, collections aren't built (yet) during `beforeBuild`, and it's too late arriving at `afterCollections` to append a new one in config).

Is there a way or workaround to use a built collection (`posts`) to populate another (`categories`) ?

**Comment by damiani** [comment]
There isn't a built-in way to do this (at the moment), for exactly the reasons you described: collections are only processed once, so your `categories` collection can't automatically access the contents your `posts` collection. 

There are some ideas for dynamically generating collections discussed [here](https://github.com/tightenco/jigsaw/issues/273) that we're exploring, but haven't yet nailed down an elegant implementation.

In the meantime, though, as mentioned in [an issue from the blog template repo](https://github.com/tightenco/jigsaw-blog-template/issues/40), I think @camuthig has a solution that might do what you're hoping: he wrote an `afterCollections` listener that checks the `posts` collection and adds any missing categories to the `category` collection, treating the generated pages as a remote collection (via the `items` key). Pretty slick solution, [check it out](https://github.com/camuthig/jigsaw-blog-default-categories).

**Comment by Max13** [comment]
thanks

**Comment by paulofreitas** [comment]
> There isn't a built-in way to do this (at the moment), for exactly the reasons you described: collections are only processed once, so your `categories` collection can't automatically access the contents your `posts` collection.
> 
> There are some ideas for dynamically generating collections discussed [here](https://github.com/tightenco/jigsaw/issues/273) that we're exploring, but haven't yet nailed down an elegant implementation.
> 
> In the meantime, though, as mentioned in [an issue from the blog template repo](https://github.com/tightenco/jigsaw-blog-template/issues/40), I think @camuthig has a solution that might do what you're hoping: he wrote an `afterCollections` listener that checks the `posts` collection and adds any missing categories to the `category` collection, treating the generated pages as a remote collection (via the `items` key). Pretty slick solution, [check it out](https://github.com/camuthig/jigsaw-blog-default-categories).

Unfortunately the aforementioned solution no longer works because `buildCollections()` method is protected and so is `$jigsaw->remoteItemLoader` property. Couldn't find a way to achieve the same thing. :/

**Comment by palexandrite** [comment]
@camuthig please, let me know how to make pagination by your extension?

**Comment by camuthig** [comment]
@palexandrite I haven't worked with this project much in recent years. If you add pagination to the general category layout, does it not add it to the generated ones as well? I'm not immediately sure how to add pagination to the user-defined category layout, so hard for me to quickly say how to add it to the generated ones.

**Comment by palexandrite** [comment]
@camuthig thank you pretty much for your answer. 

About the pagination in Jigsaw, I should make the pagination by YAML syntax in a head of a file (such as an extended layout or a page of a main category regarding the Jigsaw documentation. But the pagination shown only for simple pages not for pages of collections.

It would be nice to have a pagination in a page of a collection :-)
