### ISSUE TITLE
`$page` and collection variables not available in x-style components

### ISSUE THREAD

**Issue by amadeann** [tightenco/jigsaw#469]
Neither `$page` nor collection variables are passed by default to `x-components`. You need to explicitly pass them, as in:

```
<x-footer :page="$page" :categories="$categories" />
```

Otherwise, you get an error like:
```
Call to a member function featuredCategories() on null (View: C:\Users\...\source\_components\footer.blade.php)
```

This is inconsistent with how these variables are available by default in include-style components. For example, if I include the same component this way:
```
@include('_components.footer')
```
I don't need to pass `$page` and `$categories` for it to work. I am using Jigsaw `v1.3.27`.

**Comment by bakerkretzmar** [comment]
Hey @amadeann—this is one of the key differences between Blade includes and components: includes automatically inherit the parent scope, and components do not. Laravel ≤ 6.x `@component` directives also work this way.

If you need the partial you're including to inherit the entire parent scope automatically, you should keep using `@include`.

**Comment by amadeann** [comment]
@bakerkretzmar 

I see `$page` and collection variables as something equivalent to variables globally included in views via [View Composers](https://laravel.com/docs/7.x/views#view-composers). If you do this in a service provider in Laravel:

```
View::composer('*', function ($view) {
    $view->with('foo', "This will be displayed");
});
```
You have access to `$foo` inside x-style components. I think it would make a lot of sense to include them automatically in Jigsaw as well.

**Comment by bakerkretzmar** [comment]
@amadeann actually yeah, we tend to agree with you. We're gonna look into making this change or something similar.

Eventually I _think_ we'd like to split `$page` out into two variables, `$page` and something like `$site` or `$app`, where `$app` is truly global and available in components as you've described, and `$page` behaves how it does now, as if it was passed from a controller, and is not global.

**Comment by bumbummen99** [comment]
@bakerkretzmar Any plans on implementing it?

Tried to use View::share in the bootstrap but that does not work at all. Switched to full framework to save a lot of time.
