### ISSUE TITLE
[Proposal] jigsaw watch

### ISSUE THREAD

**Issue by Mochaka** [tightenco/jigsaw#47]
Like what Jekyll has, where it watches for changes and does a jigsaw build for development.

**Comment by Shaun2D2** [comment]
@Mochaka I think you might be looking for this http://jigsaw.tighten.co/docs/compiling-assets/ under Watching for changes

**Comment by mattstauffer** [comment]
@Mochaka Can you take a look at @Shaun2D2's link above and see if it meets the needs you're having? That's what we use at Tighten.

**Comment by mattstauffer** [comment]
Ping @Mochaka; will be closing this shortly if we don't hear back from you. Thanks!
