### ISSUE TITLE
Use jigsaw as a library

### ISSUE THREAD

**Issue by Wulfheart** [tightenco/jigsaw#472]
Is it possible to use jigsaw as a library, e.g. in a existing Laravel project?

**Comment by HeroVega** [comment]
Per this closed issue and comment by Keith, no it doesn't appear like that's on the roadmap unfortunately:

https://github.com/tightenco/jigsaw/issues/376#issuecomment-591746786

**Comment by damiani** [comment]
@Wulfheart @HeroVega It's not possible at the moment, but this is a high priority for an upcoming v2 of Jigsaw that we've begun working on ...

**Comment by aminraeisi** [comment]
Is it possible to build my laravel (app) and jigsaw (for my docs) and then redirect any request to `/docs` to my jigsaw path and not to laravel?
