### ISSUE TITLE
Can I use config values in bootstrap.php function without being passed as argument?

### ISSUE THREAD

**Issue by raniesantos** [tightenco/jigsaw#473]
I have a few regular functions defined in bootstrap.php (they're not listeners).

I want to use a config variable from within that function and the `$page` variable is unavailable here.

I know I could include/require it in, but there might be alternative ways to access it that I'm unaware of, like getting access to the `->getConfig()` method.

Context:

I have a `$page->media()` helper in my config for getting media from a CDN. It takes a value from another config key.

I want to shorten it to just `media()` in `bootstrap.php` so it would be similar to Laravel's `asset()` helper.

**Comment by bakerkretzmar** [comment]
I don't _think_ there is currently a better way to do that than what you've suggested, including or requiring the file. You do also have access to the `$container` variable in `bootstrap.php`, but I'm not able to make a plain helper function like you're describing work with it either.

**Comment by raniesantos** [comment]
I managed to access it through `$GLOBALS['container']->config`
