### ISSUE TITLE
Blade @include leads to "unexpected '$page' (T_VARIABLE)"

### ISSUE THREAD

**Issue by molerat619** [tightenco/jigsaw#482]
I like to separate sections of code into separate files so they are easier to reuse. An `index.blade.php` combines those files as needed. Example:

**index.blade.php**
```php
---
title: my page
---

@extends('_layouts.master')

@section('content')
...
@include('_partials.navigation-dots', ["dots" => ["about-us", "..."]])
....
@endsection
```

**navigation-dots.blade.php**
```php
<div class="dot-navigation-container d-none d-lg-block">
    <span class="navigation-dot scroll-to" data-target="top"></span>

    @foreach($dots as $dot)
        <span class="navigation-dot scroll-to" data-target="{{ $page->__('navigation-dots.' . $dot . '.target') }}"></span>
    @endforeach
</div>
```

When I run the build, it complains with following error: `syntax error, unexpected '$page' (T_VARIABLE), expecting ',' or ')'` for the line inside the @foreach. It seems that due to the `@include` the `$page` variable is not existent anymore. 

**Any idea how I can fix this?**

_P.S.: The `__`-method is just a translation function on the `$page` object._

**Comment by damiani** [comment]
Your example works perfectly in my testing; the `unexpected '$page' ... ` is indicating there's a syntax error somewhere in your partial (otherwise, it would throw an error something like `Call to a member function __() on null`). Could you share a link to a repo where I could look at the full code?

**Comment by molerat619** [comment]
@damiani as I was trying to prepare a repo for you, it started working again. I can't see the difference, but this is my "new" `navigation-dots.blade.php`:

```php
---
language: en
---

<div class="dot-navigation-container d-none d-lg-block">
    <span class="navigation-dot scroll-to" data-target="top"></span>

    @foreach($dots as $dot)
    <span class="navigation-dot scroll-to" data-target="{{ $page->__('navigation-dots.' . $dot . '.target') }}"></span>
    @endforeach
</div>
```

Nonetheless - Thank you! It must have been something with the syntax like you say.

**Comment by damiani** [comment]
Good deal! Let me know if it resurfaces.
