### ISSUE TITLE
Nested @include in blades not working

### ISSUE THREAD

**Issue by molerat619** [tightenco/jigsaw#483]
**It should be super simple** and straight forward, but the following does not work:

**a.blade.php**
```php
@include('b', ['testPath' => 'c'])
```

**b.blade.php**
```php
@include($testPath)
```

`c.blade.php` can be whatever.. This won't work because `$testPath` will be empty and you get this error: `View [] not found.`.

But if I do `{{ $testPath }}` anywhere in `b.blade.php` and comment the `@include`-statement out, the content of the variable is correct. Also, when I hardcode `@include(c.blade.php)` it works as well.

Any idea why the @include-statement won't evaluate the variable `$testPath` correctly?

**Comment by damiani** [comment]
No, this works fine when I test it. Can you provide a link to your repo, so I can see if there's something unusual going on?

**Comment by bakerkretzmar** [comment]
@molerat619 are you still seeing this error? Can you try to reproduce it and show us? Thanks.

**Comment by molerat619** [comment]
Sorry @bakerkretzmar, I am currently not working on this and I was too busy to create a repo so it can be reproduced, but I know the issue still exists. I can imagine it's something with my setup, but I have no clue what. Once I find the time to make repo, I will get back to you. Thanks.
