### ISSUE TITLE
Fatal error on init

### ISSUE THREAD

**Issue by vaidotas-adf** [tightenco/jigsaw#484]
jigsaw init command fails with following error message:
`
Fatal error: Declaration of TightenCo\Jigsaw\Scaffold\PresetScaffoldBuilder::init($preset) must be compatible with TightenCo\Jigsaw\Scaffold\ScaffoldBuilder::init(TightenCo\Jigsaw\Scaffold\ScaffoldBuilder $preset) in /{PATH_TO_PROJECT_DIR}/vendor/tightenco/jigsaw/src/Scaffold/PresetScaffoldBuilder.php on line 145
`

First got this error when trying to run existing project. Then tried setting up new jigsaw project, but same error occurs on init command.
How to reproduce issue (following installation instructions from website):
1. Create new project directory, cd to project directory
2. $ composer require tightenco/jigsaw
3. $ ./vendor/bin/jigsaw init

macOS Mojave 10.14.6, PHP version 7.2.22, jigsaw version 1.3.28

**Comment by damiani** [comment]
I've just pushed an update, v1.3.29, that should fix your issue.

**Comment by vaidotas-adf** [comment]
Thank you for fast response.

Ran `$ composer update` and now I'm getting another error.
```
Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\Output\stream_isatty() in /{PATH_TO_PROJECT_DIR}/vendor/symfony/console/Output/StreamOutput.php:113
Stack trace:
#0 /{PATH_TO_PROJECT_DIR}/vendor/symfony/console/Output/StreamOutput.php(51): Symfony\Component\Console\Output\StreamOutput->hasColorSupport()
#1 /{PATH_TO_PROJECT_DIR}/vendor/symfony/console/Output/ConsoleOutput.php(42): Symfony\Component\Console\Output\StreamOutput->__construct(Resource id #80, 32, NULL, NULL)
#2 /{PATH_TO_PROJECT_DIR}/vendor/tightenco/jigsaw/jigsaw-core.php(80): Symfony\Component\Console\Output\ConsoleOutput->__construct()
#3 /{PATH_TO_PROJECT_DIR}/vendor/illuminate/container/Container.php(801): {closure}(Object(Illuminate\Container\Container), Array)
#4 /{PATH_TO_PROJECT_DIR}/vendor/illuminate/container/Container.php(687): Illuminate\Container\Container->build(Object(Closure))
#5 /{PATH_TO_PROJECT_DIR}/vendor/illuminate/container/Cont in /{PATH_TO_PROJECT_DIR}/vendor/symfony/console/Output/StreamOutput.php on line 113
```

I'm starting to suspect that something is broken with my PHP config on this particular computer, as I had no such issues with jigsaw on another computer.

**Comment by damiani** [comment]
Yes, something odd is going on, `stream_isatty()` is a built-in PHP function as of 7.2.0. Is it possible you're inadvertently running an older version of PHP?

**Comment by vaidotas-adf** [comment]
Even if `php --version` reported 7.2.22 in terminal, jigsaw was using default one from macOS, which is 7.1.33. Fixed it by correctly setting up PATH variables.
Thanks for support.
