### ISSUE TITLE
Is there a way to trigger a production build via PHP?

### ISSUE THREAD

**Issue by tomlongo** [tightenco/jigsaw#485]
I'd like to give clients access to a page that allows them to push a button to re-deploy a production build after they have updated the datasource. Essentially the equivalent of running `npm run production` but via a PHP rather than command line.

**Comment by mewejo** [comment]
I've not tested it, but you might be able to do something with what's in the executable file: https://github.com/tightenco/jigsaw/blob/master/jigsaw

**Comment by bakerkretzmar** [comment]
@tomlongo if you really need to run `npm run production` and rebuild the site's assets, your best bet is probably to actually just run `npm run production` in the project directory—I would use [Symfony's Process component](https://symfony.com/doc/current/components/process.html) for this, it's like `shell_exec` but better.

If you don't need `npm` and you just want the equivalent of `jigsaw build`, you could still use the Process component or you can basically recreate the `jigsaw` binary (which is just PHP) inside a controller or something, as @mewejo suggested.

Let us know if that works!

**Comment by purplman** [comment]
Hi, I tried to run `npm run dev` via the Symfony's Process component and it says `'npm' is not recognized as an internal or external command, operable program or batch file.` How can I fix this?

**Comment by bakerkretzmar** [comment]
What kind of environment are you running it in? Is it a regular web server? Some kind of build pipeline?

Does running an `npm` command directly work (i.e. are you positive `npm` is available in the shell path)?

**Comment by purplman** [comment]
Xampp server on Windows. I'm trying to generate a pdf with [relaxed js](https://github.com/RelaxedJS/ReLaXed). Yes running the command directly generates the pdf. 
The command is `relaxed index.html --build-once`

`C:\\path\\relaxed C:\\xampp\\html_file --build-once` works if I type it directly. But fails with the process

**Comment by bakerkretzmar** [comment]
Can you share a code snippet of what you're doing to run the command using the Process component?

**Comment by purplman** [comment]
`// RELAXED_PATH=C:\Users\Razer\AppData\Roaming\npm\relaxed
$html_file is the full path to the file to be converted to pdf
$command = [env('RELAXED_PATH'), $html_file, '--build-once'];
$process = new Process($command);
$process->run();`

The command "C:\Users\Razer\AppData\Roaming\npm\relaxed C:\xampp\prject\storage\app\public\resumes\index.html --build-once" failed. Exit Code: 9009(Unknown error) Working directory: C:\xampp\pro-resume\public Output: ================ Error Output: ================ '"node"' is not recognized as an internal or external command, operable program or batch file.

**Comment by bakerkretzmar** [comment]
I'm not sure what's happening there, sorry. It's definitely not a Jigsaw issue though, maybe search or open an issue in the `relaxed` repo? Or try reinstalling it?

**Comment by purplman** [comment]
Thank you for taking the time to reply. Good luck!
