### ISSUE TITLE
Enable right side nav links?

### ISSUE THREAD

**Issue by mickmcg** [tightenco/jigsaw#489]
How can I enable the right side nav links like on https://jigsaw.tighten.co/docs/installation/

**Comment by bakerkretzmar** [comment]
We built that ourselves, but you can see all the code for it in the docs repo, [tightenco/jigsaw-site](https://github.com/tightenco/jigsaw-site). It's just looking for all the `<h3>`s on the page.

https://github.com/tightenco/jigsaw-site/blob/master/source/_assets/js/app.js#L22-L26

https://github.com/tightenco/jigsaw-site/blob/master/source/_assets/js/components/navigation-on-page.vue#L1-L21
