### ISSUE TITLE
help to dockerize

### ISSUE THREAD

**Issue by Silver343** [tightenco/jigsaw#490]
Hi,

I'm looking to use docker to build a jigsaw site, I am using docker compose to build composer, php and node. I suspect the problem is in the volumes as i'm not sure what they should be.

any help would be appreciated.

**Comment by bakerkretzmar** [comment]
What's your current docker compose setup?

**Comment by Silver343** [comment]
Realized my problems were due to the fact that the `./vendor/bin/jigsaw init blog` command was calling composer require so I just didn't run it in my container.
