### ISSUE TITLE
Debugging build issues -> cache problem

### ISSUE THREAD

**Issue by molerat619** [tightenco/jigsaw#498]
Hi there,

when I get errors during my build, they usually look somewhat like this:

`PHP Notice:  Undefined variable: translatedBaseUrl in /Users/myusername/Sites/st-website/cache/9db0d9a664659c0f43f0f0e559631e11df734c95.php on line 56`

Now because of the **file name** of the cache file, I don't know where this error occurs. When I click on the file in my console, it can't be opened because it's not there anymore after the build.... how can I debug these problems?

Thank you!

**Comment by damiani** [comment]
If you get an error like that, the `cache` directory should still be around, at the top level of your Jigsaw project's directory; `9db0d9a664659c0f43f0f0e559631e11df734c95.php` will be in there. That file might be a little cryptic—it's very likely been processed by Blade, so it will be filled with `<?php echo` statements—but there's also a `PATH` comment at the bottom of the file that can help you trace the original file, if you don't recognize it from the markup.

**Comment by molerat619** [comment]
Thank you @damiani, you’re right!
Am 27. Aug. 2020, 16:30 +0200 schrieb Keith Damiani <notifications@github.com>:
