### ISSUE TITLE
Enable Elixir versioning

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/jigsaw#51]
https://laravel.com/docs/elixir#versioning-and-cache-busting

Will require bringing in the `elixir()` helper and making sure it's configured correctly for source and target directories.

**Comment by joshwhatk** [comment]
I would love to see this happen. I tried setting it up, but Jigsaw kept choking on the elixir() call.

For now, I've just added an extra step to my production build where I update file names. ¯\_(ツ)_/¯

**Comment by joshwhatk** [comment]
I finally got it to work, I'm going to submit a pull request for it 😄
