### ISSUE TITLE
[Proposal] PHAR Distribution

### ISSUE THREAD

**Issue by dccampbell** [tightenco/jigsaw#55]
Given that Jigsaw is primarily run as a CLI tool, would it be possible to [box](https://github.com/box-project/box2) it up and also officially distribute as a .phar?

**Comment by carbontwelve** [comment]
I too would like to see a phar distribution; having it installed globally via composer causes issue on my machine because it has conflicting requirements with some other globally installed tools - having it boxed as a phar would solve that.

**Comment by darol100** [comment]
I was able to build a package myself here are some instructions on how I did it: 


```bash
### First you need to download the lastest of phar
### Install phar-composer
php phar-composer.phar --version
chmod 755 phar-composer.phar
sudo mv phar-composer.phar /usr/local/bin/phar-composer

### Build and Install the jigsaw project
phar-composer install  tightenco/jigsaw
```

**Comment by damiani** [comment]
No plans for this at the moment, but if you run into dependency conflicts when installing globally via Composer, you can always install Jigsaw locally to your project.
