### ISSUE TITLE
[Feature] Allow for generating files with endings other than `.html`

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/jigsaw#56]
Allow Jigsaw to generate files with non-`.html` endings so folks can generate `.js` files or `.rss` files.

Reference: #46 #50

**Comment by damiani** [comment]
Support for this added in v1.0.0; you can now process `.js`, `.json`, `.xml`, `.rss`, `.txt`, and `.text` with Blade first: http://jigsaw.tighten.co/docs/other-file-types/

**Comment by tnorthcutt** [comment]
Just for anyone else arriving here from the googles, the updated docs link is http://jigsaw.tighten.co/docs/content-other-file-types/

**Comment by raniesantos** [comment]
Does this include blade.yml?

@tnorthcutt @damiani

**Comment by damiani** [comment]
No, the only Blade hybrid files currently supported are those listed above and in the docs. Feel free to PR, though; it would require simple changes to the Blade extension arrays in `ViewRenderer` and `InputFile`, I believe.
