### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by RanZix** [tightenco/jigsaw#6]
- illuminate/filesystem v5.1.8 requires symfony/finder 2.7.* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7].
    - Can only install one of: symfony/finder[v2.6.0, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.1, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.10, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.11, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.12, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.2, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.3, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.4, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.5, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.6, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.7, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.8, v3.0.0].
    - Can only install one of: symfony/finder[v2.6.9, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.0, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.1, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.2, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.3, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.4, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.5, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.6, v3.0.0].
    - Can only install one of: symfony/finder[v2.7.7, v3.0.0].
    - Installation request for symfony/finder == 3.0.0.0 -> satisfiable by symfony/finder[v3.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by adamwathan** [comment]
Are you trying to install from dev-master or a tagged release? It sounds like there's a conflict with some other packages you have installed globally (global composer installs can be a pain this way :/ ).

If that's an issue, you can instead install it locally in the folder where your static site is gonna live, just by doing a `composer init` and requiring Jigsaw there. Then you can run `./vendor/bin/jigsaw`, or add that relative path to your PATH and run it as `jigsaw`.

Hope that helps!

**Comment by RanZix** [comment]
I tried to install dev-master. Currently my global packages are: laravel, lumen, homestead and php-cs-fixer. I will try what you suggested. Thanks.
