### ISSUE TITLE
How would you include fonts?

### ISSUE THREAD

**Issue by PascaleBeier** [tightenco/jigsaw#61]
How would you include fonts - e.g. font-awesome?

My usual workflow using laravel-elixir for font-awesome inclusion is the following:

```bash
$ npm i --save font-awesome
```

```javascript
// gulpfile.js
mix.copy('node_modules/font-awesome/fonts', 'public/fonts');
```

When I do so using jigsaw, the font directory is either

1. Not moved from source/_assets/fonts to build_local or build_production
2. Deleted from build_local or build_production when running jigsaw build

How do I tackle this now? I seem to be missing something.

**Comment by lesaff** [comment]
This is how I do it with UIKit
```
    // Copy uikit fonts to public folder
    mix.copy('source/_assets/bower_components/uikit/fonts', 'source/assets/fonts/');
```

**Comment by PascaleBeier** [comment]
Thanks @lesaff, you helped me figuring it out.
