### ISSUE TITLE
How could we include a .md file from a file ?

### ISSUE THREAD

**Issue by chrisvidal** [tightenco/jigsaw#62]
Im having a privacy-policy.blade.php with some layout and im trying to include the content as mardown file like `@include('content/content-privacy.md')` but this does not compile.
I'd like to re-use the same content in different context (page and lightbox)

**Comment by Shaun2D2** [comment]
@chrisvidal I don't think this is currently supported, it sounds like your trying to mix blade and markdown together?  I looked over the docs http://jigsaw.tighten.co/docs/markdown/ and looks like you have to extend the template directly in the markdown.

**Comment by damiani** [comment]
@chrisvidal: @Shaun2D2 is correct regarding the current build...Markdown files require a YAML header which specifies a Blade template to extend, and the `@include` directive will only pick up `.blade.php` files. Does the content need to be in Markdown? If it's just plain text or HTML, you could store the content in `_content/content-privacy.blade.php` and `@include` that file in multiple places.

There are, however, some new features coming just around the corner that will give you several other ways to accomplish this. Can you give some more details about how your lightbox needs to access the content? Is it via javascript?

**Comment by chrisvidal** [comment]
thanks guys !
right now, it is a standard modal lightbox fully include in the page HTML,
then a js lib will toggle this modal.
The requirement is to have only one location to store a md content, in my case the privacy policy of the website client.
and i need to be able to display this privacy content from different context, meaning different layout and page in my case.
to give full example :
simple page : https://www.wootag.com/privacy-policy/
register page with the modal : https://www.wootag.com/signup/

my 1st version was using a blade template, with all the html markup, but when the client asked me to update this content, i lost quite a lots of time, hence i switch to markdown.
the content is easier to manage in a markdown way, because this is purely content in this case, easier to update (frequnce of privacy and terms update are about every 2-3 weeks)

Does this make sense ?
open to any suggestions

**Comment by damiani** [comment]
There's an update coming within a week or so that will give you a few options for doing this, including your original approach—the ability to `@include` and parse that markdown file (and a variety of other file types, for that matter) directly in your `privacy-policy.blade.php` template, and again in your lightbox template. I'll notify you when those enhancements are live.

**Comment by chrisvidal** [comment]
sounds like a good plan ! thanks  !

**Comment by erickpatrick** [comment]
This one can be closed.

**Comment by damiani** [comment]
Added support for `@include`-ing a Markdown file in v1.0.0
