### ISSUE TITLE
Customizing Parsedown

### ISSUE THREAD

**Issue by agentphoenix** [tightenco/jigsaw#64]
I was looking to tap in to Parsedown's ability to create custom Markdown tags, but I'm not seeing a way to actually get at the instance of Parsedown that's being used or override the instance with an extended instance that includes my customizations. Am I missing something or is that just not possible with Jigsaw?

**Comment by adamwathan** [comment]
Yeah not currently possible, interesting idea for @besologic @damiani or @mattstauffer though?

**Comment by mattstauffer** [comment]
I love the idea.

**Comment by damiani** [comment]
Agreed, it's a great idea; I'm looking into it.

**Comment by damiani** [comment]
@agentphoenix Thanks for the suggestion! This has been added, see https://github.com/tightenco/jigsaw/pull/68

**Comment by agentphoenix** [comment]
This is awesome! Thank you guys for considering and implementing this. Jigsaw has been awesome and this change just makes it even more flexible for all sorts of things. Keep up the great work!
