### ISSUE TITLE
[Feature Request] Folder / SubFolder Pretty URL structure for sites??

### ISSUE THREAD

**Issue by abhi-cognitivo** [tightenco/jigsaw#70]
Since Jigsaw does a pretty good job with "pretty urls," automatically creating folders and placing the files as index, if there were a way for it to create sub folders which for me currently is a headache as my site has a deeper structure.

**currently this is possible..**.
sales.blade.php -> creates local/sales/index.html
**could it be possible to do this...**
sales.features.blade.php -> creates local/sales/features/index.html

thanks!

**Comment by abhi-cognitivo** [comment]
Ok apparently its possible. but the doc doesn't explicitly explain it.

fyi,

this is currently do-able...
local/sales.blade.php -> creates local/sales/index.html
but to achieve sub directly, create the base folder first.
local/sales/features.blade.php -> creates local/sales/features/index.html

**Comment by damiani** [comment]
Right, all folders (that aren't prepended with `_`) will be reflected in the URL path that gets built, so you're free to nest things however you'd like! 👍
