### ISSUE TITLE
[Feature] Table of contents generated in at least .md files

### ISSUE THREAD

**Issue by Cysioland** [tightenco/jigsaw#74]

**Comment by damiani** [comment]
Can you provide some more details? This is probably possible with our new Collections feature.

**Comment by damiani** [comment]
Take a look at [collections](http://jigsaw.tighten.co/docs/collections/) in v1.0.0, which makes this possible. There's also example code for a generated nav in the [demo repo](https://github.com/tightenco/jigsaw-collections-demo/blob/master/source/_layouts/sidebar/post-menu.blade.php).
