### ISSUE TITLE
Accessing the query string to populate options in the config

### ISSUE THREAD

**Issue by jabberdog** [tightenco/jigsaw#77]
I think it'd be a good idea to be able to access query strings from the URL and pass them back through the config.php file in order to generate strings that you can use for links for the blade template.

e.g. http://www.example.com/?test=xxxtestxxx&anothertest=xxxanothertestxxx

Would filter through the config as maybe:

`'link' => 'http://www.thisisanotherexample.com?',
'query' => http_build_query(array(
    't1' => isset($_GET['test']) ? $_GET['test'] : null,
    't2' => isset($_GET['anothertest']) ? $_GET['anothertest'] : null,
)),`

Back through the view as:

`<a href="{{ $link.$query }}">Test</a>`

Which would render as:

`<a href="http://www.thisisanotherexample.com?t1=xxxtestxxx&t2=xxxanothertestxxx">Test</a>`

**Comment by damiani** [comment]
Interesting, what would you envision as a use case for this feature?

**Comment by jabberdog** [comment]
If I wanted to build a one page application that could take inbound parameters and pass that data through (perhaps even cookie it) to the view, to generate outbound links.

Would be good for anybody who builds advertorials and such for advertising in an affiliate marketplace.

**Comment by damiani** [comment]
Jigsaw generates static HTML, though, meaning your built site can't process the `$_GET` server variable with PHP when someone visits it. You could, however, pull this off using Javascript to modify the outbound links on a page based on the query string.

**Comment by jabberdog** [comment]
Yeah, I was working on a method to do that as we speak. I just thought it would be a good idea to address how one might be able to use `$_GET` variables to produce content in the build.

**Comment by damiani** [comment]
Adding support for this would be beyond the scope of Jigsaw as a static site generator, as this functionality would require the built site to process PHP (at which point it would no longer be static). Thanks for the idea, though, and it's always great to see people finding new and unexpected uses for Jigsaw!
