### ISSUE TITLE
jigsaw init crashes if path exists

### ISSUE THREAD

**Issue by carbontwelve** [tightenco/jigsaw#8]
Warning: mkdir(): File exists in C:\Users\Simon\Documents\GitHub\jigsaw\vendor\illuminate\filesystem\Filesystem.php on line 337

If you run `jigsaw init` twice it will crash due to mkdir failing.

**Comment by RanZix** [comment]
When you do jigsaw init, jigsaw tries to create new  directory. In your case jigsaw tried to dir with same name twice. 

Try jigsaw init <dir-name>

**Comment by adamwathan** [comment]
Accidentally fixed by https://github.com/tightenco/jigsaw/commit/4247902341ff0c9416b3e22b5beac6d27f4f7c56 :)
