### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#80]
Installation fails...

`Using version ^0.6.4 for tightenco/jigsaw
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove illuminate/contracts v5.4.9
    - Conclusion: don't install illuminate/support v5.4.13
    - Conclusion: don't install illuminate/contracts v5.4.9
    - illuminate/support v5.2.43 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.45 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.0 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.19 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.21 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.24 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.26 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.27 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.28 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.31 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.32 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.37 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.6 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.2.7 requires illuminate/contracts 5.2.* -> satisfiable by illuminate/contracts[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support v5.3.0 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - illuminate/support v5.3.16 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - illuminate/support v5.3.23 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - illuminate/support v5.3.4 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - illuminate/support v5.2.25 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - Can only install one of: illuminate/contracts[v5.2.0, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.19, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.21, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.24, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.25, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.26, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.27, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.28, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.31, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.32, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.37, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.43, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.45, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.6, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.2.7, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.3.0, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.3.16, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.3.23, v5.4.9].
    - Can only install one of: illuminate/contracts[v5.3.4, v5.4.9].
    - Installation request for illuminate/contracts (locked at v5.4.9) -> satisfiable by illuminate/contracts[v5.4.9].
    - Installation request for tightenco/jigsaw ^0.6.4 -> satisfiable by tightenco/jigsaw[v0.6.4].
    - Conclusion: don't install tightenco/collect v5.4.12|install illuminate/support v5.2.43|install illuminate/support v5.2.45|install illuminate/support v5.3.0|install illuminate/support v5.3.16|install illuminate/support v5.3.23|install illuminate/support v5.3.4|install illuminate/support v5.2.0|install illuminate/support v5.2.19|install illuminate/support v5.2.21|install illuminate/support v5.2.24|install illuminate/support v5.2.25|install illuminate/support v5.2.26|install illuminate/support v5.2.27|install illuminate/support v5.2.28|install illuminate/support v5.2.31|install illuminate/support v5.2.32|install illuminate/support v5.2.37|install illuminate/support v5.2.6|install illuminate/support v5.2.7
    - Conclusion: remove tightenco/collect v5.4.12|install illuminate/support v5.2.43|install illuminate/support v5.2.45|install illuminate/support v5.3.0|install illuminate/support v5.3.16|install illuminate/support v5.3.23|install illuminate/support v5.3.4|install illuminate/support v5.2.0|install illuminate/support v5.2.19|install illuminate/support v5.2.21|install illuminate/support v5.2.24|install illuminate/support v5.2.25|install illuminate/support v5.2.26|install illuminate/support v5.2.27|install illuminate/support v5.2.28|install illuminate/support v5.2.31|install illuminate/support v5.2.32|install illuminate/support v5.2.37|install illuminate/support v5.2.6|install illuminate/support v5.2.7
    - tightenco/jigsaw v0.6.4 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.43, v5.2.45, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.9, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.4.0|don't install tightenco/collect v5.4.12
    - don't install illuminate/support v5.4.9|don't install tightenco/collect v5.4.12
    - Installation request for tightenco/collect (locked at v5.4.12) -> satisfiable by tightenco/collect[v5.4.12].

Installation failed, reverting ./composer.json to its original content.`

**Comment by adamwathan** [comment]
Where are you trying to run `composer require tightenco/jigsaw`, globally, or inside an existing project?

I recommend following the installation instructions here, they address how to deal with dependency conflicts when installing globally:

http://jigsaw.tighten.co/docs/installation/

**Comment by cjf** [comment]
Sorry for the lack of detail.  I was doing the global install.  Installing locally seems to have worked.
