### ISSUE TITLE
Gulp not working if jigsaw installed locally instead of globally

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#81]
I performed a local install of jigsaw and am working through the docs.  I'm running into an error in the "Compiling Assets" section.  Namely, when running 'gulp', the 'jigsaw' is assumed to be installed globally instead of locally.

I had to pop in to gulpfile.js and change line 13 from 

`.exec('jigsaw build ' + env, ['./source/*', './source/**/*', '!./source/_assets/**/*'])`
to
`.exec('./vendor/bin/jigsaw build ' + env, ['./source/*', './source/**/*', '!./source/_assets/**/*'])`

Not sure the best way to fix it, but noting in the documentation seems like a good start.

**Comment by damiani** [comment]
Docs have been updated. Thanks!
