### ISSUE TITLE
[build] Customization of `sourcePath` folder not working

### ISSUE THREAD

**Issue by erickpatrick** [tightenco/jigsaw#82]
When setting `sourcePath` to a different folder (as seen on the last two commented lines of [this code](https://github.com/tightenco/jigsaw-collections-demo/blob/master/bootstrap.php)), it does not behave properly for things that need to be compiled.

## Environment
- Laravel Homestead VM 5.0.1 (bleeding edge)
- PHP 7.1-fpm
- jigsaw @ master (yes, bleeding edge code)

## Steps to reproduce
1) create a `boostrap.php` file on the main project folder
2) add `$sourcePath = cwd() . '/src'` (or change `/src` for anything but `/source`
3) run `jigsaw build` or `./vendor/bin/jigsaw build` depending on the type of installation

## Expected result
- use the new the new source path successfully to compile collections, simples pages, partials, etc without exceptions
- see properly compiled files on the destination folder (`build_local` or other if it was also set inside `bootstrap.php`)

## Actual result
- Exception is thrown stating that some layout, collection or simple page does not exist

![Screenshot](https://cloud.githubusercontent.com/assets/396013/23441713/46517b00-fe24-11e6-8b88-0370bc415fac.JPG)

**Comment by erickpatrick** [comment]
Having a closer look into the PRs for the project, I think @damiani is already working on something (#79) related to this, however, don't know yet if it's the case and if it solves the issue

**Comment by damiani** [comment]
Yes, a change to how this is handled is in the works; in the next release, you will be able to specify `source` and `build` locations as part of the configuration array in `config.php`. In the meantime, though, you can accomplish the same thing without using `bootstrap.php`, and instead just add your `$buildPath` or `$sourcePath` overrides to `config.php`, _before_ the config array is returned. So in your case:

> `config.php`
```php
<?php

$sourcePath = getcwd() . '/src';

return [
    ...
];
```

**Comment by erickpatrick** [comment]
Hi @damiani,

That's great! I confirm that the proposed answer works! Thank you very much.
