### ISSUE TITLE
Any plans to support Laravel Mix

### ISSUE THREAD

**Issue by kevin-coyle** [tightenco/jigsaw#88]
I seem to be using mix a lot more nowadays. Any plans to support it?

**Comment by erickpatrick** [comment]
Hi @kevin-coyle, I've created a PR (#89) that does exactly that. Could you check it and test with your projects as well?

**Comment by damiani** [comment]
Yes, it's in the works and covered in PR https://github.com/tightenco/jigsaw/pull/89
